### ISSUE TITLE
Add the `mxcsr` register to the x86_64 crate

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#1000]
To be used in `shim-sev`.

**Comment by haraldh** [comment]
See also https://github.com/enarx/xsave/blob/17300fc84ab326ab32d747c99c07f7bd3c06cadd/src/lib.rs#L117-L158

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1000?planning-poker) with ZenHub @jarkkojs @npmccallum @haraldh

**Comment by jarkkojs** [comment]
I already have almost finished patch for https://github.com/rust-osdev/x86_64.git but I bumped also to this:

https://docs.rs/x86_64-xsave/latest/x86_64_xsave/

It has a lot of intersection without our xsave crate. So should I continue doing what I'm doing or?

**Comment by jarkkojs** [comment]
The project I pointed out looks more abstracted than the stuff in x86_64 crate so I'll at least make a PR available over there.

**Comment by jarkkojs** [comment]
Thanks for re-opening this. It was triggered by a commit with `Closes: #1000`

**Comment by jarkkojs** [comment]
Updated PR https://github.com/rust-osdev/x86_64/pull/336 and I also dropped the Closes tag. It is better to use it for changes that migrate Enarx and xsave to use it.
