### ISSUE TITLE
DevConf.cz 2020

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#101]
Ben Fischer giving a talk on the 25th, at 10:30!
https://devconfcz2020a.sched.com/event/YOnJ/enarx-secured-attested-execution-on-any-cloud

# Info
https://www.devconf.info/cz/

# Dates
Event: 24 – 26 January 2020

# Location
Brno, Czech Republic

# CFP
done

**Comment by mbestavros** [comment]
Talk recordings have been tweeted out, so this is done.
