### ISSUE TITLE
41st IEEE Symposium on Security and Privacy

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#102]
# Info
https://www.ieee-security.org/TC/SP2020/

# Dates
- Event: 18 – 21 May  2020
(The Symposium will be held on May 18-20, 2020, and the Security and Privacy Workshops will be held on May 21, 2020)
- CFP closes: 1 February 2020

# Location
Hyatt Regency Hotel, San Francisco, California, USA

# CFP
https://www.ieee-security.org/TC/SP2020/cfpapers.html

- Paper submission deadline: Rolling (Next deadline: February 1, 2019)
- Submission site open for acceptance: 1 week before the rolling deadline
- Acceptance notification: 2 months after submission
- Camera-ready deadline: 1 month after acceptance

**Comment by mbestavros** [comment]
Closed due to missing CFP deadline.
