### ISSUE TITLE
Remove `KvmEncRegion`

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#1029]
After https://github.com/rust-vmm/kvm-ioctls/pull/178 is merged, remove `KvmEncRegion` from `src/backend/sev/snp/launch/*`

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1029?planning-poker) with ZenHub @haraldh @jarkkojs @npmccallum

**Comment by platten** [comment]
Blocked on milan kernel issues.
