### ISSUE TITLE
Add WASM information to the wiki

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#103]
Likely in the FAQ, at least for a start, as these are questions that have come up multiple times.

We need to at least briefly explain :
- what WASM is
- by extension, what WASI is
- why we want to use WASM

In time, we will have a longer explanation of WASM. @steveeJ was interested in writing some of it.

**Comment by axelsimon** [comment]
@steveeJ and i worked on a page this afternoon and after quite some editing, we have something that works :)
The Wasm page has been published: https://github.com/enarx/enarx/wiki/WebAssembly-(Wasm)

**Comment by mbestavros** [comment]
I'm ready to consider this done. Closing.
