### ISSUE TITLE
Deduplicate testaso

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1031]
The `testaso!()` macro is duplicated several places. We should maybe make a crate with it.

**Comment by Deepansharora27** [comment]
I would like to take this up @npmccallum

**Comment by haraldh** [comment]
@Deepansharora27 Thank you. Please notify us, when this is ready, as it needs us to create a new repository in the `enarx` organization.

**Comment by Deepansharora27** [comment]
@haraldh Is Creating a new repository a pre-requisite before I start to make the modules for the `testaso` crate ?

**Comment by haraldh** [comment]
@Deepansharora27 you can create a new repo in your own account space. When it is ready, we will import it from there.

**Comment by Deepansharora27** [comment]
Got it !! 
Thanks @haraldh 😊

**Comment by haraldh** [comment]
I am sorry... I just created a repo: https://github.com/haraldh/testaso

@npmccallum you may want to import that to enarx

**Comment by Deepansharora27** [comment]
> I am sorry... I just created a repo: https://github.com/haraldh/testaso
> 
> @npmccallum you may want to import that to enarx

Thanks 😊
I had the code ready but it had `memoffset` as a dependency. I wasn't aware that I will have to get rid of it.

**Comment by haraldh** [comment]
https://crates.io/crates/testaso

**Comment by haraldh** [comment]
I think I covered all appearances.
