### ISSUE TITLE
Run SGX hardware tests as part of CI

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#104]
We'd like to implement SGX hardware testing as part of our CI pipeline. That is: whenever a new PR is submitted, compile, run, and test the new code on real SGX chips to see if it works in a production environment.

CI providers certainly can't accomplish this alone; we'll have to provide our own hardware. But assuming we have the hardware available to run the tests, we still need to research and develop a way for those tests to happen as seamlessly as possible alongside our standard test pipeline. We don't currently have a clear answer to this; any number of approaches could work.

**Comment by connorkuehl** [comment]
Closed by #765
