### ISSUE TITLE
Deduplicate sgx/sallyport readv/writev

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#1090]
Somehow we have two implementations. Choose one and remove the other.

https://github.com/enarx/enarx/blob/main/internal/shim-sgx/src/handler/file.rs

https://github.com/enarx/sallyport/blob/main/src/syscall/file.rs

**Comment by rvolosatovs** [comment]
This should be closed by the ongoing sallyport rewrite, since implementations of these will live at `sallyport`, but specific platforms will be able to override the implementations.

**Comment by jarkkojs** [comment]
@haraldh, @rvolosatovs: what is this, and is this valid?

**Comment by rvolosatovs** [comment]
This should be done now
