### ISSUE TITLE
Pin releases to stable rust releases

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#1096]
To be able to compile releases years after the release date and to always use the same compiler (no sudden surprises), I suggest to pin a release to a stable release and use the `RUSTC_BOOTSTRAP=1` environment variable trick.

See also:
https://github.com/haraldh/enarx-keepldr/commit/42529f13921cd43faba1f1975862554a04269a33
and replace `stable` with a specific rust release version.

**Comment by npmccallum** [comment]
@haraldh Wrong repo. :)

**Comment by haraldh** [comment]
@npmccallum no, the old patch I did back then was against the old repo and has to be adapted to this one.

**Comment by platten** [comment]
@haraldh can you please confirm if this issue was addressed by #1168?
