### ISSUE TITLE
enarx binary reports wrong or misleading version when logging

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1098]
v0.1.2 reports `version 0.1.0` in first log output.

`enarx --version` outputs (correctly) `enarx 0.1.2`.

Observed:
```
[mikecamel@coffeelake timestamp]$ ENARX_BACKEND=sgx enarx run target/wasm32-wasi/release/timestamp.wasm 
[INFO  wasmldr] version 0.1.0 starting up
...
```

Expected 
```
[mikecamel@coffeelake timestamp]$ ENARX_BACKEND=sgx enarx run target/wasm32-wasi/release/timestamp.wasm 
[INFO  wasmldr] version 0.1.0 starting up
...
```

Suggest auto-filling from a known file for all possible outputs of versioning (and other related metadata).

**Comment by MikeCamel** [comment]
This is actually the wasmldr component - so it's misleading, not wrong.
Options:

1. keep wasmldr in step with versioning.  Probably the wrong approach.
2. have the enarx component output a separate entry.  Easier, more clear.

**Comment by Deepansharora27** [comment]
I would like to give this a shot @MikeCamel

**Comment by platten** [comment]
The issue is yours @Deepansharora27 😄

**Comment by npmccallum** [comment]
@Deepansharora27 For this issue, just remove [this line](https://github.com/enarx/enarx/blob/main/internal/wasmldr/src/main.rs#L75). That's it!

**Comment by Deepansharora27** [comment]
Thanks a lot for your Clarification @npmccallum 
Making a PR right away
