### ISSUE TITLE
enarx run sleep test fails

### ISSUE THREAD

**Issue by rwwwwww21** [enarx/enarx#1133]
Hi! I have successfully built enarx in my machine and tried a easy sleep example but got failed.

The sleep example is 
```
use std::{thread, time};
fn main() { 
    let sleep_time = time::Duration::from_secs(5);
    thread::sleep(sleep_time);}
```

I compiled into wasm32-wasi format successfully, but when tried to run with `enarx run --backend=sgx target/wasm32-wasi/release/sleep.wasm` but got error like 

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `38`,
 right: `4`', library/std/src/sys/unix/thread.rs:219:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unexpected AEX: GeneralProtection', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enarx-0.1.2/src/backend/sgx/thread.rs:96:18
```
I read source code and found that there is similar function used [here](https://github.com/enarx/enarx/blob/d2d2f60fb6453051a68c5388f1da17cfde6f38dd/tests/integration_tests.rs#L161) but run `cargo test` and didn't appear any error.

Looking forward to some reply! Thanks!

**Comment by rwwwwww21** [comment]
And I tried [debug document](https://github.com/enarx/enarx/blob/main/README-DEBUG.md). 

However, in my machine(SGXv2), it cannot gdb successfully like as explained in the doc.

When I enter `cont` twice or typed `list` in the remote gdb, it just got aborted(core dumped)

**Comment by nickvidal** [comment]
Hi @rwwwwww21, thanks for your comment!

I wasn't able to reproduce this, it works for me.

What system are you using?

**Comment by rwwwwww21** [comment]
@nickvidal Thanks for your reply!
My system is Linux 5.11.0 ubuntu with SGXv1 (fixed for the previous statusment), enarx is the d2d2f60fb6453051a68c5388f1da17cfde6f38dd. "I wasn't able to reproduce this, it works for me." It means the gdb works successfully or the simple sleep test works or the both? 

In fact, I produces a [docker](https://hub.docker.com/repository/docker/rmheng/enarx) but it actually too big. XD

**Comment by nickvidal** [comment]
The simple sleep test works. If you run enarx info, what does that give you?

**Comment by rwwwwww21** [comment]
Sorry for late reply. My enarx info is
```
root@b10ad240c022:/# enarx info
Backend: sgx
 ✔ Driver: /dev/sgx_enclave
 ✔ CPU Manufacturer: GenuineIntel
 ✔  SGX Support
 ✔   Version 1
 ✗   Version 2
 ✔   FLC Support
 ✔   Max Size (32-bit): 2 GiB
 ✔   Max Size (64-bit): 64 GiB
 ✔   MiscSelect: (empty)
 ✔   Features: DEBUG | MODE64BIT | PROVISIONING_KEY | EINIT_KEY
 ✔   Xfrm: X87 | SSE | AVX | YMM | BNDREG | BNDCSR
 ✔   EPC Size: 94 MiB
Backend: sev
 ✗ Driver: /dev/sev
 ✗  SEV is enabled in host kernel
 ✗  /dev/sev is readable by user
 ✗  /dev/sev is writable by user
 ✗ Driver: /dev/kvm
 ✗  API Version
 ✗ MEMLOCK rlimit allows for: 0 keeps (soft limit = 65536 bytes, hard limit = 65536 bytes)
 ✗ CPU Manufacturer: GenuineIntel
 ✗  Microcode support
 ✗  Secure Memory Encryption (SME)
 ✗   Physical address bit reduction
 ✗   C-bit location in page table entry
 ✗  Secure Encrypted Virtualization (SEV)
 ✗   Number of encrypted guests supported simultaneously
 ✗   Minimum ASID value for SEV-enabled, SEV-ES disabled guest
 ✗  Secure Encrypted Virtualization Encrypted State (SEV-ES)
 ✗  Page Flush MSR available

The MEMLOCK rlimit must be large enough to accommodate the Enarx shim, wasmldr, and the memory pressure requirements of the target workloads across all deployed SEV keeps.

Backend: kvm
 ✗ Driver: /dev/kvm
 ✗  API Version
```

**Comment by rwwwwww21** [comment]
@nickvidal Another question happened, run `enarx info` and `cargo test` everything is ok, but when tried hello-world.wasm, it seemed that program direct return without return results.
```
root@a0800c8ff5d8:~/enarx# enarx run ../test-enarx/hello-world/target/wasm32-wasi/release/hello-world.wasm
[INFO  wasmldr] version 0.1.0 starting up
[WARN  wasmldr] 🌭DEV-ONLY BUILD, NOT FOR PRODUCTION USE🌭
[DEBUG wasmldr] parsing argv
[INFO  wasmldr] opts: RunOptions {
        envs: [],
        module: None,
        args: [],
    }
[INFO  wasmldr] reading module from fd 3
[INFO  wasmldr] running workload
[DEBUG wasmldr::workload] configuring wasmtime engine
[DEBUG wasmldr::workload] instantiating wasmtime linker
[DEBUG wasmldr::workload] adding WASI to linker
[DEBUG wasmldr::workload] creating WASI context
[INFO  wasmldr::workload] inheriting stdio from calling process
[DEBUG wasmldr::workload] creating wasmtime Store
[DEBUG wasmldr::workload] instantiating module from bytes
[DEBUG wasmldr::workload] adding module to store
[DEBUG wasmldr::workload] getting module's default function
[DEBUG wasmldr::workload] calling function
```

**Comment by nickvidal** [comment]
Hi @rwwwwww21, I think I know what's the issue. This usually happens when your installation was not complete. Did you install nightly? Would you be able to start over and follow each step here:

https://enarx.dev/docs/Installation/Setup

https://enarx.dev/docs/Installation/Enarx

**Comment by rwwwwww21** [comment]
@nickvidal  thank you for the quick reply! I reinstalled enarx with the following links but faces the same problem. I start my installation from a brand-new ubuntu:20.04 image from docker.io and follow the initial setup. 

Information about rustup is :
```
root@231241f4e537:/test-enarx/hello-world# rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0-nightly (e6b883c74 2021-12-08)`
```

**Comment by nickvidal** [comment]
Are you running Ubuntu from a VM? This would not work because you need direct access to the hardware.

**Comment by rwwwwww21** [comment]
> Are you running Ubuntu from a VM? This would not work because you need direct access to the hardware.

Sorry for late reply. I am running Ubuntu from a docker container with SGX-driver support use `--device /dev/sgx_enclave`.

**Comment by rwwwwww21** [comment]
@nickvidal @rvolosatovs 
Hi, I tried other simple rust example, but got different errors. I tried to read strings from a text, and the code is 
```
use std::fs;
use std::io::Read;

fn main() {
    let mut f = fs::File::open("text.txt").unwrap();
    let mut contents = String::new();
    f.read_to_string(&mut contents).unwrap();
    println!("{}", contents);
}
```
I compile into wasm32-wasi .wasm and run successfully with command
`RUST_LOG=enarx_wasmldr=info RUST_BACKTRACE=1 cargo run 3< target/wasm32-wasi/release/read-example.wasm`. But when on the enarx, `enarx run target/wasm32-wasi/release/read-example.wasm` would end with error
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to find a pre-opened file descriptor through which \"text.txt\" could be opened" }', src/main.rs:6:44

I'm confused why got the different results. If wasm don't support file operation, why `RUST_LOG=enarx_wasmldr=info RUST_BACKTRACE=1 cargo run` can got the right output?

Looking forward to some reply.

**Comment by rwwwwww21** [comment]
I'm trying to comprehend the enarx and have some stupid question...

The [KEEP_BIN](https://github.com/enarx/enarx/blob/6775871990a6c545fb586f92e048a88c0316df6c/tests/common/mod.rs#L10) here seems to be an environment variable, but when I tried to print but got `not defined` error?

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1133?planning-poker) with ZenHub @npmccallum @haraldh

**Comment by haraldh** [comment]
We don't support the `nanosleep` syscall 35 yet.

**Comment by haraldh** [comment]
> @nickvidal @rvolosatovs Hi, I tried other simple rust example, but got different errors. I tried to read strings from a text, and the code is
> 
> ```
> use std::fs;
> use std::io::Read;
> 
> fn main() {
>     let mut f = fs::File::open("text.txt").unwrap();
>     let mut contents = String::new();
>     f.read_to_string(&mut contents).unwrap();
>     println!("{}", contents);
> }
> ```

@rwwwwww21 you can't open files in the enclave yet... it has no filesystem yet.

**Comment by nickvidal** [comment]
Hi @haraldh and @platten, do we have an estimate of when we'll support filesystem just so that @rwwwwww21 is aware?

**Comment by haraldh** [comment]
@nickvidal I would guess a couple of months

**Comment by rwwwwww21** [comment]
> We don't support the `nanosleep` syscall 35 yet.

Thanks for your reply! But why don't appear `unsupport syscall`  which in the `unknown_syscall`?

**Comment by haraldh** [comment]
> > We don't support the `nanosleep` syscall 35 yet.
> 
> Thanks for your reply! But why don't appear `unsupport syscall` which in the `unknown_syscall`?

You have to compile it yourself from the git repo, with the `dbg` feature enabled to get that output.

```
$ ENARX_BACKEND=kvm cargo run --features dbg -- run /path/to/test.wasm
[…]
```

**Comment by rwwwwww21** [comment]
Thanks! But I still feel comfused about this question.

> I'm trying to comprehend the enarx and have some stupid question...
> 
> The [KEEP_BIN](https://github.com/enarx/enarx/blob/6775871990a6c545fb586f92e048a88c0316df6c/tests/common/mod.rs#L10) here seems to be an environment variable, but when I tried to print but got `not defined` error?

**Comment by haraldh** [comment]
> Thanks! But I still feel comfused about this question.
> 
> > I'm trying to comprehend the enarx and have some stupid question...
> > The [KEEP_BIN](https://github.com/enarx/enarx/blob/6775871990a6c545fb586f92e048a88c0316df6c/tests/common/mod.rs#L10) here seems to be an environment variable, but when I tried to print but got `not defined` error?

@rwwwwww21 This environment variable is only set in the host environment. It is not passed to the keep environment and not further not passed to the wasm environment.

**Comment by haraldh** [comment]
> We don't support the `nanosleep` syscall 35 yet.

Opened https://github.com/enarx/sallyport/issues/55 for this.
