### ISSUE TITLE
Question about get_att in SGX

### ISSUE THREAD

**Issue by RMheng** [enarx/enarx#1134]
Hi~

I read the enarx source code but felt puzzled with attestation with SGX. 

It seems enarx SGX implemented `get_att` with a self-defined syscall number `0xEA01`. When enclave application invoke `get_att`, syscall with number `0xEA01` happens, I think the the actually execution of syscall is performed by host kernel, but confused that syscall with number `0xEA01` is whether realized in linux kernel? (But I cannot find any implementation details)

Another question is the attestation seems only compute the size of reports. In my understanding, SGX attestation should be exchanging quote report which is written in your [slides](https://github.com/enarx/enarx.github.io/raw/master/docs/enarx_slides_2020-12.pdf) too. And If we want to implement Local attestation and remote attestation in enarx like SGX, is it ok to directly apply SGX's? 

Looking forward to some reply!

**Comment by npmccallum** [comment]
@RMheng This is going to change in the coming days. However, the design is that this syscall is handled by the shim. See this: https://github.com/enarx/enarx/blob/main/internal/shim-sgx/src/handler/enarx.rs

**Comment by RMheng** [comment]
@npmccallum Thanks for your explanation. So now `get_att` in SGX is a prototype simulation？

**Comment by RMheng** [comment]
@npmccallum @haraldh  I read `get_att` in SEV which is more detailed and have another question...

When the program reached [guest_req()](https://github.com/enarx/enarx/blob/b9eb5aa562e90c652972e6cc0798ed5f8f431671/internal/shim-sev/src/snp/ghcb.rs#L502), a `vmmcall` will happen in [vmgexit](https://github.com/enarx/enarx/blob/b9eb5aa562e90c652972e6cc0798ed5f8f431671/internal/shim-sev/src/snp/ghcb.rs#L334).My question is when program called `vmmcall`, would the control of program go to the hypervisor and how is the program reflected?

I thought `vmmcall` would cause guest os exit and the control of program will return to the host, so the program would return to the [vcpu_fd.run()](https://github.com/enarx/enarx/blob/b9eb5aa562e90c652972e6cc0798ed5f8f431671/src/backend/kvm/thread.rs#L110), but I cannot find any return value of `vcpu_fd.run()` related to `vmmcall`. 

And in issue#483, it said
> So, with regards to AMD, looks like rdrand and rdseed won't cause an exit. cpuid, rdmsr and wrmsr will cause a non-automatic exit, that will cause the processor to issue a #VC that will handled by the guest to cause a VMGEXIT. I guess in our case, we just handle it internally instead of transfering control to the hypervisor. (15.35.5)

So enarx shim would handle the `vmmcall` but where handled? 

That's my new question and expect some explanation~

**Comment by haraldh** [comment]
> 

@RMheng this special guest os exit is handled by the linux kernel itsself and is basically forwarded to the SNP firmware and the answer is returned in the Guest Hypervisor Communication Block (GHCB). The entire conversation with the SNP firmware is encrypted and signed with a key, which was provided in the SNP secrets page by the SEV-SNP firmware.

So, this vmexit / vmmcall will not reach host userspace.

**Comment by RMheng** [comment]
@haraldh I thought `enc_payload` and `dec_payload` are handled by the shim, what will linux kernel and SNP firmware handled? (attestation report?)

**Comment by haraldh** [comment]
> @haraldh I thought `enc_payload` and `dec_payload` are handled by the shim, what will linux kernel and SNP firmware handled? (attestation report?)

enc/dec_payload encrypt and decrypt the messages with the SNP firmware.. yes, mainly for the attestation report. The linux kernel is basically just a proxy inbetween this communication channel.

**Comment by RMheng** [comment]
Thanks! Got it

**Comment by RMheng** [comment]
@npmccallum @haraldh @connorkuehl Sorry for reopened the issue. I still have a question, what's the relationship between the following attestation process with the attestation [here](https://github.com/enarx/sev/tree/e0e17aac9249b00b0cb3e24a2780ca814d229a11/docs/attestation). I guess what link did is SNP firmware's task(generating key chains).

**Comment by RMheng** [comment]
I should read more careful... Thanks a lot!

**Comment by rwwwwww21** [comment]
@haraldh  Sorry I got a question. What would happened after [vmmcall](https://github.com/enarx/enarx/blob/5e03c96b4ec48e70df48a9f6aa8a6976f53f9e15/internal/shim-sev/src/snp/ghcb.rs#L335), `vmmcall` seems to introduce an exception to SNP-VM, and control would go to the host linux kernel, but in [enter()](https://github.com/enarx/enarx/blob/5e03c96b4ec48e70df48a9f6aa8a6976f53f9e15/src/backend/kvm/thread.rs#L108), where handle the vmmcall?

**Comment by haraldh** [comment]
> 

@rwwwwww21 Most `vmmcall` exits are caught by the host linux kernel and are not propagated to the host kvm userspace application (`enter()`).

In case of the GHCB protocol vmmcall, none of these calls ever reach user space on the host.

**Comment by rwwwwww21** [comment]
So when host linux kernel finished handling , program automatically returned to the SNP-VM and continued [vmgexit](https://github.com/enarx/enarx/blob/5e03c96b4ec48e70df48a9f6aa8a6976f53f9e15/internal/shim-sev/src/snp/ghcb.rs#L304) ?

> > 
> 
> @rwwwwww21 Most `vmmcall` exits are caught by the host linux kernel and are not propagated to the host kvm userspace application (`enter()`).
> 
> In case of the GHCB protocol vmmcall, none of these calls ever reach user space on the host.

**Comment by haraldh** [comment]
> So when host linux kernel finished handling , program automatically returned to the SNP-VM and continued [vmgexit](https://github.com/enarx/enarx/blob/5e03c96b4ec48e70df48a9f6aa8a6976f53f9e15/internal/shim-sev/src/snp/ghcb.rs#L304) ?

@rwwwwww21 yes
