### ISSUE TITLE
Make sure tcs::Flags::DBGOPTIN is cleared on EADD

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#114]
As per documentation in Table 38-6.

**Comment by npmccallum** [comment]
Does the kernel do this for us?

**Comment by lkatalin** [comment]
That sounds plausible. I wanted to double check when I came across it in the documentation so I created the issue as a reminder. At least, it may be good to write a sanity-check test for it.

**Comment by lkatalin** [comment]
This issue seems like it should be one of many tests that the leaf instructions are doing what we generally expect. Maybe I should assign it to a larger meta-issue for testing, or re-name it, or close it and open a more general one.

**Comment by lkatalin** [comment]
Closed because this should be a more comprehensive issue re: testing for each leaf function.
