### ISSUE TITLE
Support for ACCEPT on file descriptors

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1143]
We need to be able to have listening sockets (via passed-in fds) in applications.  This will make demos *much* more interesting!

**Comment by npmccallum** [comment]
Passing in listening file descriptors is fine. But we need to be able to `accept()` on them from within WASI.

We have a few options and I have a call with wasmtime people this afternoon to discuss. I will fill in this issue when I have more information.

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1143?planning-poker) with ZenHub @haraldh @npmccallum
