### ISSUE TITLE
Provide guidance on supported hardware

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1157]
The current [introduction](https://enarx.dev/docs/Installation/Requirements) doesn't provide details of supported chipsets.  This should be provided to allow those interested in the project to get more easily involved.

**Comment by MikeCamel** [comment]
Current status (needs checking): 

- AMD SEV SNP available in some(?) Milan-series CPUs
- SGX EDMM available in some CoffeeLake series CPUs

**Comment by nickvidal** [comment]
Documentation updated with recommendations from Nathaniel (Milan and Ice Lake):

https://enarx.dev/docs/Installation/Requirements
