### ISSUE TITLE
enarx crate build fails with recent nightly

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1167]
`nightly-x86_64-unknown-linux-gnu updated - rustc 1.59.0-nightly`, as per instructions here: [https://github.com/enarx/enarx/wiki/Install-Enarx](https://github.com/enarx/enarx/wiki/Install-Enarx)

`cargo +nightly install --bin enarx -- enarx`

```
    Updating crates.io index
  Installing enarx v0.1.2
  Downloaded x86_64 v0.14.7
  Downloaded 1 crate (74.0 KB) in 0.30s
   Compiling proc-macro2 v1.0.34
   Compiling unicode-xid v0.2.2

...

Compiling structopt v0.3.25
   Compiling sallyport v0.1.0
error: cannot find macro `asm` in this scope
   --> /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/sallyport-0.1.0/src/lib.rs:188:13
    |
188 |             asm!(
    |             ^^^
    |
    = note: consider importing this macro:
            core::arch::asm

error[E0283]: type annotations needed
   --> /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/sallyport-0.1.0/src/lib.rs:184:37
    |
184 |                 ret: [ret.into(), 0.into()],
    |                                   --^^^^--
    |                                   | |
    |                                   | cannot infer type for type `{integer}`
    |                                   this method call resolves to `T`
    |
    = note: multiple `impl`s satisfying `primordial::Register<usize>: From<{integer}>` found in the `primordial` crate:
            - impl From<i16> for primordial::Register<usize>;
            - impl From<i32> for primordial::Register<usize>;
            - impl From<i64> for primordial::Register<usize>;
            - impl From<i8> for primordial::Register<usize>;
            and 6 more
    = note: required because of the requirements on the impl of `Into<primordial::Register<usize>>` for `{integer}`

For more information about this error, try `rustc --explain E0283`.
error: could not compile `sallyport` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `enarx v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-installlcKHbP`

Caused by:
  build failed
```

**Comment by nickvidal** [comment]
From @haraldh:

To fix this issue, we either:

- have to wait for all the crates to be updated, update our dependencies and our code, and release a new version...
- or release a new version, which uses a specific nightly version....
- or release a new version, which uses the RUST_BOOTSTRAP trick and rely on a stable version

**Comment by MikeCamel** [comment]
See https://github.com/enarx/enarx/issues/1096 for options for fix.

**Comment by nickvidal** [comment]
@haraldh's solution works on both Ice Lake and Milan:

https://github.com/enarx/enarx/pull/1168

Will close this once we have it merged in `enarx:main` and the docs updated.

**Comment by nickvidal** [comment]
Enarx 0.1.3 fixes this issue:

https://crates.io/crates/enarx/0.1.3

**Comment by MikeCamel** [comment]
Still fails for me, following instructions at [https://github.com/enarx/enarx/wiki/Install-Enarx](https://github.com/enarx/enarx/wiki/Install-Enarx)

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source $HOME/.cargo/env
rustup toolchain install nightly --allow-downgrade -t x86_64-unknown-linux-musl,x86_64-unknown-linux-gnu
sudo dnf install git curl gcc pkg-config openssl-devel musl-gcc
cargo +nightly install --bin enarx -- enarx
```

**Comment by nickvidal** [comment]
There's a note on the top of that page pointing to the new instructions:

> ⚠️ **Note:** a new version of this documentation is available at: https://enarx.dev/docs/Installation/Enarx

Not sure if deleting this wiki is a good idea, or if there's a better way to highlight that a new documentation is available. Any recommendations?

**Comment by MikeCamel** [comment]
Closing, moving issue to https://github.com/enarx/enarx/issues/1174
