### ISSUE TITLE
Write up contributions process

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#117]
Here's a set of contribution guidelines.  They need to be codified somewhere better than here.

0. make sure that _everything_ you're doing is in github.  It doesn't matter if it's not perfect.  Churn is expected, but we need the code there to start with.
1. ensure that no single issue should take more than 1-2 days to complete.  If you have an issue that will take more time, then break it down into separate issues, and link them (under the top issue if required).
2. only have 1-3 issues assigned to you at any time.
3. when you complete an issue, submit a PR.
4. review other folks' PRs.
5. listen to Mark, who will be hassling you if the above doesn't happen.
6. if this isn't working, let's talk.  I'm sure we can do better than the above, and I'm going to put an issue in github RIGHT NOW asking for process improvements.

**Comment by MikeCamel** [comment]
See, I did number 6!  Good me...

**Comment by axelsimon** [comment]
Well done!
I'm going to read through our current CONTRIBUTING.md file(s) and [How to Contribute](https://github.com/enarx/enarx/wiki/How-to-contribute) guide to ensure they are:
a/ consistent and
b/ include all your good points.

**Comment by axelsimon** [comment]
These points have been added to the How to Contribute page.

**Comment by axelsimon** [comment]
I'm now having some doubts: have all these points properly been made in the [adequate documentation](https://github.com/enarx/enarx/wiki/How-to-contribute-code)?

@m-dombrowski, maybe would you be interested in checking that out?

**Comment by m-dombrowski** [comment]
> I'm now having some doubts: have all these points properly been made in the [adequate documentation](https://github.com/enarx/enarx/wiki/How-to-contribute-code)?
> 
> @m-dombrowski, maybe would you be interested in checking that out?

Yes, I will take a look.

**Comment by axelsimon** [comment]
I think everything has been added to the documentation. Closing this.
