### ISSUE TITLE
Improve the contributions process

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#118]
Initial contributions process at [#117](https://github.com/enarx/enarx/issues/117) needs improvement.  Please help!

**Comment by axelsimon** [comment]
Accepting this task, with the following deliverable: a list of suggestions for improvements to how newcomers to the project can start contributing.
Implementing these changes (if accepted by the community) will be covered by another issue.

**Comment by axelsimon** [comment]
Here are various suggestions to improve how we welcome new contributors.

Some have already been adopted or are in the process of being adopted.

One of the things i think we need to do to is to make more mentions of:
- Confidential Computing (and link to articles we've written about, such as the [Now+Next one](https://next.redhat.com/2019/12/02/current-trusted-execution-environment-landscape/), even though it's 9 months old now)
- Our relationship to the Confidential Computing Consortium? While much smaller than the CNCF, it is a consortium in the same spirit, and that has bearing on contributors.

## Enarx.io
Bring links on front page up by ~70 px and change current links ("menu") to:
**Enarx** · **Documentation** · **Contribute** · **News**

Each link should not go straight to another page but open a paragraph under the menu describing what the link is about, then offer a link to get there.
Trying to classify them to see how they answer the basic why, what, how, who questions:

**Enarx**: why, what.
Links to > github.com/enarx/enarx, maybe also to the FAQ

**Documentation**: what, how.
Links to > github.com/enarx/enarx/wiki

**Contribute**: how (?)
Links to > wiki/How-to-contribute

**News** >  who, how
Links to Twitter (blog idea is still parked, for now)

Another option would be to go for a full one-page site, like quarkus or keylime.dev.

## Enarx/Enarx README.md

Logic: keep simple, give the basics, stay technically relevant.
For anything beyond that, take people to a longer intro.

- ~~Add link to chat~~ done
- ~~Add link to redhat.com~~ done
- Improve intro text: work being done in gdoc with Mike ( #172 )

## Enarx wiki
### Fix the multiple introductions issue

wiki/ (home) and wiki/Introduction need to be unified / clarified.
 
My feeling is that the wiki home should follow the same general approach as the README: provide the bare minimum (what, why) and immediately send people to further resources where they can get more details.

This reworked wiki home could continue the "Enarx for…" persona approach and suggest clearly defined paths.

Links to: FAQ

~~Move "We've known for a long time…" to top of introduction~~ done

### Wording improvements for the introduction
Some improved wording from the README review process should make it into the (improved) intro:
> "Confidential: nothing (except for the workload itself) has the visibility required to disclose the workload's sensitive information. All unauthorized access, even from the host computer the workload is deployed on, is blocked."

> "Integrity-protected: all attempts to manipulate the workload's memory (whether malicious or by accident) are blocked. The workload's data will never change without its blessing."

## Enarx flow page
Fold into a more general technical flow page?
