### ISSUE TITLE
Write initial proposal of WASI crypto primitives

### ISSUE THREAD

**Issue by ueno** [enarx/enarx#119]
To delegate the crypto operations to the host libraries for constant-timeness and certification purposes, we will need to extend WASI to have crypto hostcalls. Define those hostcalls as a proposal in the `witx` format, starting with a very simple primitives (like cryptographic hashes).

**Comment by steveeJ** [comment]
It will be beneficial to write it in the [witx format](https://github.com/WebAssembly/WASI/blob/04d4eba571dc1d6fe9ab129ea9343911bcc256dc/docs/witx.md), to propose the crypto module as part of the [WASI specification in witx](https://github.com/WebAssembly/WASI/tree/04d4eba571dc1d6fe9ab129ea9343911bcc256dc/phases/ephemeral/witx).

**Comment by ueno** [comment]
Current draft can be found at:
https://github.com/ueno/WASI/blob/wip/dueno/crypto-api/phases/ephemeral/witx/wasi_ephemeral_crypto.witx

@steveeJ comments appreciated

**Comment by steveeJ** [comment]
@ueno I took a review pass directly on the commit https://github.com/ueno/WASI/commit/717dd56629bcb09d876b852dcdb10baab4ab4a09. If you could open a PR (even in your own repo) that would be great. OTOH, we could also fork WASI to the enarx organization and work on it there.

**Comment by mbestavros** [comment]
Proposal is merged upstream per @ueno; closing.
