### ISSUE TITLE
SGX: recheck xsave

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#1190]
Fails with the rust integration tests:
```
$ ENARX_BACKEND=sgx RUSTFLAGS='-C target-cpu=x86-64-v4' cargo test
[…]
test echo ... FAILED
test memory_stress_test ... FAILED
test rust_sev_attestation ... FAILED
test unix_echo ... FAILED
[…]
```

While with `kvm` it works:
```
$ ENARX_BACKEND=kvm RUSTFLAGS='-C target-cpu=x86-64-v4' cargo test
[…]
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.10s
```

**Comment by haraldh** [comment]
Case solved... it's the XFRM mask for the enclave.
```
$ ENARX_BACKEND=sgx RUSTFLAGS='-C target-cpu=x86-64-v3' cargo test
```

works with:
```diff
--- a/internal/shim-sgx/src/lib.rs
+++ b/internal/shim-sgx/src/lib.rs
@@ -28,7 +28,7 @@ pub const ENCL_SIZE_BITS: u8 = 31;
 /// FIXME: doc
 pub const ENCL_SIZE: usize = 1 << ENCL_SIZE_BITS;
 
-const XFRM: Xfrm = Xfrm::from_bits_truncate(Xfrm::X87.bits() | Xfrm::SSE.bits());
+const XFRM: Xfrm = Xfrm::from_bits_truncate(Xfrm::X87.bits() | Xfrm::SSE.bits() | Xfrm::AVX.bits());
 
 /// Default enclave CPU attributes
 pub const ATTR: Attributes = Attributes::new(Features::MODE64BIT, XFRM);
```

**Comment by npmccallum** [comment]
@haraldh Is there any reason not to apply this patch?

**Comment by jarkkojs** [comment]
Running `ENARX_BACKEND=sgx RUSTFLAGS='-C target-cpu=x86-64-v4' cargo test`gives consistently:

```
Error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `/home/jarkko/Hacking/enarx/target/debug/build/openssl-sys-547fd1e6cb1e86e9/build-script-main` (signal: 4, SIGILL: illegal instruction)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SYSROOT
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rustc-link-lib=ssl
  cargo:rustc-link-lib=crypto
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-changed=build/expando.c
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jarkkojs** [comment]
I verified that I can compile C programs with libssl linked and pkgconfig is configured correctly, i.e. `/usr/lib/pkgconfig/libssl.pc` exists.

**Comment by jarkkojs** [comment]
@haraldh Did you *already* have success with this or should I investigate on Monday?

**Comment by npmccallum** [comment]
@jarkkojs  if this begins to look non-trivial, let's move on to attestation which is far more important.

**Comment by jarkkojs** [comment]
There is couple of opcodes that can be used in ECDSA implementation:

- VPMADD52HUQ
- VPMADD52LUQ

These can be used to implement multiplications in ECDSA. We can postpone this if we have the knowledge that aesmd does not have any code invoking these. I honestly know.

**Comment by haraldh** [comment]
> Running `ENARX_BACKEND=sgx RUSTFLAGS='-C target-cpu=x86-64-v4' cargo test`gives consistently:
> 
> ```
> Error: failed to run custom build command for `openssl-sys v0.9.72`
> 
> Caused by:
>   process didn't exit successfully: `/home/jarkko/Hacking/enarx/target/debug/build/openssl-sys-547fd1e6cb1e86e9/build-script-main` (signal: 4, SIGILL: illegal instruction)
>   --- stdout
>   cargo:rustc-cfg=const_fn
>   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
>   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
>   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
>   OPENSSL_LIB_DIR unset
>   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
>   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
>   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
>   OPENSSL_INCLUDE_DIR unset
>   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
>   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
>   cargo:rerun-if-env-changed=OPENSSL_DIR
>   OPENSSL_DIR unset
>   cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=OPENSSL_STATIC
>   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=SYSROOT
>   cargo:rerun-if-env-changed=OPENSSL_STATIC
>   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rustc-link-lib=ssl
>   cargo:rustc-link-lib=crypto
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=OPENSSL_STATIC
>   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-changed=build/expando.c
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> ```

compiling/building works for me... at my machine and the lab machines... Running (cargo test) fails.

**Comment by jarkkojs** [comment]
OK

> > Running `ENARX_BACKEND=sgx RUSTFLAGS='-C target-cpu=x86-64-v4' cargo test`gives consistently:
> > ```
> > Error: failed to run custom build command for `openssl-sys v0.9.72`
> > 
> > Caused by:
> >   process didn't exit successfully: `/home/jarkko/Hacking/enarx/target/debug/build/openssl-sys-547fd1e6cb1e86e9/build-script-main` (signal: 4, SIGILL: illegal instruction)
> >   --- stdout
> >   cargo:rustc-cfg=const_fn
> >   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
> >   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
> >   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
> >   OPENSSL_LIB_DIR unset
> >   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
> >   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
> >   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
> >   OPENSSL_INCLUDE_DIR unset
> >   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
> >   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
> >   cargo:rerun-if-env-changed=OPENSSL_DIR
> >   OPENSSL_DIR unset
> >   cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
> >   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
> >   cargo:rerun-if-env-changed=PKG_CONFIG
> >   cargo:rerun-if-env-changed=OPENSSL_STATIC
> >   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
> >   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
> >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
> >   cargo:rerun-if-env-changed=SYSROOT
> >   cargo:rerun-if-env-changed=OPENSSL_STATIC
> >   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
> >   cargo:rustc-link-lib=ssl
> >   cargo:rustc-link-lib=crypto
> >   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
> >   cargo:rerun-if-env-changed=PKG_CONFIG
> >   cargo:rerun-if-env-changed=OPENSSL_STATIC
> >   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
> >   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
> >   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
> >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
> >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
> >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
> >   cargo:rerun-if-changed=build/expando.c
> > warning: build failed, waiting for other jobs to finish...
> > error: build failed
> > ```
> 
> compiling/building works for me... at my machine and the lab machines... Running (cargo test) fails.

Right my bad. `cargo test` is what fails. Thanks for correction.

**Comment by haraldh** [comment]
Oh, with my mentioned patch, it all works now somehow... so we should apply it :)

**Comment by jarkkojs** [comment]
I'll check quickly.

**Comment by jarkkojs** [comment]
@haraldh Can you make a PR, or did you have one already?

**Comment by haraldh** [comment]
@jarkkojs here you go
