### ISSUE TITLE
Ensure `getatt()` on AMD  SEV-SNP is fully functional

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1211]
# Description:
The `getatt()` call is required for attestation and should work on platforms equipped with AMD SEV-SNP hardware.

# Acceptance Criteria:
- [ ]  A successfully passing test which validates the signature on the attestation message for getatt() on SEV-SNP
- [ ] Documentation updated

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1211?planning-poker) with ZenHub @haraldh @npmccallum

**Comment by platten** [comment]
@haraldh Is this working and can we close this?

**Comment by haraldh** [comment]
> @haraldh Is this working and can we close this?

@platten nobody has written the test yet
