### ISSUE TITLE
sgx: Reburnish get_attestation() implementation

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1212]
1. Import src/backend/sgx/attestation.rs either from 95dcb02ae6e4 (@platten) or 
   7f691c91783c (@haraldh). They provide the exact same version of the file.</del>
   - **Nothing** done. Upstream attestation.rs is the same, which means that this step is not required.
2. Import sgx crate with 41f347cf2a39 **reverted** (not cherry-picked) on top and make it compile together with the project.
   1. Fix compilation issues.
   2. Implement missing to_vec() to Attributes.
   3. Fix alignment of Attributes from 4 to 8.
   4. Add `ProductId` and `SecureVersionNumber` types. 
3. Reburnish internal/shim-sgx/src/handler/enarx.rs attestation so that it builds and functions correctly.

Note from @npmccallum to @jarkkojs:
 * DON'T resurrect the code from the `sgx` crate in the `sgx` crate. Move that code to the `enarx` crate for now.

# Acceptance Criteria

* [x] Remove https://github.com/enarx/enarx-shim-sgx and https://github.com/enarx/sgx crates from the Enarx Github project.
* [x] Fix aesmd has an availability issue: https://lore.kernel.org/linux-sgx/YfPYfsnjYXQsY6Jz@iki.fi/T/#t.
  * A cgroup does not fix this because cgroups do not support EPC limits.
  * The only way to pin pages for architectural enclaves is to put aesmd to a VM, as `/dev/sgx_vepc` is based on partitioning.
* [ ] Verify that an enclave is running on a genuine Intel CPU.

**Comment by npmccallum** [comment]
Note that the code in the `sgx` crate probably doesn't belong there (at least yet). It should probably belong in the test for now.

**Comment by jarkkojs** [comment]
What is `getatt()`? Not aware of such syscall.

**Comment by npmccallum** [comment]
@jarkkojs https://github.com/enarx/enarx/wiki/Enarx-syscall:-get_attestation

**Comment by jarkkojs** [comment]
Thanks.

**Comment by jarkkojs** [comment]
This issue is blocked by https://github.com/enarx/enarx/issues/1331

**Comment by jarkkojs** [comment]
All tests succeed, if I revert `55caa95c`
