### ISSUE TITLE
Access to the `EAUG` instruction in the lab kernel

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1214]
We need to be able to add pages to an initialized enclave.

**Comment by npmccallum** [comment]
In particular, we need to add pages to the enclave with maximum RWX permissions. This is because we need to `mmap()` the pages as `rw` first and then move them to `rx`.

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1214?planning-poker) with ZenHub @npmccallum @haraldh @jarkkojs

**Comment by jarkkojs** [comment]
https://gitlab.com/enarx/sgx/-/merge_requests/6

**Comment by jarkkojs** [comment]
It's supported.
