### ISSUE TITLE
Make SNP patches work in `kexec()`

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1221]
We are using the [sev-snp-part2-v6](https://github.com/AMDESE/linux/tree/sev-snp-part2-v6) branch for developing Enarx's SNP support. Attempting to `kexec()` into this kernel currently fails and the system hard-reboots. I have bisected the failure to [this patch](https://github.com/AMDESE/linux/commit/d41c4fab5799749f392529887449a7110674e81e). This patch [hasn't been well received on lkml](https://lkml.org/lkml/2021/8/27/412).

We need to make these patch work under `kexec()`.

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1221?planning-poker) with ZenHub @haraldh @npmccallum

**Comment by haraldh** [comment]
In theory we can just skip this patch, because we are not using it as an enclave kernel.

**Comment by platten** [comment]
Booted in the infrastructure, no longer an issue.
