### ISSUE TITLE
Ensure `getatt()` on KVM returns `ENOSYS`

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1223]

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1223?planning-poker) with ZenHub @haraldh @npmccallum

**Comment by haraldh** [comment]
@npmccallum : Currently it returns `TEE_NONE` on KVM

**Comment by platten** [comment]
This is a non-issue and is documented.

**Comment by haraldh** [comment]
See https://github.com/enarx/enarx/issues/966
