### ISSUE TITLE
Fix `process_control` deprecated types

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1225]
We are apparently using now-deprecated types in the aforementioned crate. We should fix this. See #1176.

**Comment by platten** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Enarx-61d86a4144f52e001a7857d6/issues/enarx/enarx/1225?planning-poker) with ZenHub @haraldh @jarkkojs @npmccallum

**Comment by haraldh** [comment]
Maybe closed by https://github.com/enarx/enarx/pull/1231

**Comment by haraldh** [comment]
@definitelynobody ?
