### ISSUE TITLE
valid pkcs10 encoding

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1236]
https://github.com/RustCrypto/formats/issues/322

This issue can be closed when the above issue is closed. We can either wait for upstream to fix this or we can contribute a fix.

**Comment by bstrie** [comment]
PR submitted at https://github.com/RustCrypto/formats/pull/349.

**Comment by bstrie** [comment]
https://github.com/RustCrypto/formats/pull/349 has been accepted, the next step is to wait for a new release of `der_derive` to be published.

**Comment by npmccallum** [comment]
Merged upstream.
