### ISSUE TITLE
Add support for `sock_accept()` to `wasmtime`

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1244]
Blocked by https://github.com/bytecodealliance/wasmtime/pull/3711

**Comment by haraldh** [comment]
https://github.com/bytecodealliance/wasmtime/pull/3711

**Comment by haraldh** [comment]
Wasmtime tracking issue: https://github.com/bytecodealliance/wasmtime/issues/3730

**Comment by haraldh** [comment]
merged
