### ISSUE TITLE
Add support for `sock_accept()` to `wasi-libc`

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1245]
https://github.com/WebAssembly/wasi-libc

**Comment by Deepansharora27** [comment]
Would like to have a look and work on this

**Comment by rvolosatovs** [comment]
This will be closed by https://github.com/WebAssembly/wasi-libc/pull/282

**Comment by haraldh** [comment]
https://github.com/WebAssembly/wasi-libc/pull/287

**Comment by bstrie** [comment]
Can this be closed?

**Comment by rvolosatovs** [comment]
Yes
