### ISSUE TITLE
[Infrastructure]: 0.2 Release Application Level Tests.

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

# Acceptance Criteria:
- [x] Exercise functionality for echo server using new networking functions
- [x] Run SEV `getatt()` tests()

**Comment by jarkkojs** [comment]
I plan to demo this but do I need to follow this or what is the plan?

**Comment by haraldh** [comment]
@jarkkojs so you want to "[Create a demo of an `axum` "Hello World" server running in wasm32-wasi](https://github.com/enarx/enarx/issues/1246)" ??

**Comment by haraldh** [comment]
> @jarkkojs so you want to "[Create a demo of an `axum` "Hello World" server running in wasm32-wasi](https://github.com/enarx/enarx/issues/1246)" ??

@jarkkojs  Sorry, didn't see the SGX attestation on the list.
