### ISSUE TITLE
[Tracking]: Pursue stabilization for Rust RFC 2972: "Constrained Naked Functions"

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In service of getting off of the nightly Rust toolchain and onto the stable one, we need upstream Rust to finish stabilizing some of the necessary features that we rely on. This issue tracks the stabilization of one such feature, constrained naked functions: https://github.com/rust-lang/rust/issues/90957

### Acceptance Criteria

This issue can be closed when https://github.com/rust-lang/rust/issues/90957 is closed.

**Comment by dpal** [comment]
We are not going to continue this effort due to the existing alternative solution.
