### ISSUE TITLE
[Bug]: Using direct feature flag in the source code considered harmful

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Consider a rustc feature flag, any of them, so we can just call it `a_feature`.

The problem statement is that rustc does not currently support the following conditions:

- Enable default features.
- Disable a single feature flag.

If you need to meet up these conditions, you might end up incredibly complicated hacks, e.g.

https://github.com/rust-osdev/x86_64/issues/337

### Expected Behaviour

Being able to disable feature flag and otherwise keep rustc features intact.

### Environment Information

-

### Steps To Reproduce

-

**Comment by jarkkojs** [comment]
My proposal is this:

- For any flag `a_feature`, introduce `enarx_a_feature`.
- Use `enarx_a_feature` in the place of `a_feature`.

**Comment by platten** [comment]
Working as intended.
