### ISSUE TITLE
[Bug]: `clock_gettime` integration test fails on debug

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

```---- clock_gettime stdout ----
thread 'clock_gettime' panicked at 'assertion failed: sec < MAX_SEC', tests/integration_tests.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    clock_gettime
```

### Expected Behaviour

Test pass.

### Environment Information

CI, especially on sev test system on debug

**Comment by haraldh** [comment]
Make a PR to change the test:
1. get time `before_test`
2. get test result `test_time`
3. get time `after_test`

assert that `before_test` < `test_time` < `after_test`

**Comment by haraldh** [comment]
Huh? why is this closed?
