### ISSUE TITLE
[Feature]: Can enarx support sgx driver like isgx?

### ISSUE THREAD

**Issue by rwwwwww21** [enarx/enarx#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'd like to try enarx in my own computer. But unfortunately, my computer cannot support to install `sgx_enclave` driver. Could enarx support `isgx` driver?

I tried to modify `sgx_enclave` to `isgx`, but got error: Invalid argument (os error 22).

**Comment by platten** [comment]
isgx is an out of tree kernel module and as we are focusing on a good upstream experience and prioritizing that at this time.
