### ISSUE TITLE
[Feature]: Setup git precommit hooks

### ISSUE THREAD

**Issue by definitelynobody** [enarx/enarx#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be helpful to create a precommit hook to run formatting and linting checks before you commit.
If you want to ignore the precommit when you commit something you can just pass `-n` and it will be skipped so it's not too invasive.

### Acceptance Criteria

When commits are made a git precommit hook will run which will run various read-only checks.

### Suggestions for a technical implementation

I've used https://crates.io/crates/rusty-hook in the past for this.

.rusty-hook.toml

```
[hooks]
pre-commit = "cargo fmt -- --check && cargo clippy [ARGS HERE] && ..."
```

Add this to any Cargo.toml

```
[dev-dependencies]
rusty-hook = "^0.11.2"
```

We could run clippy a bunch of times to match what the pipeline does? (I use https://github.com/casey/just at home and run a lot of precommit hooks with `just precommit`, maybe we could consider that in the future or something similar)

**Comment by platten** [comment]
Perhaps it would make sense to use a pre-push hook.

**Comment by definitelynobody** [comment]
I will create a script in the root of the project to allow the user to opt-in to a push hook.

**Comment by rvolosatovs** [comment]
@definitelynobody is this now documented in the wiki?

**Comment by definitelynobody** [comment]
Not yet but I'll make another pull request for this @rvolosatovs
