### ISSUE TITLE
AMD SEV demo: provide details on how to reproduce

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#129]
Provide requirements and steps necessary to reproduce the AMD SEV [demo](https://github.com/enarx/enarx/wiki/Demo-Video).

**Comment by connorkuehl** [comment]
Should the instructions live in the [wiki page that contains the videos](https://github.com/enarx/enarx/wiki/Demo-Video)? Or should I open a pull request against [the demo repo](https://github.com/enarx/demo/tree/master/amd-sev)?.

**Comment by npmccallum** [comment]
@connorkuehl Don't care. Just make it good.

**Comment by axelsimon** [comment]
My initial understanding (and because of that, current preference) is to have the instructions under the video.
It also makes sense that the demo repo contains just the code you need and all our documentation live in enarx/enarx/wiki.

However, it probably makes sense to have a short readme for the demo reop, telling people what it is and where to go to make it work (aforementioned [wiki page](https://github.com/enarx/enarx/wiki/Demo-Video)). Does that sound good, @connorkuehl?

**Comment by connorkuehl** [comment]
> However, it probably makes sense to have a short readme for the demo reop, telling people what it is and where to go to make it work (aforementioned wiki page). Does that sound good, @connorkuehl?

It does! I'll update my work with a v2 to propose these changes against the wiki and have the README in the demo point to it accordingly.
