### ISSUE TITLE
fuzz pkcs10 crate

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1303]
The upstream pkcs10 crate could use fuzzing. The x509 crate too.

**Comment by bstrie** [comment]
PR for fuzzing pkcs10 is up at https://github.com/RustCrypto/formats/pull/446 . However, we will need to actually fix any panics found via fuzzing before the PR can land. I'll be working on that next.

**Comment by bstrie** [comment]
This is complete.
