### ISSUE TITLE
[Bug]: Document xchg use.

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Looks like a `nop`.

### Expected Behaviour

Add documentation explaining that why `ebx` cannot be consumed. 

### Environment Information

-

### Steps To Reproduce

-

**Comment by jarkkojs** [comment]
So, the basic idea with this is to document the reasons why `rustc` does not allow the use `rbx` freely in an inline assembly statemnt, as reported by @npmccallum. It's true that`rbx` is in the SystemV ABI a so called callee saved registers, but at least in GCC there's a concept of clobbering built-in to equivalent statement.

**Comment by haraldh** [comment]
https://doc.rust-lang.org/unstable-book/library-features/asm.html#register-names

> This is used internally by LLVM as a "base pointer" for functions with complex stack frames.

https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/asm/x86.rs#L163

**Comment by jarkkojs** [comment]
> https://doc.rust-lang.org/unstable-book/library-features/asm.html#register-names
> 
> > This is used internally by LLVM as a "base pointer" for functions with complex stack frames.
> 
> https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/asm/x86.rs#L163

Got it but in more general sense it is already dictated by the calling convention that it needs to be saved by caller (you're right what you're saying about the stack pointer tho). It's one of the callee saved register (for completeness, I presume you obviously know this).

This was not intuitive because in GCC inline assembly all registered are assumed by preserved, so I would add just:

```
// In Rust inline assembly rbx is not preserved by the compiler, even when part of the input list.
```

What u think?
