### ISSUE TITLE
[Feature]: Document the guidelines for commit messages

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Document motivation behind writing commit messages.
- Document an appropriate structure for a commit message.
- Document the use of widely known tags such as SOB in a commit message.
- Document guidelines for the content of a commit message.
- Document the use Github tags in a commit message.

### Acceptance Criteria

The team agrees with the guidelines.

**Comment by jarkkojs** [comment]
This should go off-sprint but we need to have this (eventually).

**Comment by npmccallum** [comment]
Maybe we should enable this: https://github.com/marketplace/actions/opinionated-commit-message

**Comment by jarkkojs** [comment]
> Maybe we should enable this: https://github.com/marketplace/actions/opinionated-commit-message

I think this could be interesting. I'm not emotionally attached the way we do thing in kernel.

**Comment by haraldh** [comment]
I personally would like to see commits following: https://www.conventionalcommits.org/en/v1.0.0/
A couple of tools exist for this to autogenerate a Changelog or Release Notes (e.g. [clog](https://github.com/clog-tool/clog-cli)).

Of course the [dracut](https://github.com/dracutdevs/dracut/) project uses this and I had good experiences with it.
It uses https://github.com/dracutdevs/commisery-action as a lint gh action, which is a modified version of https://github.com/KevinDeJong-TomTom/commisery-action

It helped me to create release notes like this: https://github.com/dracutdevs/dracut/releases/tag/054

**Comment by moksh-pathak** [comment]
Hey! can I take up this issue?

**Comment by jarkkojs** [comment]
> I personally would like to see commits following: https://www.conventionalcommits.org/en/v1.0.0/ A couple of tools exist for this to autogenerate a Changelog or Release Notes (e.g. [clog](https://github.com/clog-tool/clog-cli)).
> 
> Of course the [dracut](https://github.com/dracutdevs/dracut/) project uses this and I had good experiences with it. It uses https://github.com/dracutdevs/commisery-action as a lint gh action, which is a modified version of https://github.com/KevinDeJong-TomTom/commisery-action
> 
> It helped me to create release notes like this: https://github.com/dracutdevs/dracut/releases/tag/054

I'm absolutely fine with this. As long as things get more formalized and get a better information (e.g. for bisection), it's good enough for me. Also, when I clone **any** open source project, the first thing I look up is the commit log. Even before I look into documentation. It's best place to study how things work, when done properly.

**Comment by jarkkojs** [comment]
> I personally would like to see commits following: https://www.conventionalcommits.org/en/v1.0.0/ A couple of tools exist for this to autogenerate a Changelog or Release Notes (e.g. [clog](https://github.com/clog-tool/clog-cli)).
> 
> Of course the [dracut](https://github.com/dracutdevs/dracut/) project uses this and I had good experiences with it. It uses https://github.com/dracutdevs/commisery-action as a lint gh action, which is a modified version of https://github.com/KevinDeJong-TomTom/commisery-action
> 
> It helped me to create release notes like this: https://github.com/dracutdevs/dracut/releases/tag/054

I'm absolutely fine with this. As long as things get more formalized and get a better information (e.g. for bisection), it's good enough for me. Also, when I clone **any** open source project, the first thing I look up is the commit log. Even before I look into documentation. It's best place to study how things work, when done properly.

**Comment by platten** [comment]
I think adopting the conventional commits convention and putting checks in place to abide by that. I'll sketch together a plan on how to document/implement/enforce this.

@haraldh Thank you for posting the links.

**Comment by bstrie** [comment]
Harald has a document here that we can repurpose: https://github.com/dracutdevs/dracut/blob/master/docs/HACKING.md#commit-messages

**Comment by dpal** [comment]
So this discussion has died. Let us decide what to do with it.
Current commit messages are defined in the guide: https://enarx.dev/docs/Contributing/PRs#commit-messages
Are they not sufficient? Is it critical to fix it any time soon? Can we close it and open when we actually see a need to change it?
