### ISSUE TITLE
[Dependency]: upgrade from structopt to clap 3

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1346]
As of the clap 3 release, structopt has been effectively upstreamed into clap. From the structopt readme:

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added. Bugs will be fixed, and documentation improvements will be accepted.

Consider removing our dependency on structopt and replacing it with a dependency on clap 3.

clap's migration guide: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating

**Comment by moksh-pathak** [comment]
May I take up this issue?

**Comment by bstrie** [comment]
@moksh-pathak You may. I recommend reading the migration guide linked above, as well as the documentation for clap in order to understand what it does and how it works.

**Comment by bstrie** [comment]
@moksh-pathak my apologies, but this issue turned out to be an unforeseen blocker for another important issue so I've gone ahead and implemented this.
