### ISSUE TITLE
[Bug]: Most recent version fails to compile on release and debug for rust versions 1.60.0 and older

### ISSUE THREAD

**Issue by divinusdracodominus** [enarx/enarx#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

several dependencies require asm! which is now marked as an unstable feature and as such these dependencies fail to compile

### Expected Behaviour

ideally newer versions of these dependencies should be pulled in that allow this unstable feature 

### Environment Information

NixOS 21.11 porcupine running rustc version 1.60.0 (also tried with versions 1.57.0, and 1.52.0) using nightly-x86_64-unknown-linux-gnu

### Steps To Reproduce

as per BUILD.md

git clone https://github.com/enarx/enarx
cd enarx
nix-shell
cargo build

**Comment by rvolosatovs** [comment]
This should be fixed by https://github.com/enarx/enarx/pull/1356
@divinusdracodominus could you confirm?
