### ISSUE TITLE
Add GP faults to errcd in sgx-types/src/ssa.rs

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#135]
It seems reasonable to add general protection faults to the `errcd`, as in the SGX documentation an `errcd` could refer to a page fault or a general protection fault. Currently, ours refers only to page faults with the `PageFault` struct.

**Comment by npmccallum** [comment]
How do we discriminate between the types in the resulting union? We should wrap that with a safe interface that interprets it correctly.

**Comment by lkatalin** [comment]
I'm planning to create a `Gpf` struct (maybe non-specific for now with just one field) and then create a union type that is either the `Gpf` or `PageFault` struct, and have `errcd` be of the type of that union. Does that seem like a good way to do it?

**Comment by lkatalin** [comment]
I stopped over-engineering it because none of the Rust abstractions were working to abstract over these two types of structs, so I changed `PageFault` to `Fault` and added a case for the GP fault in there as a new `const`. If this isn't a good solution, I can keep trying.

**Comment by npmccallum** [comment]
@lkatalin Why doesn't a union work?

**Comment by lkatalin** [comment]
@npmccallum I haven't yet been able to find a reasonable way to implement `Debug` for a union, but am still looking.

**Comment by npmccallum** [comment]
@lkatalin We'd probably have to implement it at a higher level. What are the possible values for `errcd`? And how do you tell which value type it contains? Those are the two questions we need to answer.

**Comment by lkatalin** [comment]
@npmccallum Updated #146: Apparently I can wrap the structs in variants and create an `enum` that way. It specifies the possible types of faults for `errcd` through the enum. We could tell which type it is through an `if let` or `match` statement when the fault occurs, and/or maybe add some formatting info for debugging (now that it's an `enum`, hopefully that would work). Thoughts on this solution?

**Comment by lkatalin** [comment]
@npmccallum Oops, you already commented on it. Very fast! Sorry to ping you.
