### ISSUE TITLE
Ensure all files have up-to-date Apache license headers

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#136]
With the new year and all the new project files that come with it, we should ensure everything contains proper license headers.

**Comment by mbestavros** [comment]
A quick tip for whoever takes this: I found and used https://github.com/google/addlicense the last time we needed to do this. Very handy!

**Comment by npmccallum** [comment]
I think we should use SPDX IDs instead: https://spdx.org/ids-how

This de-clutters the top of our files. It also enables easier automation.

For this issue to be complete we need to:
- [ ] Write a test that demands an Apache 2.0 `LICENSE` file in each crate
- [ ] Write a test that demands an SPDX ID in the first line of every `.rs` file
- [ ] Replace all existing license headers with its corresponding SPDX ID
