### ISSUE TITLE
[Infrastructure]: Automate Rust toolchain updates

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Provide scheduled task to check if latest rust nightly build breaks enarx build. Preferably generate automatic dependabot-like PR if build succeeds / tests pass.

@rvolosatovs's comment on RocketChat:

> So for the nightly update, we'd literally just need a bot to do sed -i "s/nightly-[[:digit:]]\+-[[:digit:]]\+-[[:digit:]]\+/nightly-$(date +%Y-%m-%d)/" rust-toolchain.toml .github/workflows/*.yml, make a commit and push it to a branch, which we could even manually open a PR from every week fixing any issues that arise

**Comment by rvolosatovs** [comment]
This was never completed, reopening

**Comment by dpal** [comment]
@bstrie @rvolosatovs is this addressed with the latest changes?

**Comment by dpal** [comment]
I should not be an issue in the long term thus closing.
