### ISSUE TITLE
Update enarx/enarx README to better reflect the project

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#137]
The `enarx/enarx` README currently reads "This is a placeholder repository." We do not want this to be the first thing newcomers see when they look at our premiere repo. We should have something better there, even if it isn't an exhaustive description of the project. A link to the wiki would be a good idea.

**Comment by axelsimon** [comment]
The simplest thing is to grab the README from `enarx/enarx.github.io`. I'll do that for a start.
