### ISSUE TITLE
[Infrastructure]: Document contribution process and conventions 

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

# Acceptance Criteria
- Documentation available on enarx.dev
- Cover process around:
  - Creating issues
  - Defining dependencies
  - Linking PRs

**Comment by dpal** [comment]
This seems to be covered in the Contributions guide. Might be a candidate for closing.

**Comment by nickvidal** [comment]
Agreed. Closing the issue.
