### ISSUE TITLE
[Feature]: Use JS to describe which input data & capabilities should be served to a wasm app

### ISSUE THREAD

**Issue by nickvidal** [enarx/enarx#1373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In JavaScript it's really easy to tame and delegate capabilities through object wrappers. Instead of giving a pointer to powerful API's (e.g. a network function, File::open, etc). This allows you to follow the principle of least authority (POLA) by creating a wrapper to tame functionality [1]. For example, you can expose a fetch' function to a wasm blob that wraps the native fetch function but restricts network access to a particular domain (or basically any condition you can express in JS code).
A Secure ECMAScript (SES) implementation such as Moddable's XS [2] hardens JS such that you can safely build those wrapper and expose them to untrusted code. The WebAssembly System Interface (WASI) [3] tries to do the same thing without JS, but this loses some flexibility for the developer.

[1] https://medium.com/agoric/pola-would-have-prevented-the-event-stream-incident-45653ecbda99
[2] https://blog.moddable.com/blog/secureprivate/
[3] https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-capabilities.md

**Comment by dpal** [comment]
@nickvidal It is unclear what the ask is? Is this still relevant?

**Comment by haraldh** [comment]
@nickvidal ?

**Comment by nickvidal** [comment]
I think we can close this
