### ISSUE TITLE
Audit usage of `static mut`

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1405]
`static mut` is almost always suspect, as its semantics are far more subtle than most people realize. In a single-threaded process it's fine, but as soon as multithreading is involved `static mut` is essentially guaranteed to be unsound. Currently AIUI all of the relevant codebases are single-threaded so it's not a risk for now, but if we intend to make e.g. the shim multithreaded then we'll need to look very carefully at all `static mut` usages.

See this Rust issue for more information: https://github.com/rust-lang/rust/issues/53639

**Comment by platten** [comment]
@bstrie to create entry into the styleguide to be allowed in shims and discussed situations.
