### ISSUE TITLE
SGX EDMM Support

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1426]

**Comment by jarkkojs** [comment]
`s/EDDM/EDMM/`. It's an acronym of Enclave Dynamic Memory Management.

**Comment by jarkkojs** [comment]
#1496, #1506, #1531 fully breakdown this issue.

**Comment by jarkkojs** [comment]
@haraldh, @npmccallum, @platten: Could we close this now? We have issues tracking e.g. in-shim page tracking etc. This does not have clear definition of done, and has danger to hang around forever. I think we could say that now the basic EDMM support is fully completed.

**Comment by jarkkojs** [comment]
Can we close this?
