### ISSUE TITLE
feat(sgx): edmm

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

-

### Acceptance Criteria

-

### Suggestions for a technical implementation

-

**Comment by jarkkojs** [comment]
#1432 blocks getting this work done.

**Comment by platten** [comment]
RE: https://lore.kernel.org/linux-sgx/cover.1644274683.git.reinette.chatre@intel.com/T/#t

**Comment by jarkkojs** [comment]
For 16/32 a comment about RX pages: https://lore.kernel.org/linux-sgx/Yh4fGORDaJyVrJQW@iki.fi/
