### ISSUE TITLE
In depth project presentation slides link broken

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#144]
The link on our [wiki page](https://github.com/enarx/enarx/wiki/In-depth-Project-Presentation-(slides)) is [broken](https://github.com/enarx/enarx.github.io/raw/master/docs/enarx_slides_2019-12.pdf). I'm not sure which slide deck we want to put here, or I would try to fix it.

**Comment by axelsimon** [comment]
Thanks for the reminder, i had a commit ready to go but it hadn't been pushed.
It's fixed now!
