### ISSUE TITLE
[Infrastructure]: Provide CycloneDX BOM manifest for Enarx

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Update CI to generate CycloneDX SBOM artifacts and check into repository. These artifacts should be kept in sync with dependencies stored in Cargo.lock files.

SBOM.<xml|json> files can be generated using: https://crates.io/crates/cargo-cyclonedx

**Comment by abhinandanudupa** [comment]
Can you assign me this issue?

**Comment by abhinandanudupa** [comment]
Where should the sbom file be uploaded - in which folder?
