### ISSUE TITLE
[Bug]: SGX `get_attestation` should return the quote size when buffer length is 0

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

SGX `get_attestation` only returns the quote size when `NULL` hash is passed
https://github.com/enarx/enarx/blob/500c0b8feaa267b559227694c469d2b1e3b12388/internal/shim-sgx/src/handler/enarx.rs#L27-L30

### Expected Behaviour

It should return the quote size also when buffer length is 0

### Environment Information

irrelevant

**Comment by jarkkojs** [comment]
So we could cache the quote
