### ISSUE TITLE
Enarx 0.3.0 Launch Materials

### ISSUE THREAD

**Issue by nickvidal** [enarx/enarx#1477]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

For the upcoming Enarx 0.3.0 release, we want to publish some launch materials, including:

- [x] Enarx documentation update
  - [x] WebAssembly Guide
  - [x] Networking Guide (initial)
- [x] GitHub release notes
- [x] Enarx blog post
- [x] Social media updates (Twitter, LinkedIn)

Are we ready for?
- [ ] Hacker News
- [ ] Reddit

**Comment by platten** [comment]
@nickvidal @MikeCamel we should sync on the scope of the launch materials.

**Comment by MikeCamel** [comment]
Is this not 0.4.0?

**Comment by MikeCamel** [comment]
We also need an architectural diagram + process diagram, showing the various pieces and how they interact.

**Comment by platten** [comment]
Our last release was 0.2.1...

**Comment by nickvidal** [comment]
It's time to overhaul our documentation and other materials. I want to incorporate some of the work that has been developed by the Enarx interns/community. I do think we can have a Wasm guide ready for 0.3.0, and we can start documenting Steward/Drawbridge as we approach 0.4.0. Networking + TLS is also something that needs attention, along with attestation. The architectural + process diagrams will be an integral part. All of these would be developed in parallel from 0.3.0 to 0.4.0, onwards to 0.5.0.

**Comment by Deepansharora27** [comment]
> We also need an architectural diagram + process diagram, showing the various pieces and how they interact.

Is this something related to the Attestation Guide ?

**Comment by MikeCamel** [comment]
We need Steward documentation for 0.3.0, as it's part of the release.  Same for networking.

I really think that a diagram would got a long way towards this (and it's something I can contribute to).

**Comment by Deepansharora27** [comment]
> We need Steward documentation for 0.3.0, as it's part of the release. Same for networking.
> 
> I really think that a diagram would got a long way towards this (and it's something I can contribute to).

If I ask specifically about Networking Guide, what do you expect to incorporate as a part of the Diagrams?
