### ISSUE TITLE
feat(sgx): mprotect()

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1479]
The page permission change is two-folded:

- ENCLS[EMODPR] restricts permissions from the outside of the enclave. Enclave cannot do it from from inside because restricting rights requires to have no alive TLB entries. This all is taken care of `SGX_IOC_ENCLAVE_RESTRICT_PERMISSIONS`. Enclave acknowledges pages with ENCLU[EACCEPT] before they can be accessed normally again.
- ENCLU[EMODPE] extends permissions and is executed inside the enclave, which invalidates the TLB entry. This will trigger page-table walk which will succeed, assuming that the permissions are extended.

1. Do mprotect() syscall through sallyport.
2. Do ioctl(SGX_IOC_RESTRICT_PERMISSIONS) with zero permissions through sallport.
3. EACCEPT for the range.
4. Do EMODPE for the range

Note: does not support unmapped ranges.

**Comment by jarkkojs** [comment]
@npmccallum a blocker: ioctl's are inside the backend. What actions should I take:

Options:
- Move ioctls's to SGX crate.
- Make a fixed blob for EMODPR with PROT_NONE. 

I'd actually tend to be aligned to second options. I.e. we can remove the ioctls that I introduced to the back end and use sallyport to do ioctl with the range and PROT_NONE instead.

After that the final step is EACCEPT + EMODPE.
