### ISSUE TITLE
WebAssembly Project Unavailable for New Issues

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#148]
When creating a new issue, I can select which project to put the ticket into. However, the `WebAssembly` project is not in the list. All the other projects are.

**Comment by mbestavros** [comment]
I'm able to add new issues to the WebAssembly project when creating a new one.

By default, Github seems to only surface "recent" projects -- if you haven't interacted with the WebAssembly board yet, it won't surface it by default. However, if you click the "repository" tab in the Project selection dialog, it should become available even if you've never touched it before (that lists all repo projects). Is it still happening even if you do that?

**Comment by npmccallum** [comment]
You're right.
