### ISSUE TITLE
[Infrastructure]: Disable `nix` test

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Per discussion at the Enarx standup on 2022-02-07 we should disable the nix test workflow.

**Comment by rvolosatovs** [comment]
Refs https://github.com/enarx/enarx/pull/1455#issuecomment-1059737637
