### ISSUE TITLE
Improve SGX contributor experience with ability to skip attestation tests

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On laptop you don't want to always keep daemons running, so there should be a way to run cargo test without attestation.

**Comment by bstrie** [comment]
There exists an `#[ignore]` attribute that can be used on tests which will tell the test runner to ignore them unless specifically requested: https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested . We would need to make sure that CI is using `cargo test -- --include-ignored` to get any ignored tests (assuming that CI is testing attestation).

**Comment by jarkkojs** [comment]
@pl

> There exists an `#[ignore]` attribute that can be used on tests which will tell the test runner to ignore them unless specifically requested: https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested . We would need to make sure that CI is using `cargo test -- --include-ignored` to run any ignored tests (assuming that CI is testing attestation).

Can you exit test by telling to the cargo test that this test is actually ignored. It could be based existence of aesmd.socket.

**Comment by bstrie** [comment]
If you want to exit any test marked with `#[test]` based on information that is available at runtime, then you can just check inside the test and return early to skip the rest of the test. It won't show up as ignored in the cargo output, however.

**Comment by jarkkojs** [comment]
> If you want to exit any test marked with `#[test]` based on information that is available at runtime, then you can just check inside the test and return early to skip the rest of the test. It won't show up as ignored in the cargo output, however.

I think I found a working solution.
