### ISSUE TITLE
Test which checks for lints

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#153]
All our crates should have the following lints turned on:

- `#![deny(missing_docs)]`
- `#![deny(clippy:all)]`

We should have a test which confirms this and fails if any required lints are missing.

Note, however, that we *will* allow selective disabling of specific lints on a case by case basis.

**Comment by squidboylan** [comment]
It doesn't look like i can assign this to myself but I'm happy to work on this.

**Comment by squidboylan** [comment]
https://github.com/enarx/enarx/pull/182 Addresses the `#![deny(clippy:all)]` part of this PR, however it doesn't address the `#![deny(missing_docs)]` piece as I don't have enough knowledge to add the missing docs.

**Comment by npmccallum** [comment]
@squidboylan I would consider it acceptable to grandfather in old crates by doing this:

```rust
#![deny(missing_docs)]

// TODO: link to technology debt issue for documentation
#![allow(missing_docs)]
```

There is value in enforcing this lint on all new crates earlier rather than later.
