### ISSUE TITLE
[Bug]: shim-sgx: arch_prctl() does nothing

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Looking at `arch_prctl()` handler:

```rust
            ARCH_SET_FS => self.ssa.gpr.fsbase = addr,
            ARCH_SET_GS => self.ssa.gpr.gsbase = addr,
````

SSA gets overwritten on AEX and the values come from those in TCS. FS can be only changed with WRFSBASE. For GS we should never do nothing special since it is irrelevant for 64-bit.

**Comment by haraldh** [comment]
fixed now, isn't it?

**Comment by haraldh** [comment]
with #1665
