### ISSUE TITLE
New York State Cyber Security Conference - June 2-3, 2020

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#157]
**Info**
2019 link (2020 doesn't seem live): https://its.ny.gov/2019-nyscsc

Received an email w/ CFP SurveyMonkey link; looks like it could be relevant

**Dates**
- CFP closes:    2020-03-02
- Speakers notified: 2020-04-01
- Event:         2020-06-02

**Location**
Empire State Plaza, Albany, New York, USA

**CFP**
URL to the Call for Proposals / Papers:
https://www.surveymonkey.com/r/2020NYSCSCCFP

**Comment by axelsimon** [comment]
Ah ha, just saw this one and came here to add. You beat me to it, thanks @mbestavros :+1:

**Comment by axelsimon** [comment]
Extra info:

> June 2020 marks the 23rd annual New York State Cyber Security Conference (NYSCSC ‘20) and we invite you to participate in this great event. Share your experience and knowledge with this year’s attendees by submitting a presentation and/or training proposal. The 2020 conference will be held on June 2 and 3 with training sessions held on June 4. The event takes place in Albany, New York, and is co-hosted by the New York State Office of Information Technology Services (NYS ITS), the University at Albany’s School of Business, and The NYS Forum, Inc. Last year’s conference drew more than 1,500 attendees.
> 
> AUDIENCE
> Attendees include all government levels, academia, businesses, not-for-profit organizations and citizens.
> 
> PROPOSAL GUIDELINES
> Proposals will be accepted for:
> Individual or team presentations.
> Panel discussions – panel may be organized and submitted as a group by a panel coordinator, or an individual may submit his/her particular viewpoint to become part of a panel.
> Training sessions featuring real world scenarios and advanced techniques.
> Breakout sessions will run 50 minutes, including 10 minutes for Q and A on June 2 and 3.
> Training sessions will be half day (3 hours) or full day (5-6 hours) on June 4.
> Presentation and training selections will be made based upon desired topics, flow of content, educational value and understanding of the content.
> Only product neutral presentations that are cybersecurity related will be considered.

**Comment by lkatalin** [comment]
CFP is here: https://its.ny.gov/2020-nyscsc/presenters
https://www.surveymonkey.com/r/2020NYSCSCCFP

Lily submitted on 2/5/2020 (need to add bio for Mark to the below email address):

If you have further questions, please send an email to cyber.outreach@its.ny.gov.
If you submitted a proposal(s) you will receive an email by April 1st notifying you of our decision.
