### ISSUE TITLE
[EXTERNAL]:  SGX2 / EDMM support in Linux

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1576]

**Comment by jarkkojs** [comment]
* v3: https://lore.kernel.org/linux-sgx/cover.1648847675.git.reinette.chatre@intel.com/T/#t
* Arch Linux packages: https://github.com/jarkkojs/aur-linux-sgx/actions/runs/2094138421
* Gave reviewed-by for https://lore.kernel.org/linux-sgx/cover.1648847675.git.reinette.chatre@intel.com/T/#m80374894660b23d56ca1f1fa74bca99e1057a833.

**Comment by jarkkojs** [comment]
I ended up acking about 80% of the patches.

**Comment by jarkkojs** [comment]
v4 is out looking good.
