### ISSUE TITLE
[Bug]: Rocket.Chat server side is broken for external applications

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Server asks for password in addition to the access token.

### Expected Behaviour

Server can authenticate **only** with the access token.

### Environment Information

-

### Steps To Reproduce

-

**Comment by platten** [comment]
Hi @nickvidal, could you please follow up with @jarkkojs ?

**Comment by jarkkojs** [comment]
I'll provide a transcript on how to configure rocket.chat with bitlbee as soon as I get to it. I think it is something that would be appreciated also other people that they can use their favorite apps to access Enarx chat.

**Comment by jarkkojs** [comment]
https://github.com/ezkrg/docker-bitlbee-libpurple/issues/8

**Comment by jarkkojs** [comment]
Here's one related to access tokens: https://github.com/EionRobb/purple-rocketchat/issues/6

**Comment by jarkkojs** [comment]
```
20:03 <@root> otr: starting background keygen for jarkko|chat.enarx.dev/eionrobb-rocketchat
20:03 <@root> Notice: The accounts above do not have OTR encryption keys associated with them, yet. These keys are now 
              being generated in the background. You will be notified as they are completed. It is not necessary to 
              wait; BitlBee can be used normally during key generation. You may safely ignore this message if you don't 
              know what OTR is. ;)
20:03 <@root> Password accepted, settings and accounts loaded
20:03 <@root> otr keygen for jarkko|chat.enarx.dev/eionrobb-rocketchat complete
20:03 <@root> Trying to get all accounts connected...
20:03 <@root> Enter password for account eionrobb-rocketchat first (use /OPER)
```

Settings:

```
20:04 <@jarkko> account 0 set
20:04 <@root> auto-add-buddy = `false'
20:04 <@root> auto_connect = `true'
20:04 <@root> auto_reconnect = `true'
20:04 <@root> away is empty
20:04 <@root> default-buddy-group = `Rocket.Chat'
20:04 <@root> display_name is empty
20:04 <@root> handle_unknown is empty
20:04 <@root> nick_format is empty
20:04 <@root> nick_source = `handle'
20:04 <@root> password = `********' (hidden)
20:04 <@root> personal_access_token = `<removed for the bug>'
20:04 <@root> personal_access_token_user_id = `<removed for the bug>'
20:04 <@root> server_path = `'
20:04 <@root> tag = `eionrobb-rocketchat'
20:04 <@root> username = `jarkko|chat.enarx.dev'
 [20:04] [@jarkko(+Ris)] [2:localhost/&bitlbee(+Ct)] [Act: 1]                                                          
```
@nickvidal If you're unfamiliar with `bitlbee-purple` you can just as well test run this with `pidgin`. They both use the same backend.

**Comment by nickvidal** [comment]
Thanks, @jarkkojs. I'll have a look!

**Comment by jarkkojs** [comment]
There's an army of technically savvy people who could help a lot with Enarx, but like me, are too grumpy and terminal-oriented that not being able to use IRC will turn them down :-) That's why I think this is important. I just represent this niche in the core team ATM :-)
