### ISSUE TITLE
New York State Cyber Security Conference

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#159]
https://www.surveymonkey.com/r/2020NYSCSCCFP

Deadline: 2020-03-02

**Comment by MikeCamel** [comment]
June 2020 marks the 23rd annual New York State Cyber Security Conference (NYSCSC ‘20) and we invite you to participate in this great event. Share your experience and knowledge with this year’s attendees by submitting a presentation and/or training proposal. The 2020 conference will be held on June 2 and 3 with training sessions held on June 4. The event takes place in Albany, New York, and is co-hosted by the New York State Office of Information Technology Services (NYS ITS), the University at Albany’s School of Business, and The NYS Forum, Inc. Last year’s conference drew more than 1,500 attendees.
 
AUDIENCE
Attendees include all government levels, academia, businesses, not-for-profit organizations and citizens.

PROPOSAL GUIDELINES 
Proposals will be accepted for:
Individual or team presentations.
Panel discussions – panel may be organized and submitted as a group by a panel coordinator, or an individual may submit his/her particular viewpoint to become part of a panel.
Training sessions featuring real world scenarios and advanced techniques. 
Breakout sessions will run 50 minutes, including 10 minutes for Q and A on June 2 and 3.
Training sessions will be half day (3 hours) or full day (5-6 hours) on June 4.
Presentation and training selections will be made based upon desired topics, flow of content, educational value and understanding of the content.
Only product neutral presentations that are cybersecurity related will be considered.

**Comment by axelsimon** [comment]
Duplicate of #157. Do you want to copy your comment to that one?
