### ISSUE TITLE
[Infrastructure]: Have CI gate PRs on binary size

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

We care about the binary size of Enarx, the shims, and wasmldr. But right now binary size regressions are only detected when someone manually inspects the binaries. CI should aid us in detecting size regressions. I'm unclear on the best way to achieve this, but one strategy is the following:

1. For each PR, do `cargo build` on each of the following: enarx, shim-kvm, shim-sev, wasmldr.
2. Then, build all of the above tools without the PR, i.e. using the current main branch.
3. If the new binary size is more than X% larger than its prior version, then cause the CI job to fail.

Deciding the proper size for X% will be interesting. Increasing binary size isn't always a bad thing, and some PRs will be fully expected to increase the binary size, so approvers will be expected to understand when they should override the CI and merge a PR anyway. So let's aim for making X% quite low, but still high enough that it will not trigger on the random minor perturbations that result from the feeding the optimizer slightly different code.

Ideally the job would report the exact percentage increase when it fails. Ideally I'd also like a bot to leave a comment in the PR itself so that people don't have to go digging for this information.

**Comment by npmccallum** [comment]
I think we just need to have a hard limit of 1MiB for shims. When we hit that limit, we kick off a (manual) size-optimization task and target getting below 0.5MiB. Then we adjust these thresholds as necessary.
