### ISSUE TITLE
[Bug]: bccce095 breaks `ENARX_BACKEND=sgx cargo test` when AESM daemon is not running

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

All tests fail.

### Expected Behaviour

The test, which do not use attestation pass.

### Environment Information

XPS-13 2020 model laptop

**Comment by haraldh** [comment]
Just remove `ENARX_BACKEND=sgx` ... the backend is not able to run.. point.

**Comment by haraldh** [comment]
or just:
```
$ sudo touch /var/run/aesmd/aesm.socket
```

**Comment by platten** [comment]
This looks like a non-issue. Let's discuss.
