### ISSUE TITLE
[Bug]: WASM Binary runs in Wasmtime but gives a `Shutdown` error while deploying it in Enarx Keep

### ISSUE THREAD

**Issue by Deepansharora27** [enarx/enarx#1630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

I was trying my hands on the `Wasi-sdk` release for .NET. The issue that I am getting is that the WASM Binary is getting generated successfully but when I am trying to deploy it in an Enarx Keep, it gives me a `Shutdown` Error.

However, that is not the case with `wasmtime`. On `wasmtime` , I am getting no errors and able to see the output. 

### Expected Behaviour

Shouldn't give the shutdown error.

### Environment Information

Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

enarx 0.2.0
```
Version 0.2.0 starting up
Backend: sgx
 ✔ System Info: Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 (none)
 ✗ Driver: /dev/sgx_enclave
 ✔ CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | GenuineIntel
 ✗  SGX Support
 ✗   Version 1
 ✗   Version 2
 ✗   FLC Support
 ✔   Max Size (32-bit): 1 
 ✔   Max Size (64-bit): 1 
 ✔   MiscSelect: (empty)
 ✔   Features: (empty)
 ✔   Xfrm: (empty)
 ✔   EPC Size: 0 
Backend: sev
 ✔ System Info: Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 (none)
 ✗ Driver: /dev/sev
 ✗  SEV-SNP is enabled in host kernel
 ✗  /dev/sev is readable by user
 ✗  /dev/sev is writable by user
 ✔ Driver: /dev/kvm
 ✔  API Version: 12
 ✔ MEMLOCK rlimit allows for: ~12 keeps (soft limit = 67108864 bytes, hard limit = 67108864 bytes)
 ✗ CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | GenuineIntel
 ✗  Microcode support
 ✗  Secure Memory Encryption (SME)
 ✗   Physical address bit reduction
 ✗   C-bit location in page table entry
 ✗  Secure Encrypted Virtualization (SEV)
 ✗   Number of encrypted guests supported simultaneously
 ✗   Minimum ASID value for SEV-enabled, SEV-ES disabled guest
 ✗  Secure Encrypted Virtualization Secure Nested Paging (SEV-SNP)
 ✗  Page Flush MSR available
Backend: kvm
 ✔ System Info: Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 (none)
 ✔ Driver: /dev/kvm
 ✔  API Version: 12
 ✔ CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | GenuineIntel
```

**Comment by platten** [comment]
Hello @Deepansharora27 , I've noticed that you're running enarx 0.2.0 which is outdated. Could you please update to the latest release (0.3.0) and try again? If this problem still is occuring, could you please list all the steps to reproduce it and provide and output? Thanks!

**Comment by rjzak** [comment]
I've had this issue with the latest code trying out the wasm version of Ruby.

**Comment by Deepansharora27** [comment]
I guess there is a minor typo in this command :

`cargo run --features dbg mywasm.wasm`

It gives a error when I provide it the `run` flag. Also there is a space between features and dbg. 

But even when I am trying to execute with this 
It logs out this error that error: Found argument 'mywasm.wasm' which wasn't expected, or isn't valid in this context

**Comment by Deepansharora27** [comment]
Spot on @rjzak Thanks !! I missed that

**Comment by Deepansharora27** [comment]
I am getting the following Exception:
`
EXCEPTION: PAGE FAULT
Accessed Address: VirtAddr(0x10)
Error Code: CAUSED_BY_WRITE | USER_MODE
ExtendedInterruptStackFrameValue { rbp: 5e8, rbx: 3f, r15: 7f344495c130, r14: 7f344495bb40, r13: 5555e3c73bd0, r12: a0160, r11: 46, r10: 1, r9: 5555e3b9ba00, r8: 5555e3c73b90, rax: 5555e3bd3a30, rcx: 0, rdx: 0, rdi: 5f0, rsi: 41, instruction_pointer: VirtAddr(0x7f344426859d), code_segment: 23, cpu_flags: 10002, stack_pointer: VirtAddr(0x7ff0a7a3bf50), stack_segment: 1b }
TRACE:
E 0x000000000182759d
TRACE:
TRACE:
[src/backend/kvm/thread.rs:182] &syscall = Payload {
    num: 231,
    argv: [
        255,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
`

**Comment by Deepansharora27** [comment]
Attaching Screenshot as well for more readability:


![Screenshot from 2022-04-05 22-55-35](https://user-images.githubusercontent.com/43300955/161814815-be2e4395-dfad-4eef-9729-72f6ad1aeedf.png)

**Comment by rjzak** [comment]
Looks like it's the same issue I had, #1637 and #1638. Syscall 25 `mremap()` isn't implemented.

**Comment by Deepansharora27** [comment]
@jarkkojs @rjzak I was just curious how did you figure out by looking at this that Syscall 25 `mremap()` is not implemented

**Comment by rjzak** [comment]
We didn't, @rvolosatovs looked at the trace and already knew that syscall 25 wasn't implemented.

**Comment by rvolosatovs** [comment]
> syscall 25 = -38

is the key - `mremap` was executed, but returned errno `38`, which corresponds to `ENOSYS` - that's what sallyport returns for unimplemented syscalls.
