### ISSUE TITLE
[Bug]: `KVM Shutdown Error` with JS Binary

### ISSUE THREAD

**Issue by Deepansharora27** [enarx/enarx#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

With JS Binary, the same issue prevails as .NET and Ruby. 

Even getting JS Binary to work with `wasmtime` was a bit cumbersome at first, but with `msgpack` dependency, I was finally able to get it working with Wasmtime without any errors. 

I have two points of Concern here. 

1). The default implementation of toolchain that I am using in order to compile my Source code to a WASM Binary expects a `msgpack` input(Converting JSON to msgpack) to be sent through `stdin`. 

Now, in order to get it working on Wasmtime, we have to do:
`json2msgpack -i input.json | wasmtime run index.wasm | msgpack2json` 

We have to provide `input.json` as input to `json2msgpack` and also since it is `messagepack` encoded, we also have to decode it with a tool like `msgpack2json`. 

`json2msgpack` and `msgpack2json` are two utilities which are provided by the `msgpack-tools` dependency.
You can find more info about it here : https://github.com/ludocode/msgpack-tools

Now, if I tweak the command like this to get it working on Enarx  :
`json2msgpack -i input.json | enarx run index.wasm | msgpack2json` 

It reports me this error :
```
Error: KVM error: Shutdown
msgpack2json: parse error: mpack_error_io (2)
```
2).However in the second case, If I just generate my binary using the toolchain and directly run it in Enarx Keep:
`enarx run index.wasm`

It reports me this single Error:
```
Error: KVM error: Shutdown
```
Also, I did a error trace for this and it returned me this exception:
![Screenshot from 2022-04-07 00-14-38](https://user-images.githubusercontent.com/43300955/162046324-b51793b5-d358-47eb-aecf-a38674cd6794.png)

I believe that running it by using `enarx run index.wasm` will not be the feasible way to go with this since the `Javy` toolchain doesn't expects input from us through the normal way(console). Instead, it expects from us a `messagepack` input. 

### Expected Behaviour

Should work in the Keep and not give `Shutdown` Exception

### Environment Information

```
Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

`enarx 0.3.0`

```
✗ Backend: sgx
  ✔ System Info: Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 (none)
  ✗ Driver: /dev/sgx_enclave
  ✔ CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | GenuineIntel
  ✗  SGX Support
  ✗   Version 1
  ✗   Version 2
  ✗   FLC Support
  ✔   Max Size (32-bit): 1 
  ✔   Max Size (64-bit): 1 
  ✔   MiscSelect: (empty)
  ✔   Features: (empty)
  ✔   Xfrm: (empty)
  ✔   EPC Size: 0 
✗ Backend: sev
  ✔ System Info: Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 (none)
  ✗ Driver: /dev/sev
  ✗  SEV-SNP is enabled in host kernel
  ✗  /dev/sev is readable by user
  ✗  /dev/sev is writable by user
  ✔ Driver: /dev/kvm
  ✔  API Version: 12
  ✔ MEMLOCK rlimit allows for: ~12 keeps (soft limit = 67108864 bytes, hard limit = 67108864 bytes)
  ✗ CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | GenuineIntel
  ✗  Microcode support
  ✗  Secure Memory Encryption (SME)
  ✗   Physical address bit reduction
  ✗   C-bit location in page table entry
  ✗  Secure Encrypted Virtualization (SEV)
  ✗   Number of encrypted guests supported simultaneously
  ✗   Minimum ASID value for SEV-enabled, SEV-ES disabled guest
  ✗  Secure Encrypted Virtualization Secure Nested Paging (SEV-SNP)
  ✗  Page Flush MSR available
✔ Backend: kvm
  ✔ System Info: Linux deepanshu-HP-Notebook 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 (none)
  ✔ Driver: /dev/kvm
  ✔  API Version: 12
  ✔ CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | GenuineIntel

```

### Steps To Reproduce

For a more detailed documentation on this, I have already written it and it can be found here :
https://enarx.dev/docs/WebAssembly/JavaScript

**Comment by rjzak** [comment]
Can you provide a longer trace? If this has syscall 25, it might be fixed when the PRs are accepted.

**Comment by Deepansharora27** [comment]
@rjzak Will this work ? 
```
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
syscall 228 …
[src/backend/kvm/thread.rs:198] &_syscall = Payload {
    num: 228,
    argv: [
        1,
        0,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}
syscall 228 = 0
EXCEPTION: PAGE FAULT
Accessed Address: VirtAddr(0x10)
Error Code: CAUSED_BY_WRITE | USER_MODE
ExtendedInterruptStackFrameValue { rbp: 7f01ebfae020, rbx: 34, r15: 34, r14: 7f01ebfae028, r13: 7f01ebfadb40, r12: 5555d04f6a30, r11: b8, r10: 3f, r9: ffffffffffffafe0, r8: 5555d0660af0, rax: 0, rcx: 0, rdx: 5555d0621cd0, rdi: 5020, rsi: 0, instruction_pointer: VirtAddr(0x7f01eb8bae8a), code_segment: 23, cpu_flags: 10087, stack_pointer: VirtAddr(0x7ff009c0c300), stack_segment: 1b }
TRACE:
E 0x0000000001827e8a
TRACE:
TRACE:
[src/backend/kvm/thread.rs:182] &syscall = Payload {
    num: 231,
    argv: [
        255,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}



```

**Comment by Deepansharora27** [comment]
I don't know whether I am right or not, please correct me if I am wrong but I guess it has something to do with syscall 228 since it's occuring redundantly.

**Comment by rjzak** [comment]
PR 1645 added the syscall that was needed for Ruby, so maybe do a `git pull`, `cargo clean`, and `cargo build` to see if the issue is fixed. Otherwise, pipe the output to a file and share via chat.

**Comment by haraldh** [comment]
@Deepansharora27 please give me a link to the wasm file, so I can try to reproduce.

**Comment by haraldh** [comment]
> @haraldh Here is the link to it Harald : https://keybase.pub/deepansharora27/JSBinary.wasm Thanks !!

I don't know what it expects as input,  but:
```
❯ echo 1 2 3 4 5 6 7 | cargo run --release -- run ~/Downloads/JSBinary.wasm  
    Finished release [optimized] target(s) in 0.50s
     Running `target/release/enarx run /home/harald/Downloads/JSBinary.wasm`
Fibonacci Term is  12586269025
�
```

**Comment by haraldh** [comment]
That is with current HEAD f5c9e74bd2ebf01d71ac256e6b59104b10fe0e6b

**Comment by Deepansharora27** [comment]
> > @haraldh Here is the link to it Harald : https://keybase.pub/deepansharora27/JSBinary.wasm Thanks !!
> 
> I don't know what it expects as input, but:
> 
> ```
> ❯ echo 1 2 3 4 5 6 7 | cargo run --release -- run ~/Downloads/JSBinary.wasm  
>     Finished release [optimized] target(s) in 0.50s
>      Running `target/release/enarx run /home/harald/Downloads/JSBinary.wasm`
> Fibonacci Term is  12586269025
> �
> ```

It expects a `messagepack` input to be piped along with it. So normally if we run it on the top of wasmtime we have to execute it like this: 

`json2msgpack -i input.json  | wasmtime run index.wasm | msgpack2json`

The fibonacci function here expects a number as a parameter and that number is supplied through the input.json file by converting it into `messagepack`

**Comment by haraldh** [comment]
> 

 @Deepansharora27 worth a try with a current git version of enarx.

**Comment by Deepansharora27** [comment]
@haraldh It is working now Harald in Enarx Keep as well with : 

`json2msgpack -i input.json | enarx run JSBinary.wasm | msgpack2json`

**Comment by platten** [comment]
This has been resolved.
