### ISSUE TITLE
Implement `clock_getres` syscall

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#1657]
> @jarkkojs Here is the link to it : https://keybase.pub/deepansharora27/wasm_file.wasm

This one needs the `SYS_clock_getres` syscall

_Originally posted by @haraldh in https://github.com/enarx/enarx/issues/1637#issuecomment-1091766992_

Above example:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', /home/harald/.cargo/registry/src/github.com-1ecc6299db9ec823/cap-time-ext-0.24.2/src/monotonic_clock.rs:40:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jarkkojs** [comment]
ok can do

**Comment by haraldh** [comment]
> ok can do

?
