### ISSUE TITLE
Fill in XSave struct in sgx-types/ssa.rs

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#171]
Add details to the XSave struct.

**Comment by lkatalin** [comment]
@npmccallum Do we know that the size of the current `XSave` struct is correct, or should I test for that with `CPUID`?

**Comment by npmccallum** [comment]
The size of `XSave` is variable. But in this case **we** get to define what goes in it. So we probably want the maximum.

**Comment by npmccallum** [comment]
I'm also okay with growing this over time. But we need to have a minimal set first.

The minimum is probably what Jarkko did here: https://github.com/jsakkine-intel/linux-sgx/blob/master/tools/testing/selftests/x86/sgx/encl_bootstrap.S#L83
