### ISSUE TITLE
Document or link to Rust environment setup in How to Contribute

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#173]
The "How to Contribute" wiki page does not currently include any mention of how to set up a Rust environment -- a fairly significant gap given we're a Rust project. :stuck_out_tongue:

We should either document how to set up a Rust environment ourselves or link externally to an appropriate guide. If we can assume users have Rust set up, we can also tell them to install relevant testing packages like `rustfmt` and `cargo audit`.

**Comment by axelsimon** [comment]
Indeed! :smiley: I see that @haraldh added some (basic) information regarding Rust to the README.

I'll start adding it to the wiki, as a start. But that won't be enough to fix this issue, so leaving open for now.
