### ISSUE TITLE
Finish migrating the wiki to the official documentation at enarx.dev

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1742]
Some pages on the wiki have been migrated, but there are still plenty that haven't. It's difficult for developers to keep the documentation in sync if there isn't a single canonical place for the documentation to live, and it's even more confusing for users to figure out where the canonical documentation is and if any documentation they find is up-to-date.

**Comment by bstrie** [comment]
All wiki pages have been migrated and the wiki pages have been updated to point to their canonical locations. The only question now is if and when we want to delete the wiki entirely.

**Comment by nickvidal** [comment]
Since each wiki page has a link to the most up-to-date documentation, I would leave the wiki pages up.

**Comment by dpal** [comment]
@nickvidal @bstrie anything changed since then?

**Comment by nickvidal** [comment]
I think we can close this.
