### ISSUE TITLE
Red Hat Summit 2020 - supplementary content

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#175]
**Info**
Conference / Event URL
https://www.redhat.com/en/summit

**Dates**
- Booth preparation due:    2020-04-20 ?
- Event:         2020-04-27/2020-04-29

**Location**
San Francisco, California, USA

**CFP**
URL to the Call for Proposals / Papers:
N/A

**Comment by MikeCamel** [comment]
Note: although acceptance of the booth is down to Red Hat management, non-RH community members are very welcome to be involved in planning and staffing.  And, of course, visiting!

**Comment by axelsimon** [comment]
Some news: our "Enarx - secured, attested execution on any cloud" demo for the Community Central minitheaters at Red Hat Summit was accepted :)

**Comment by axelsimon** [comment]
Status: Working on updating the slides' format, re-editing the video from summit and then uploading it and the interviews to Youtube.

**Comment by mbestavros** [comment]
All our Summit content is on YouTube, so we consider this closed, per @axelsimon.
