### ISSUE TITLE
CNCF TAG-Runtime discussion/presentation?

### ISSUE THREAD

**Issue by raravena80** [enarx/enarx#1766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello enarx team,

I'm one of the co-chairs of the CNCF TAG-Runtime. I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, a general overview of the project or/and a demo.

Feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by nickvidal** [comment]
Thanks Ricardo. We'll be adding a presentation to the agenda early next year.

**Comment by raravena80** [comment]
Thanks @nickvidal

**Comment by raravena80** [comment]
Hi @nickvidal, checking in on this. It would be great to have you present the project in our CNCF TAG-Runtime meeting. Thx.
