### ISSUE TITLE
[Feature]: feat(sgx): initiate memory mappings from the shim

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It does not really matter all that much whether PTE's contain RWX or something else for the enclave's security's sake, BUT there are some good reasons to make them match anyhow:

* Increases the probability of catching bugs related to corrupted permissions.
* Gives some visibility to the enclave's heap layout, which is a great debugging aid.
* Remove code from the backend that fixes the heap location.

Enclave's security is defined by other set of page permissions contained to a database called Enclave Page Cache Metadata (EPCM), which is fully controlled by the enclave, and not the host.

**Comment by jarkkojs** [comment]
@rvolosatovs Can I get an example how to invoke syscall from shim?

**Comment by rvolosatovs** [comment]
> @rvolosatovs Can I get an example how to invoke syscall from shim?

That's probably a question to @haraldh, but looking through the SGX shim code, https://github.com/enarx/enarx/blob/36f19c242b1684da621c1b6c3384e4e3394b7262/crates/shim-sgx/src/handler/mod.rs#L381-L392 is probably what you're looking for, this executes an "opaque" syscall from userspace (hence it uses the `syscall` method), which is triggered by an invalid opcode https://github.com/enarx/enarx/blob/36f19c242b1684da621c1b6c3384e4e3394b7262/crates/shim-sgx/src/handler/mod.rs#L264

If you want to invoke a syscall directly from the shim, i.e. the syscall you want to execute is known at compile-time, you can use any of the methods on [`Handler` trait](https://docs.rs/sallyport/0.4.0/sallyport/guest/trait.Handler.html)

If you have more than one syscall to execute, you can also use [`execute`](https://docs.rs/sallyport/0.4.0/sallyport/guest/trait.Handler.html#method.execute) like so: https://github.com/enarx/enarx/blob/36f19c242b1684da621c1b6c3384e4e3394b7262/crates/sallyport/tests/integration_tests/syscall.rs#L1571-L1575

**Comment by jarkkojs** [comment]
> > @rvolosatovs Can I get an example how to invoke syscall from shim?
> 
> That's probably a question to @haraldh, but looking through the SGX shim code,
> 
> https://github.com/enarx/enarx/blob/36f19c242b1684da621c1b6c3384e4e3394b7262/crates/shim-sgx/src/handler/mod.rs#L381-L392
> is probably what you're looking for, this executes an "opaque" syscall from userspace (hence it uses the `syscall` method), which is triggered by an invalid opcode
> 
> https://github.com/enarx/enarx/blob/36f19c242b1684da621c1b6c3384e4e3394b7262/crates/shim-sgx/src/handler/mod.rs#L264
> 
> If you want to invoke a syscall directly from the shim, i.e. the syscall you want to execute is known at compile-time, you can use any of the methods on [`Handler` trait](https://docs.rs/sallyport/0.4.0/sallyport/guest/trait.Handler.html)
> 
> If you have more than one syscall to execute, you can also use [`execute`](https://docs.rs/sallyport/0.4.0/sallyport/guest/trait.Handler.html#method.execute) like so:
> 
> https://github.com/enarx/enarx/blob/36f19c242b1684da621c1b6c3384e4e3394b7262/crates/sallyport/tests/integration_tests/syscall.rs#L1571-L1575

Thanks, I'll play with that.

BR, Jarkko

**Comment by jarkkojs** [comment]
I will close this because this a duplicate to #1204. In that issue, I've documented the implementation approach.
