### ISSUE TITLE
Change the Standup Time

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#179]
I b0rked the previous poll (#178). So this is a new poll. @enarx/everyone please vote. Please note that you **CAN** vote for multiple options. However, once you vote for an option, you can't unvote.

Now that @connorkuehl has joined the team and @squidboylan is interested in working on the project and both are on the West Coast, we need to consider a change to the standup time.

[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/07%3A00%20PST%20*%2010%3A00%20EST%20*%2015%3A00%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/07%3A00%20PST%20*%2010%3A00%20EST%20*%2015%3A00%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/07%3A30%20PST%20*%2010%3A30%20EST%20*%2015%3A30%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/07%3A30%20PST%20*%2010%3A30%20EST%20*%2015%3A30%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/08%3A00%20PST%20*%2011%3A00%20EST%20*%2016%3A00%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/08%3A00%20PST%20*%2011%3A00%20EST%20*%2016%3A00%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/08%3A30%20PST%20*%2011%3A30%20EST%20*%2016%3A30%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/08%3A30%20PST%20*%2011%3A30%20EST%20*%2016%3A30%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/09%3A00%20PST%20*%2012%3A00%20EST%20*%2017%3A00%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/09%3A00%20PST%20*%2012%3A00%20EST%20*%2017%3A00%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/09%3A30%20PST%20*%2012%3A30%20EST%20*%2017%3A30%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/09%3A30%20PST%20*%2012%3A30%20EST%20*%2017%3A30%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/10%3A00%20PST%20*%2013%3A00%20EST%20*%2018%3A00%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/10%3A00%20PST%20*%2013%3A00%20EST%20*%2018%3A00%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/10%3A30%20PST%20*%2013%3A30%20EST%20*%2018%3A30%20GMT)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/10%3A30%20PST%20*%2013%3A30%20EST%20*%2018%3A30%20GMT/vote)
[![](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/Variable%20Times)](https://api.gh-polls.com/poll/01DZSNRTRAVM4NGQW6Z7W626VZ/Variable%20Times/vote)

**Comment by connorkuehl** [comment]
Voted! Technically _all_ of these options work for me, however the only two I did not specifically vote for are the 7am PST and 7:30am PST ones. That's only a light preference, and I'm awake before those times regardless, so if we do choose those time slots it's not really a problem.

**Comment by MikeCamel** [comment]
I voted for all bar 1800 & 1830 GMT, but I can do those on some occasions.  My availability is strongly dependent on day of the week & other commitments.  I also think that we should consider either alternating weekly for some days (early/late), alternating entire weeks (early/late) or some mix of the above.

**Comment by lkatalin** [comment]
I voted, although all of these times would work for me.

**Comment by squidboylan** [comment]
I voted for everything except 09:00 PST which conflicts with other things for me

**Comment by mbestavros** [comment]
Voted for 11am EST. Most of these times work for me, though I'd strongly prefer not to have it between 12 and 1 EST (personal preference, though it's also when the weekly WASI/Wasmtime meetings are held)

**Comment by steveeJ** [comment]
I voted. All options work for me so my vote isn't going to help decide. I'd like to second @MikeCamel's suggestion of trying out an alternating schedule.

**Comment by axelsimon** [comment]
I voted. Similarly to Stefan and Mike, most options work for me and i added a vote to explore variable times.

**Comment by npmccallum** [comment]
@enarx/everyone I am closing the poll and choosing `8AM PST / 11AM EST / 4PM GMT` which was the highest voted option. I think there is value in having a consistent time until a need arises for us to capture input from more Eastern time zones. When such occurs, I'm open to variable times. I will update the calendar invitations. @mbestavros Please update the documentation and then close this ticket.

**Comment by mbestavros** [comment]
Documentation updated, closed.
