### ISSUE TITLE
Port sev functionality from ketuvim to enarx/sev

### ISSUE THREAD

**Issue by whitebrandy** [enarx/enarx#180]
There are plans for api common code in ketuvim to be merged with rust-vmm. The sev functionality needs to be moved and ported to the SEV crate in enarx.

**Comment by connorkuehl** [comment]
@npmccallum Regarding the scope of this task: since we don't plan to support migration, the only outstanding SEV commands would be: guest status, debug decrypt, and debug encrypt. Should those be sufficient for closing this issue or would you prefer to have all SEV commands in this crate?

**Comment by connorkuehl** [comment]
I think we can close this. I'll resubmit to triage for consensus.

**Comment by mbestavros** [comment]
Consensus reached; closing.
