### ISSUE TITLE
[Bug]: Documentation needed for Nil backend

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

https://enarx.dev/docs/Installation/Requirements does not list Nil backend.

### Expected Behaviour

Requirements should list Nil backend

### Environment Information

n/a

**Comment by MikeCamel** [comment]
Needs this, I believe: `--no-default-features --features=backend-nil`

Thus: `cargo build --no-default-features --features=backend-nil`

**Comment by platten** [comment]
This should be added to: https://github.com/enarx/enarx/blob/main/docs/Install.md for the upcoming release.

**Comment by MikeCamel** [comment]
This is a BLOCKER for 0.5.0 release.
