### ISSUE TITLE
[Bug]: Need instructions for Raspberry Pi

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

No instructions for Raspberry Pi at https://enarx.dev/docs/Installation/Setup

### Expected Behaviour

Same as for Debian/Ubuntu

### Environment Information

aarch64 kernel

**Comment by jarkkojs** [comment]
So, why this is a bug? Shouldn't this be a feature?

**Comment by MikeCamel** [comment]
Any functionality without documentation is a bug.

**Comment by jarkkojs** [comment]
> Any functionality without documentation is a bug.

OK, makes sense.

**Comment by MikeCamel** [comment]
This is a BLOCKER for 0.5.0 release.
