### ISSUE TITLE
[Feature]: Reorder handler functions alphabetically in the handler of shim-sgx

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I spent a lot of time thinking where to place a new function to `Handler`. Reorder functions alphabetically so that this time is used instead for something productive.

**Comment by jarkkojs** [comment]
> As I mentioned in [#1812 (review)](https://github.com/enarx/enarx/pull/1812#pullrequestreview-960839058), I don't think that sorting everything alphabetically would help organization. How about we add the same comment "sections" like we have in `sallyport` and keep the sorting within these sections?

Thank you, I follow this suggestion.

**Comment by bstrie** [comment]
Yes, I think it makes sense to group things into logical categories (via comments or modules or however you want to do it), but within each category things should be alphabetized.

**Comment by jarkkojs** [comment]
This issue needs to be open up until I've implemented it. It's relevant but not a priority.

**Comment by bstrie** [comment]
I don't mind if people want to do this, but I don't think we need to make it a priority or have an open issue for tracking it. Instead, I would recommend people simply do minor refactorings whenever they have reason to touch a given file. Closing.
