### ISSUE TITLE
[Infrastructure]: "Nil" issue Label

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#1837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

There are labels for SGX, KVM, SEV, etc., but none existing for Nil.  We should add this for tracking and ease of management.

**Comment by jarkkojs** [comment]
I created a label for nil.

**Comment by jarkkojs** [comment]
I guess this can be closed now?
