### ISSUE TITLE
Check size of GPR struct (Intel docs ambiguous)

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#184]
The [docs](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3d-part-4-manual.pdf) are ambiguous about whether this size is 176 or 184.

Table 38-7 indicates 176 bytes, but Table 38-8 indicates 184 bytes. Currently we are using 184 bytes because this matches with the specific layout in 38-8.

**Comment by platten** [comment]
The correct size is 184 bytes, we currently test for this in the SGX crate.
