### ISSUE TITLE
Determine names for new `enarx run` commands

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1848]
We decided that we would like to allow users to operate in two separate modes, one where they're deploying code from a Drawbridge instance and another where they're running code locally. We would like to have separate Enarx subcommands for each mode, to make it maximally clear which is being used. We need to determine what these names should be, however.

Ideas for remote deployment command:
* `enarx deploy`

Ideas for local development command:
* `enarx test`
* `enarx debug`
* `enarx run-local`

**Comment by rjzak** [comment]
I vote something short and concise, like `enarx test` or `enarx run`. Both imply (in my mind) local testing, and "deploy" sounds more serious and implies doing real work.

**Comment by haraldh** [comment]
So, the goal for local development should be, that I can run it like this (without any wasmtime installation) and have a full development experience:

```rust
fn main() {
    println!("Hello, world!!!");
}

#[test]
fn test_hello_1() {
    println!("Hello Test 1 compiled to wasm in the TEE!!!");
}

#[test]
fn test_hello_2() {
    println!("Hello Test 2 compiled to wasm in the TEE!!!");
}
```

```console
❯ CARGO_TARGET_WASM32_WASI_RUNNER="enarx run"  cargo test --target wasm32-wasi 
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests (target/wasm32-wasi/debug/deps/hello_world-e0c6ac14626afb4f.wasm)

running 2 tests
test test_hello_1 ... ok
test test_hello_2 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

And for testing we could even allow passing arguments, which then allows arguments to the test harness like this:



```console
❯ CARGO_TARGET_WASM32_WASI_RUNNER="enarx run"  cargo test --target wasm32-wasi  -- --show-output
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests (target/wasm32-wasi/debug/deps/hello_world-e0c6ac14626afb4f.wasm)

running 2 tests
test test_hello_1 ... ok
test test_hello_2 ... ok

successes:

---- test_hello_1 stdout ----
Hello Test 1 compiled to wasm in the TEE!!!

---- test_hello_2 stdout ----
Hello Test 2 compiled to wasm in the TEE!!!


successes:
    test_hello_1
    test_hello_2

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

which currently looks like this:

```console
❯ CARGO_TARGET_WASM32_WASI_RUNNER="enarx run"  cargo test --target wasm32-wasi  -- --show-output
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests (target/wasm32-wasi/debug/deps/hello_world-e0c6ac14626afb4f.wasm)
error: Found argument '--show-output' which wasn't expected, or isn't valid in this context
```

**Comment by haraldh** [comment]
So, for my part I like `enarx run` or `enarx run-local` and/or `enarx test` or `enarx test-local` (for the testing part with argument passing).... but naming is hard, and I don't really care, except for backwards compatibility...

**Comment by nickvidal** [comment]
I've given some thoughts to this. Is there a case where people will want to deploy applications using Enarx, but without TEEs/attestation? We give them the opportunity to use Enarx now, and let them take full advantage of CC at a later point, or for some sensitive workloads? In other words, we create a smooth path towards CC, until it's generally available across SCP.

For that reason, I would avoid using `enarx run-local` or `enarx test`.

**Comment by nickvidal** [comment]
Not _encourage_, but as an option.

> enarx deploy can deploy the "package" and the idea is that we'll allow KVM backend behind a flag (e.g. --insecure)

That's perfect.

**Comment by rjzak** [comment]
I agree with Harald's comment above, Enarx should be runnable with `cargo test`. It would be great to see Enarx be a part of the Wasm development process.

**Comment by bstrie** [comment]
We could also distribute a `cargo-enarx` tool that hooks into Cargo and is invoked via `cargo enarx test`.

**Comment by bstrie** [comment]
I think we've decided that we should have single command for this, where each mode is differentiated by flags. Closing.
