### ISSUE TITLE
[Feature]: Refactor/reorganize CLI

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#1856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CLI implementation could benefit from some refactoring, functionality is scattered around and it's different to navigate and extend.
We should try to simplify this and keep related functionality close, e.g. `run` command options should be defined in the same module (file) where the actual `run` implementation lives

**Comment by bstrie** [comment]
This is done.
