### ISSUE TITLE
[Feature]: Default to a Drawbridge slug in `enarx deploy`

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently only URLs are supported. We should assume default Drawbridge instance slugs, such that users could simply do:
```
enarx deploy myuser/myrepo:1.0.2
```

Refs #1852 , but not necessarily blocked by it

### Suggestions for a technical implementation

Once we have #1852, on-the-fly convert the slug into a drawbridge URL

**Comment by bstrie** [comment]
TODO: define slug, including `@#` syntax.

**Comment by rvolosatovs** [comment]
This is done already
