### ISSUE TITLE
[Feature]: Initialize the buffer capacity using `Content-Length` header

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#1859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When fetching objects, especially large, initialize the buffer using value in `Content-Length` header, if specified. Note, that we should probably have some hard limit on this to prevent a malicious party from sending a very high number to attempt to case an OOM.
Currently only relevant for `exec-wasmtime`

**Comment by bstrie** [comment]
TODO: block on encrypted filesystem support, then stream file directly to disk.

**Comment by rvolosatovs** [comment]
Done
