### ISSUE TITLE
[Infrastructure]: Unable to attest an SGX keep on babbage

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Attempting to run an enarx keep on babbage results in an attestation failure. It fails at this line:
https://github.com/profianinc/steward/blob/main/src/ext/sgx/quote/qe/cert.rs#L30

I think this is caused by something in the `aesmd`. @haraldh ?

**Comment by haraldh** [comment]
most probably pccs is not running

**Comment by haraldh** [comment]
because we did not automate the  aesmd with pics, because of API key

**Comment by npmccallum** [comment]
@haraldh We need a way to keep this up. It impacted a demo yesterday.

**Comment by haraldh** [comment]
@npmccallum see 
https://gitlab.com/enarx/aesmd/-/merge_requests/7
and
https://gitlab.com/haraldh/pccs

There are docker images already available.

**Comment by haraldh** [comment]
basically:
```
# systemctl stop aesmd.service
# su - aesmd
$ podman run -it --rm -v /dev/log:/dev/log --secret PCCS_APIKEY,type=mount --net host registry.gitlab.com/haraldh/pccs &
$ podman run --net host --rm -it -v /dev/log:/dev/log -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision -v /var/run/aesmd:/var/run/aesmd registry.gitlab.com/haraldh/aesmd:latest &
```

**Comment by npmccallum** [comment]
@haraldh

1. Can we move the PCCS crate into the gitlab org?
2. Can we ensure that everything except the manual secret setup step is in our bootable containers?

**Comment by dpal** [comment]
The issues is addreesed.
