### ISSUE TITLE
[Feature]: override TLS `poll_oneof`

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#1882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Current `poll` implementation on TLS FDs is not correct, since it may report that there is data to be read in cases where the is no *plaintext* data to be read, e.g. if there's ciphertext in the buffer, but no plaintext can be decrypted yet.
cc @npmccallum 

### Suggestions for a technical implementation

We should be able to override the `poll_oneof` snapshot1 trait like we had done before in one of the TLS iterations, where we'd have to maintain a table of TLS FDs and if the FD is TLS, validate if there is any plaintext to be read.

**Comment by haraldh** [comment]
return EAGAIN as a fast fix

**Comment by rvolosatovs** [comment]
This works fine now
