### ISSUE TITLE
[Feature]: Official aarch64 builds

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We should provide official aarch64 builds

### Suggestions for a technical implementation

Adapt `flake.nix` and release workflow from #1881 to cross-compile for aarch64

**Comment by rvolosatovs** [comment]
Assigning myself, because I both have experience with doing this on Github Actions and Nix.

**Comment by rjzak** [comment]
Closing, as the PR was merged and a recent CI run https://github.com/enarx/enarx/actions/runs/3410597301 still works on `aarch64-unknown-linux-musl`, `aarch64-apple-darwin`, and Universal 2.

**Comment by rjzak** [comment]
We may want to re-open this when we support ARMv9's Realms.
