### ISSUE TITLE
CLI API for Drawbridge integration

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#1953]
# Acceptance Criteria:
- [x] Draft user markdown user documentation
- [ ] Develop subcommand
- [ ] Integration / E2E testing

# Proposed API

Adding Drawbridge integration to the CLI will also involve changes to the existing CLI API. Here is a proposed overview of what the final CLI will look like:

```
enarx
├── run [--backend <BACKEND>] [--config <CONFIG>] <PACKAGE>
├── platform
│   ├── info [--format <FORMAT>]
│   ├── sgx
│   │   └── register
│   └── snp
│       ├── info [--file]
│       └── update [--path <PATH>]
├── user
│   ├── info [--format <FORMAT>] <USER_ID>
│   ├── login [--oidc-domain <URL>] [--oidc-client-id <ID>] [--insecure]
│   ├── logout
│   └── register <USER_ID>
├── repo
│   ├── info [--format <FORMAT>] <REPO_ID>
│   ├── register --public|--private <REPO_ID>
│   ├── search [--format] [--host <HOST>] <QUERY>
│   ├── token
│   │   ├── info [--format <FORMAT>] <REPO_ID>
│   │   ├── generate <REPO_ID> <REPO_TOKEN_NAME>
│   │   └── revoke <REPO_ID> <REPO_TOKEN_NAME>
│   └── yank [--undo] <REPO_ID>
├── package
│   ├── info [--format <FORMAT>] <PACKAGE_ID>
│   ├── fetch <PACKAGE_ID>
│   ├── publish <PACKAGE_ID> <FILES>
│   └── yank [--undo] <PACKAGE_ID>
├── tree
│   ├── info [--format <FORMAT>] [--host <HOST>] <DIGEST>
│   ├── fetch [--host <HOST>] <DIGEST>
│   └── digest <FILES>
└── unstable
    └── exec [--backend <BACKEND>] <BINARY>
```

Changes to the existing CLI API:

* `enarx info`, `enarx sgx`, and `enarx snp` are moved into the new `enarx cpu` subcommand, becoming `enarx cpu info`, `enarx cpu sgx`, and `enarx cpu snp`.
* `enarx snp vcek show` becomes `enarx cpu snp info`, and `enarx snp vcek show-file` becomes `enarx cpu snp info --file`.
* `enarx exec` is moved into the new `enarx unstable` subcommand. Like `enarx exec`, `enarx unstable` will be hidden from documentation and the command-line `help` output. This helps to reinforce that this command is unsupported.
* Per Nathaniel's suggestion, `enarx deploy` is merged into `enarx run` in order to better support bootstrapping.

The remaining API surface is dominated by four new subcommands, each with their own subcommands: `enarx user`, `enarx repo`, `enarx package`, and `enarx tree`. Preliminary documentation for using these commands to interact with Drawbridge can be found here: https://gist.github.com/bstrie/c0f169475563aa962ca73be55cfd05ac

**Comment by rjzak** [comment]
I don't know that `enarx run` should become `enarx unstable exec`. I understand that the point is to fetch and run jobs from Drawbridge, so maybe it should be `enarx test`. We don't want developers thinking that Drawbridge is required to test their applications, and "Unstable" implies the command isn't ready to be used and that it will be at some future point (like a work in progress), which it isn't.

Suggestion: `enarx run` would only be available on debug builds of Enarx.

**Comment by bstrie** [comment]
@rjzak `enarx run` is remaining as it is, it's `enarx exec` that is becoming `enarx unstable exec`, and we explicitly don't support users making use of `exec` (it's omitted from the documentation and hidden from the CLI help, and still would be under this plan). Because this command is hidden it doesn't really matter where we put it, but Nathaniel suggested that we might grow more unstable commands in the future so it might make sense to group them under an `unsatble` subcommand.
