### ISSUE TITLE
[Infrastructure]: Create SBOMs which map to dependencies used in specific builds.

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Instead of SBOMS to be generated for a workspace/project, it would be preferable to have SBOMs to be generated for code/dependencies actually consumed during a build.

This is related to: CycloneDX/cyclonedx-rust-cargo#175

**Comment by Rana-KV** [comment]
Hi @platten, I'm interested to pursue this topic and work on SBOM implementation. I would like to work on the Issue if it is not already taken.

**Comment by rjzak** [comment]
I think this is already done. Action: https://github.com/enarx/enarx/blob/main/.github/workflows/sbom_manifest_action.yml

**Comment by rjzak** [comment]
Though it's currently broken, possibly because we're on an outdated Rust version at the moment. https://github.com/enarx/enarx/actions/runs/8383677557/job/22959809769#step:4:1
