### ISSUE TITLE
[Feature]: Extract Enarx.toml handling into separate crate

### ISSUE THREAD

**Issue by platten** [enarx/enarx#2017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be helpful to have Enarx.toml parsing/handling & documentation to be packaged as a sub-crate.

### Acceptance Criteria

- Extracted code
- Published subcrate crate
- Updated documentation
- Updated Cargo.toml to use Enarx.toml subcrate

**Comment by haraldh** [comment]
first version: https://github.com/haraldh/enarx_config

@rvolosatovs @bstrie @npmccallum @rjzak @definitelynobody if you want to have a look, before it gets imported?
