### ISSUE TITLE
Pre-push git hooks depend on undocumented dependencies (clippy)

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#204]
**Description**
I activated the test using the suggested git hook (cf. [wiki](https://github.com/enarx/enarx/wiki/How-to-contribute#on-your-local-machine)) and even though i installed cargo, added the `$HOME/.cargo/bin` path to my `PATH` (which is undocumented) and then `cargo install cargo-audit`, i still have an error when trying to `git push`:
```
error: no such subcommand: `clippy`                                            
```

**Comment by mbestavros** [comment]
Documented how to install Clippy in Rust environment setup on [How to contribute](https://github.com/enarx/enarx/wiki/How-to-contribute).
