### ISSUE TITLE
[Bug]: Issue template is invalid

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#2043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

`enarx info` is asked in "Environment Information", but that command does not exist

### Expected Behaviour

use `enarx platform info`, maybe also mention that it should be run as user, which has permissions to actually interact with SEV/SGX devices

### Environment Information

irrelevant

**Comment by dpal** [comment]
Can we close this now?

**Comment by rvolosatovs** [comment]
Yes!
