### ISSUE TITLE
[Infrastructure]: Point release or an RC1

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#2053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Due to SGX backend being unusable in `0.6.0` in generic SGX setups (https://github.com/enarx/enarx/issues/2050 #2051 ), we need a point release or at least an RC1 as was mentioned a few times already yesterday.

Additionally, `0.6.0` renders SEV setups with insufficient `LimitMEMLOCK` unusable, which requires a hardware reboot (https://github.com/enarx/enarx/pull/2046)

This means that:
- `0.6.0` release is either unusable on generic SGX setups
- `0.6.0` release, when misconfigured, renders user's SEV-SNP machines unusable

Neither of these points are acceptable, so we need to release new point release or at least an RC1 ASAP.

**Comment by bstrie** [comment]
This is done.
