### ISSUE TITLE
[Feature]: Publish Enarx OCI images

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#2064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Our CI already builds OCI images containing Enarx for different platforms, we should publish them.
We probably want to use Docker Hub, but perhaps @npmccallum has different opinion here. We could also publish to several registries.

### Suggestions for a technical implementation

Add credentials to CI and push as part of CI/CD pipeline

**Comment by npmccallum** [comment]
@rvolosatovs Is there a reason not to publish to the github registry?

**Comment by puiterwijk** [comment]
For the record: Docker hub credentials are available in this repo as repository secrets.
