### ISSUE TITLE
Implement correct default for TargetInfo

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#207]
The previous one relied on a reference to an Secs. But Secs fields are always private; so we need to do this a different way.

**Comment by lkatalin** [comment]
I've been looking into how a TARGETINFO gets populated by SGX leaf functions or similar, but after delving into it a while, I'm not able to find this yet. Maybe we don't need our own instantiation of this? I don't see where the `qe3_report_body` gets filled out after it's [zeroed](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/0436284f12f1bd5da7e7a06f6274d36b4c8d39f9/QuoteGeneration/quote_wrapper/quote/qe_logic.cpp#L1223) in Intel's DCAP code and don't see any helpful documentation.

I did find that the `sgx_qe_get_target_info` is a wrapper for `sgx_ql_init_quote`, which is a wrapper for `ECDSA256Quote::init_quote()`, which is a wrapper for `ECDSA256Quote::ecdsa_init_quote`...

**Comment by npmccallum** [comment]
I think this is what you're looking for: https://www.felixcloutier.com/x86/ereport

**Comment by lkatalin** [comment]
`EREPORT` is reading a `TargetInfo` from the address in `rbx`, but I haven't found anything that states how that info is created beforehand. I remember it being something like an enclave calling a `REPORT` for itself, but I can't find this anywhere. Do you think we will need to instantiate it in our code?

**Comment by npmccallum** [comment]
I honestly don't know... Maybe ask Intel?

**Comment by lkatalin** [comment]
I think this is actually not relevant and the issue should be closed. We'll never use a `TargetInfo` that isn't populated by `EREPORT`, so the default values don't matter.
