### ISSUE TITLE
[Feature]: Implement a `sign` cli command

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Use the backend hash() functions and output signed keep signatures for every backend.

Implement the missing hash() functions for the backends.

**Comment by bstrie** [comment]
> output the hashes of the default shim + default exec for every backend

Can you elaborate on why this should be exposed from the CLI? When would it be used?

**Comment by haraldh** [comment]
@bstrie This will be used in the release process:

```
$ enarx unstable hash > enarx-hash.json
$ sign-enarx.sh --private-key mycompanies-secret-signing-key --hashes enarx-hash.json --outfile mycompany-enarx-signature
```

So, that people can use it with:
```
$ enarx deploy --signature mycompany-enarx-signature <PACKAGE>
```

This will start the TEEs with a vendor signature, which also will be included in the attestation report.
Also, if the keep contents was modified manually in the `enarx` executable, the Intel or AMD PSP will refuse to start the keep.

**Comment by bstrie** [comment]
If it's designed to be deliberately unstable then go wild, the whole point of the unstable subcommand is that it's out of my jurisdiction. :P

**Comment by haraldh** [comment]
yeah, unstable, until we decide on an export format.
