### ISSUE TITLE
[Bug]: After SEV-SNP reboot, the first enarx run fails

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

fails with I/O error

### Expected Behaviour

doesn't fail

### Environment Information

recent kernels

### Steps To Reproduce

1. reboot machine
2. try enarx .. fails
3. try enarx .. succeeds

**Comment by jarkkojs** [comment]
This bug still exists. Have noticed for some time. Even after rebasing on top of 5.20.

**Comment by haraldh** [comment]
Fixed with https://github.com/enarx/enarx/pull/2178
