### ISSUE TITLE
[Feature ENARX-18]: VFS API

### ISSUE THREAD

**Issue by platten** [enarx/enarx#2149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Provide underlying VFS API to enable file, networking, and crypto operations within the keep.

### Suggestions for a technical implementation

Expose a virtual FS to the application by either:

- capturing the syscalls in Sallyport
- capturing the calls in WasiCtx, i.e. overriding the implementation

Note, that a virtual FS will be required to support languages relying on a runtime anyway.
The right approach TBD

**Comment by rvolosatovs** [comment]
An API is provided in https://github.com/enarx/vfs already.
I believe it's not fit for purpose - it requires lots of workarounds and duplicate code to actually use it in Enarx, but we do have it.
According to @npmccallum a proper FS interface will be provided by wasmtime at which point we should be able to come up with a proper API

Closing this for now
