### ISSUE TITLE
[Feature]: Benchmarks and Profiling Support

### ISSUE THREAD

**Issue by rjzak** [enarx/enarx#2176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add benchmarking and profiling to Enarx so developers can learn more about their application's performance.

### Acceptance Criteria

Ideas:
* Add a stopwatch to `exec-wasmtime` which shows how long a program ran when it exits, enabled by a flag. This would show the program's runtime without any start-up or attestation time from Enarx.
* Add profiling which can be viewed live from a browser, similar to Go's [net/http/pprof](https://pkg.go.dev/net/http/pprof).
  * Memory profiling
  * CPU profiling
  * Anything else?

### Suggestions for a technical implementation

Checkout:
* https://nnethercote.github.io/perf-book/profiling.html
* https://github.com/flamegraph-rs/flamegraph

**Comment by rvolosatovs** [comment]
@ish-meal is working on this and we now have a flame graph in Enarx!
