### ISSUE TITLE
[Bug]: current main breaks existing workloads

### ISSUE THREAD

**Issue by puiterwijk** [enarx/enarx#2219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

When trying to start the `examples/cryptle-rust:0.20` workload, enarx errors with:
```
Error: failed to fetch package

Caused by:
    0: failed to parse config
    1: invalid type: map, expected option at line 10 column 1
```

### Expected Behaviour

I expect it to start the cryptle workload.

### Environment Information

Enarx main

### Steps To Reproduce

This broke with commit 21e36ab3d1be6cf5029ed90e411f00fb55083743, found by using the following test script in a git rebase run:

```
#!/usr/bin/bash -x
nix build || exit 1
timeout 5s nix run . -- deploy 'examples/cryptle-rust:0.2.0'
OUT=$?
echo "Out: $OUT"
if [ $OUT == 124 ];
then
        exit 0
else
        exit $OUT
fi
```

**Comment by rvolosatovs** [comment]
`Enarx.toml` is being reworked in a backwards-incompatible way, so breakages will happen.
This one was not expected, so thanks for reporting
