### ISSUE TITLE
Determine how to identify local packages for attestation

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#2229]
In the exec layer we want to communicate the workload's unique ID to steward for the purpose of attestation/authorization. In the case of a remote package, we use its drawbridge URL as its unique ID. In the case of a local package, we need to determine what to use in lieu of a URL.

**Comment by bstrie** [comment]
The plan is to pass three URI SANs, containing the following info:
 
* name and version (only present if retrieved from drawbridge)
* cryptographic measurement
* signature

**Comment by dpal** [comment]
@roman to add a reference and close the ticket.

**Comment by rvolosatovs** [comment]
@bstrie see https://docs.rs/drawbridge/0.3.0/drawbridge/types/struct.Tree.html#method.from_path_sync
