### ISSUE TITLE
Create design doc for attestation flow

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#2230]
Attestation is a complex dance of keys and authorities and for the sake of understanding and auditability we should have a document describing the entire flow. Not sure where the document will live, but presumably somewhere on enarx.dev.

**Comment by dpal** [comment]
Nathniel started a document https://hackmd.io/KHyHqYHFTSukTOvMjW9N2Q

**Comment by dpal** [comment]
@rjzak please clean and refine the document especially the cross out areas to make it clear what the cross-outs actually mean. Keep the crossed out things in the doc but show that they were evaluated and removed.

**Comment by dpal** [comment]
Need new documents per technology. These docs should be linked with them.
