### ISSUE TITLE
Consistent terminology regarding "packages" and "deployments"

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#2247]
Currently we are inconsistent with regard to terminology for "the thing that is uploaded to drawbridge and deployed as part of `enarx deploy`". The Enarx CLI currently calls this a "package", some parts of the documentation call this a "deployment", and drawbridge calls this a "tag". We should find consistent terminology and use it in all user-facing contexts, e.g. `enarx package publish` could become `enarx foo publish`. Some pros and cons of each option:

* "package": this is a general and familiar term, which is good for onboarding users but could risk confusion with other things that call themselves "packages", e.g. there may be WASM-related standards that use the term "package" with a subtly different meaning compared to how we use it.
* "deployment": this naturally ties into our existing "deploy" terminology, e.g. `enarx deploy`, but IMO a "deployment" suggests something that has already *been* deployed, e.g. a keep that is currently running, and does not naturally suggest something that "can be deployed" or "is waiting to be deployed". A more intuitive term to capture this distinction might be "deployable", but now we're inventing words. It's also a bit long.
* "tag": currently this is only a user-facing term for the small number of people directly consuming the drawbridge client. It's debatable whether there's all that much benefit to changing it on the drawbridge side, but as far as using it more widely, most users will probably intuitively associate it with git's notion of tags, which is somewhat imprecise for our use case. In addition, using "tag" to refer to the bundled-up code artifact itself seems novel; IMO most users would intuitively expect a "tag" to refer to merely the identifier itself, rather than the entire *thing* that is being identified.
* "workload": in both documentation and marketing we use this term, which I believe was popularized by Kubernetes for a similar concept. This is relatively familiar and descriptive, but a tiny bit long.
* "app": IIRC a few places in the documentation currently use "Enarx app" as a way to distinguish "a wasm file" from "a WASM file with an Enarx.toml". We could expand this definition to mean "anything that can run on Enarx". Unlike "package", which (I think?) might have a specific WASM-related definition, I think "app" is generic, as well as being familiar to users. In addition, it might be good for branding/marketing to have a notion of an "Enarx app"; we may be an open platform (as opposed to a walled garden), but we are still a platform and we expect most code to have to do at least a tiny bit of adaptation and configuration (via Enarx.toml) in order to conform to the platform. Also, it's quite short and easy to type.
* "bundle": this currently doesn't get used anywhere, but if we just want a synonym for "package" that is both familiar to developers and avoids any existing WASM-related jargon then we could do worse than this.

**Comment by dpal** [comment]
We have decided that the following terminology will be used:

- **application** - is the actual software binary that will be deployed without configuration.
- **deployment** - the configuration of one or more applications deployed together

The relationship between a **deployment** and the **application** is hierarchical, i.e., a **deployment** includes one or more **applications**. The signatures will be calculated accordingly, i.e., the **deployment** digest will include the digests of the **applications**.

As a result, the terms "wdig" and "wsig" will be renamed to "ddig" and "dsig" respectively.
The signatures of the application will be "adig" and "asig.
The terminology "wdig" and "wsig" will be retired.

There was a suggestion to keep the **workload** concept to denote a collection of the applications working together. But it still needed to be made clear what the benefit would be.

Separate tickets will be open to implement the changes and clean the code up.

**Comment by dpal** [comment]
@bstrie does this address this ticket in its entirety or do we need to discuss the use of the **tag** and the **package** terminology also?

**Comment by bstrie** [comment]
I'm fine with those definitions. I'll close this.
