### ISSUE TITLE
[Feature]: implement threading for WASI

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2292]
### Description

Implement threading for WASI

### Acceptance Criteria

Implement threading for WASI in 
* https://github.com/enarx/enarx/issues/2294
* https://github.com/enarx/enarx/issues/2293
* rust stdlib

### Tracking issue for end-to-end support

https://github.com/WebAssembly/wasi-threads/issues/10

**Comment by dpal** [comment]
This issue is consolidated under: https://github.com/enarx/enarx/issues/2362
