### ISSUE TITLE
[Feature]: implement threading in wasi-libc

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2293]
### Description

Implement threading in wasi-libc.

### Acceptance Criteria

Most of the `pthread_*` functions implemented and working.

### WIP

https://github.com/haraldh/wasi-libc/tree/threads-tls

* [x] https://github.com/WebAssembly/wasi-libc/pull/342

**Comment by haraldh** [comment]
promising PR for stack and TLS: https://github.com/WebAssembly/wasi-libc/pull/342

**Comment by haraldh** [comment]
possible task:
> over in wasi-libc, get some test infrastructure up and running a subset of the [libc-test thread tests](http://nsz.repo.hu/git/?p=libc-test;a=blob;f=src/functional/pthread_mutex.c;h=1c048aefeec6b9bde7f2f15b3b49e5e304dfad6a;hb=HEAD), or

**Comment by dpal** [comment]
This issue is consolidated under: https://github.com/enarx/enarx/issues/2362
