### ISSUE TITLE
[Feature]: implement threading for wasmtime

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2294]
### Description

Implement threading for wasmtime.

### WIP

Working prototype: https://github.com/haraldh/wasmtime/tree/wasi-threads-working

* [x] https://github.com/bytecodealliance/wasmtime/pull/5255
* [ ] https://github.com/bytecodealliance/wasmtime/issues/5235 figure out how to lock the WASI contexts which should now be measurable with the benchmarks I made but still has the async problems to resolve
* [ ] start figuring out the refactoring to properly share Arc-wrapped WASI contexts between instances (read: threads).

**Comment by dpal** [comment]
Blocked on the upstream roadmap.

**Comment by dpal** [comment]
Harald will setup a call.

**Comment by haraldh** [comment]
Filed https://github.com/bytecodealliance/wasmtime/pull/5255

**Comment by haraldh** [comment]
next would be https://github.com/bytecodealliance/wasmtime/issues/5235

**Comment by dpal** [comment]
This issue is consolidated under: https://github.com/enarx/enarx/issues/2362
