### ISSUE TITLE
Unpin nixify dependency

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#2306]
In #2305 we began pinning our nixify dependency in order to work around a bug: https://github.com/enarx/enarx/pull/2305/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R4 . Once this bug is fixed, the dependency should be unpinned.

**Comment by rvolosatovs** [comment]
The transitive dependency overrides should also be removed as part of this.
