### ISSUE TITLE
Keep track of available hardware and CPU support for TEEs

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#232]
Probably should be reviewed on a 6mo basis.

Maybe it belongs on the wiki.

**Comment by axelsimon** [comment]
This would be a very useful resource, for ourselves and for the more general community.
It should clearly live in the wiki.

On the AMD side, "[What processors support SEV?](https://github.com/AMDESE/AMDSEV/issues/1)" was asked over at the AMDSEV repo, for reference.

**Comment by mbestavros** [comment]
@axelsimon considers this complete for now. Closing.
