### ISSUE TITLE
Remove ManuallyDrop from wasmtime test runner

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2352]
https://github.com/enarx/enarx/blob/19ea426405a79c664806d5804a1a62149f5b8a40/crates/exec-wasmtime/src/lib.rs#L107-L123

There has to be a cleaner solution for this!

Introduced by #2348

**Comment by rvolosatovs** [comment]
Yes, and such solution should probably utilize https://doc.rust-lang.org/std/fs/struct.File.html#impl-AsFd-for-File

**Comment by dpal** [comment]
Resolution: Add the comment to the code, explaining the situation.
