### ISSUE TITLE
[Infrastructure]: Discrepancy in the merge configuration in different Enarx repos

### ISSUE THREAD

**Issue by dpal** [enarx/enarx#2359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

While investigating [.github/#29](https://github.com/enarx/.github/issues/29), I noticed that different "Pull Requests" configurations in different repositories are set differently.

Specifically:

- Allow merge commits 
- Allow squash merging 
- Allow rebase merging 
- Always suggest updating pull request branches 
- Automatically delete head branches 

I do not know whether they should be the same or if there is a specific reason for them to be different.
 I have not checked other configuration parameters. It seems that making the configurations more consistent might help with the behaviors of the repo.

**Comment by dpal** [comment]
The policy should be:
- Allow merge commits - NO
- Allow squash merging - NO
- Allow rebase merging - YES
- Always suggest updating pull request branches - YES
- Automatically delete head branches - YES

**Comment by dpal** [comment]
This will be solved with Terraform.

**Comment by puiterwijk** [comment]
The Terraform repo is created, and I'm validating the repo imports.

**Comment by puiterwijk** [comment]
This has been completed: all repos are currently managed by Terraform.
