### ISSUE TITLE
[Bug]: .NET demos slow on Enarx

### ISSUE THREAD

**Issue by nickvidal** [enarx/enarx#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

The .NET demos are really slow on Enarx. They work fine using the .donet runtime or wasmtime.

### Expected Behaviour

The .NET demos should be running like wasmtime, perhaps with small performance penalty.

### Environment Information

nick@vidal:~$ uname -a
Linux vidal 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

nick@vidal:~$ enarx --version
enarx 0.6.3

nick@vidal:~$ enarx platform info
Enarx version 0.6.3
System Info: Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64
✗ Backend: sgx
  ✗ Driver: /dev/sgx_enclave
  ✔ CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz | GenuineIntel
  ✔  SGX Support
  ✔   Version 1
  ✗   Version 2
  ✗   FLC Support
  ✔   Max Size (32-bit): 2 GiB
  ✔   Max Size (64-bit): 64 GiB
  ✔   MiscSelect: (empty)
  ✔   Features: DEBUG | MODE64BIT | PROVISIONING_KEY | EINIT_KEY
  ✔   Xfrm: X87 | SSE | AVX | YMM | BNDREG | BNDCSR
  ✔   EPC Size: 94 MiB
  ✗ AESM Daemon Socket: /var/run/aesmd/aesm.socket
✗ Backend: sev
  ✗ Driver: /dev/sev
  ✗  SEV-SNP is enabled in host kernel
  ✔ Driver: /dev/kvm
  ✔  API Version: 12
  ✗ CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz | GenuineIntel
  ✗  Microcode support
  ✗  Secure Memory Encryption (SME)
  ✗   Physical address bit reduction
  ✗   C-bit location in page table entry
  ✗  Secure Encrypted Virtualization (SEV)
  ✗   Number of encrypted guests supported simultaneously
  ✗   Minimum ASID value for SEV-enabled, SEV-ES disabled guest
  ✗  Secure Encrypted Virtualization Secure Nested Paging (SEV-SNP)
  ✗  Page Flush MSR available
  ✗ /dev/sev is readable by user
  ✗ /dev/sev is writable by user
  ✔ MEMLOCK rlimit allows for: ~190 keeps (soft limit = 999071744 bytes, hard limit = 999071744 bytes)
  ✗ SEV-SNP VCEK key cache file: No such file or directory (os error 2)

  enarx expects the directory `/var/cache/amd-sev` to exist and be readable

✔ Backend: kvm
  ✔ Driver: /dev/kvm
  ✔  API Version: 12
  ✔ CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz | GenuineIntel
  ✔  CPU supports FSGSBASE instructions
  ✔  CPU supports RDRAND instruction
✔ Backend: nil

### Steps To Reproduce

For the ICUMonitor demo, you can follow the instructions at:

https://github.com/enarx/ICUMonitor

For the Greenhouse Monitor demo, you can follow the instructions above but for the code below:

https://github.com/enarx/GreenhouseMonitor

You may test against the 3 runtimes: dotnet, wasmtime, and enarx.

**Comment by nickvidal** [comment]
@puiterwijk noticed that the .NET demos are using `prot = "tcp"` on `Enarx.toml`, but changing it to prot = "tls"` gives an error:

Fatal: sock_accept returned unexpected status 28. This may mean the host isn't listening for connections. Be sure to pass the --tcplisten parameter

Adding `args = [ "--tcplisten [0.0.0.0:5000](http://0.0.0.0:5000/)"]` on Enarx.toml didn't work either. Still gives out an error.

**Comment by haraldh** [comment]
> Expected Behaviour
> The .NET demos should be running like wasmtime, perhaps with small performance penalty.

Feel free to implement lazy memory mapping via a page fault handler. Thank you!

**Comment by nickvidal** [comment]
> `--tcplisten` is an argument for `wasmtime` not for enarx applications.

**Comment by haraldh** [comment]
I should have added a smiley to my previous comment.

**Comment by dpal** [comment]
Might be related to the issue #2280.

**Comment by dpal** [comment]
@haraldh can we close this issue?

**Comment by haraldh** [comment]
ask @nickvidal

**Comment by nickvidal** [comment]
Locally it seems to be much faster, but when deployed on Try Enarx, it's still slow. Not sure why and no benchmarking yet. Let's keep this open as we evaluate. Thanks

**Comment by dpal** [comment]
OK, as @puiterwijk is debugging this as we speak, I will assign it to him for now.

**Comment by puiterwijk** [comment]
This ended up being caused by the fact that Enarx had blocking network sockets, and got fixed by #2469.

**Comment by nickvidal** [comment]
With lazy mmap (#2406) the nonblocking on TCP (#2469), the .NET applications work really well now.
