### ISSUE TITLE
Rust's libc crate doesn't export MAP_FIXED_NOREPLACE on musl

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#239]
We're building on musl libc now. But the Rust `libc` crate doesn't export `MAP_FIXED_NOREPLACE`. It is probably missing other flags too. We should patch upstream. I'm pretty sure we'll need a bunch of these flags at some point. (I need `MAP_FIXED_NOREPLACE` now...)

**Comment by npmccallum** [comment]
Looks like `MAP_SHARED_VALIDATE` is missing too.

**Comment by npmccallum** [comment]
`MAP_SYNC` too.

**Comment by connorkuehl** [comment]
Tracking this here: https://github.com/rust-lang/libc/pull/1658

**Comment by connorkuehl** [comment]
@npmccallum This has been merged upstream and I believe should be included in the next release on crates.io.

So I think when this PR is gets closed, the package will be updated with the patch: https://github.com/rust-lang/libc/pull/1691
