### ISSUE TITLE
Enable chat app issue/PR integrations

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#242]
[Gitter](https://gitter.im/enarx/community) has some built-in Github integration that we should make use of in a new development-centric channel.

It seems like this needs to be done by a repo admin, so @npmccallum in this case.

**Comment by connorkuehl** [comment]
Enarx no longer uses Gitter.

Should this issue be updated to pertain to Rocket.Chat or shall we close this?

**Comment by mbestavros** [comment]
I'll close this. Rocket.Chat integration has the potential to be a lot deeper, so it probably deserves its own thing.
