### ISSUE TITLE
Need to make the git repo(s) easier to use

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#243]
**Description**
Need to allow smaller groups to have particular capabilities (approve, review, etc.).
Need to have pathways through from enarx.io to help people get involved quicker.

**Comment by axelsimon** [comment]
Regarding finer management of permissions, our current conclusion is that this is not possible directly with Github tooling and will require using a bot as a gatekeeper. @mbestavros, can you confirm this?

Regarding pathways from enarx.io to help people get involved, this is ongoing, but i need to finalise the propositions i had regarding this.

**Comment by mbestavros** [comment]
@axelsimon Yes, I believe that is the current state of affairs.

We now have a good understanding of how to build powerful Github bots (see #360), and it's likely we can address this issue with something similar.

**Comment by mbestavros** [comment]
We're generally handling this with automation, so we'll close this.
