### ISSUE TITLE
[Bug]: repository registration fails

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#2450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

```
$ curl -sL https://github.com/enarx/enarx/releases/download/v0.6.4/enarx-x86_64-unknown-linux-musl > enarx-0.6.4    
$ chmod +x enarx-0.6.4
$ ./enarx-0.6.4 repo register rvolosatovs/chat-client
Error: Failed to register repository

Caused by:
    0: request failed with status code `401`
    1: OpenID Connect credential validation failed: Request failed
```

### Expected Behaviour

Success

### Environment Information

enarx 0.6.4

**Comment by puiterwijk** [comment]
Is this against production drawbridge? Could you retry against staging please?

If it works on staging, that's the result of #2311 and https://github.com/profianinc/drawbridge/pull/312: this means that the new enarx tokens only work on newer drawbridge deployments.
At this moment, prod drawbridge is still using the version of Drawbridge from before that patchset, to make sure it works with Enarx 0.6, and the agreement was made during the standup that the moment we release Enarx 0.7, the new Drawbridge gets published, to work with the new Enarx.

**Comment by rvolosatovs** [comment]
> Is this against production drawbridge? Could you retry against staging please?
> 
> If it works on staging, that's the result of #2311 and https://github.com/profianinc/drawbridge/pull/312: this means that the new enarx tokens only work on newer drawbridge deployments.
> At this moment, prod drawbridge is still using the version of Drawbridge from before that patchset, to make sure it works with Enarx 0.6, and the agreement was made during the standup that the moment we release Enarx 0.7, the new Drawbridge gets published, to work with the new Enarx.

This occurs both on `main` *and* last released version (`0.6.4`) of Enarx.
So Enarx 0.6 is already broken.

I will test with staging. Where can I find the versions running on each environment? ( and what environments are actually available )

**Comment by puiterwijk** [comment]
Just tested it actually, and it just works:
```
$ ./enarx-0.6.4 repo register --credential-helper ./test.sh puiterwijk/testing
Error: Failed to register repository

Caused by:
    0: request failed with status code `400`
    1: invalid HTTP header (authorization)
$ ./enarx-0.6.4 user login --credential-helper ./test.sh
To continue, open the following link in your browser:
	https://auth.profian.com/activate
At the prompt, enter the following one-time code:
	QLMJ-MPTP
Once entered, please wait a few moments for authorization to complete.
Credentials saved locally.
Login successful.
$ ./enarx-0.6.4 repo register --credential-helper ./test.sh puiterwijk/testing
$ 
```

So I wonder, since you didn't get a 400 (i.e. "you have no token"), but you get 401 ("you had a token, but it was invalid"), if your current token has expired (tokens expire after a set amount of time).
Due to the type of token, Enarx has no way to locally check if it's expired, and it also has no code to retry.
So please try removing your current token from your keyring service, re-login, and then retry.

**Comment by puiterwijk** [comment]
This is basically #2048 in disguise.

**Comment by rvolosatovs** [comment]
We really need to address #2048, this is clearly an issue, which anyone really using `enarx` will run into
