### ISSUE TITLE
[Bug]: Cargo test consistently fails on RHEL8 system

### ISSUE THREAD

**Issue by dpal** [enarx/enarx#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

On an RHEL8 system create a local git clone of the enarx repo.
Run: 
`cargo run --release -- platform info`

The project builds and runs providing the expected output, so it seems to work.
However, running
`cargo test`

Produces the following output:
<pre>[dpal@dpal enarx]$ cargo test
<font color="#8AE234"><b>    Finished</b></font> test [unoptimized + debuginfo] target(s) in 0.16s
<font color="#8AE234"><b>     Running</b></font> unittests src/main.rs (target/debug/deps/enarx-16888493525d8dd8)

running 26 tests
test backend::kvm::tests::shim_kvm_binary_size ... <font color="#C4A000">ignored, debug_assertions active</font>
test backend::sev::snp::firmware::linux::test::offsets ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::linux::test::align ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::linux::test::size ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::test::align ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::test::offsets ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::test::size ... <font color="#4E9A06">ok</font>
test backend::nil::test::coverage ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::test::test_tcbversion ... <font color="#4E9A06">ok</font>
test backend::sev::snp::launch::test::align ... <font color="#4E9A06">ok</font>
test backend::sev::snp::launch::test::size ... <font color="#4E9A06">ok</font>
test backend::sev::snp::firmware::test::test_vcek_url ... <font color="#4E9A06">ok</font>
test backend::sev::snp::tests::test_const_id_macro ... <font color="#4E9A06">ok</font>
test backend::sev::snp::launch::test::offsets ... <font color="#4E9A06">ok</font>
test backend::sgx::attestation::tests::request_target_info ... <font color="#C4A000">ignored, CPU does not support SGX2 or attestation not possible</font>
test backend::sgx::tests::shim_sgx_binary_size ... <font color="#C4A000">ignored, debug_assertions active</font>
test backend::sev::snp::vcek::tests::test_invalid_cache_path ... <font color="#4E9A06">ok</font>
test cli::key::sgx::digest::test::test_digest ... <font color="#4E9A06">ok</font>
test exec::test::coverage ... <font color="#4E9A06">ok</font>
test cli::platform::info::test_info ... <font color="#4E9A06">ok</font>
test cli::key::sev::digest::test::test_id_digest ... <font color="#4E9A06">ok</font>
test cli::sign::test::test_sgx_vector ... <font color="#4E9A06">ok</font>
test cli::key::sev::digest::test::test_author_digest ... <font color="#4E9A06">ok</font>
test cli::sign::test::test_sev_vector ... <font color="#4E9A06">ok</font>
test cli::key::sev::sign::test::test_sev_vector ... <font color="#4E9A06">ok</font>
test backend::sev::snp::vcek::tests::test_write ... <font color="#4E9A06">ok</font>

test result: <font color="#4E9A06">ok</font>. 23 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.40s

<font color="#8AE234"><b>     Running</b></font> tests/integration.rs (target/debug/deps/integration-ae5a79ed1c6b081c)

running 35 tests
test exec::futex ... <font color="#C4A000">ignored, Backend does not support SGX</font>
test exec::rust_sev_attestation ... <font color="#C4A000">ignored, Backend does not support SEV-SNP</font>
test exec::rust_sgx_attestation ... <font color="#C4A000">ignored, Backend does not support SGX</font>
test exec::thread ... <font color="#C4A000">ignored, Backend does not support SGX</font>
test exec::thread_channel ... <font color="#C4A000">ignored, Backend does not support SGX</font>
test exec::thread_exit_group ... <font color="#C4A000">ignored, Backend does not support SGX</font>
test exec::thread_many ... <font color="#C4A000">ignored, Backend does not support SGX</font>
test client::test_config_init ... <font color="#4E9A06">ok</font>
test exec::cpuid ... <font color="#CC0000">FAILED</font>
test syscall::get_att ... <font color="#C4A000">ignored, Backend does not support attestation</font>
test syscall::exit_one ... <font color="#CC0000">FAILED</font>
test exec::memory_stress_test ... <font color="#CC0000">FAILED</font>
test exec::memspike ... <font color="#CC0000">FAILED</font>
test syscall::exit_zero ... <font color="#CC0000">FAILED</font>
test syscall::readv ... <font color="#CC0000">FAILED</font>
test syscall::read ... <font color="#CC0000">FAILED</font>
test syscall::tests ... <font color="#CC0000">FAILED</font>
test syscall::read_udp ... <font color="#CC0000">FAILED</font>
test exec::echo ... <font color="#CC0000">FAILED</font>
test exec::unix_echo ... <font color="#CC0000">FAILED</font>
test syscall::write_stdout ... <font color="#CC0000">FAILED</font>
test syscall::write_stderr ... <font color="#CC0000">FAILED</font>
test syscall::write_emsgsize ... <font color="#CC0000">FAILED</font>
test wasm::listen_tcp ... <font color="#CC0000">FAILED</font>
test wasm::listen_tls ... <font color="#CC0000">FAILED</font>
test wasm::connect_tcp ... <font color="#CC0000">FAILED</font>
test wasm::memspike ... <font color="#CC0000">FAILED</font>
test wasm::hello_wasi_snapshot1 ... <font color="#CC0000">FAILED</font>
test wasm::memory_stress_test ... <font color="#CC0000">FAILED</font>
test wasm::echo ... <font color="#CC0000">FAILED</font>
test wasm::wasi_snapshot1 ... <font color="#CC0000">FAILED</font>
test wasm::no_export ... <font color="#CC0000">FAILED</font>
test wasm::return_1 ... <font color="#CC0000">FAILED</font>
test wasm::zerooneone ... <font color="#CC0000">FAILED</font>
test client::full has been running for over 60 seconds
test client::full ... <font color="#4E9A06">ok</font>

failures:

---- exec::cpuid stdout ----
thread &apos;exec::cpuid&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- syscall::exit_one stdout ----
thread &apos;syscall::exit_one&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `1`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- exec::memory_stress_test stdout ----
thread &apos;exec::memory_stress_test&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- exec::memspike stdout ----
thread &apos;exec::memspike&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- syscall::exit_zero stdout ----
thread &apos;syscall::exit_zero&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- syscall::readv stdout ----
thread &apos;syscall::readv&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100]`: Expected contents of stdout output differs&apos;, tests/integration.rs:377:13

---- syscall::read stdout ----
thread &apos;syscall::read&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 10]`: Expected contents of stdout output differs&apos;, tests/integration.rs:377:13

---- syscall::tests stdout ----
thread &apos;syscall::tests&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- syscall::read_udp stdout ----
thread &apos;syscall::read_udp&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `0`,
 right: `65507`: Expected length of stdout output differs&apos;, tests/integration.rs:220:5

---- exec::echo stdout ----
thread &apos;&lt;unnamed&gt;&apos; panicked at &apos;failed to write stdin to child: Os { code: 32, kind: BrokenPipe, message: &quot;Broken pipe&quot; }&apos;, tests/integration.rs:265:18
thread &apos;exec::echo&apos; panicked at &apos;failed to provide input for process: Any { .. }&apos;, tests/integration.rs:282:22

---- exec::unix_echo stdout ----
thread &apos;exec::unix_echo&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- syscall::write_stdout stdout ----
thread &apos;syscall::write_stdout&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 105, 10]`: Expected contents of stdout output differs&apos;, tests/integration.rs:377:13

---- syscall::write_stderr stdout ----
thread &apos;syscall::write_stderr&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 105, 10]`: Expected contents of stderr output differs.&apos;, tests/integration.rs:389:13

---- syscall::write_emsgsize stdout ----
thread &apos;syscall::write_emsgsize&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::listen_tcp stdout ----
waiting for workload to start...
thread &apos;wasm::listen_tcp&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::listen_tls stdout ----
waiting for workload to start...
thread &apos;wasm::listen_tls&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::connect_tcp stdout ----
thread &apos;wasm::connect_tcp&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::memspike stdout ----
thread &apos;wasm::memspike&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::hello_wasi_snapshot1 stdout ----
thread &apos;wasm::hello_wasi_snapshot1&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `[]`,
 right: `[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33, 10]`: Expected contents of stdout output differs&apos;, tests/integration.rs:377:13

---- wasm::memory_stress_test stdout ----
thread &apos;wasm::memory_stress_test&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::echo stdout ----
thread &apos;&lt;unnamed&gt;&apos; panicked at &apos;failed to write stdin to child: Os { code: 32, kind: BrokenPipe, message: &quot;Broken pipe&quot; }&apos;, tests/integration.rs:265:18
thread &apos;wasm::echo&apos; panicked at &apos;failed to provide input for process: Any { .. }&apos;, tests/integration.rs:282:22

---- wasm::wasi_snapshot1 stdout ----
thread &apos;wasm::wasi_snapshot1&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::no_export stdout ----
thread &apos;wasm::no_export&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `1`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::return_1 stdout ----
thread &apos;wasm::return_1&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `255`,
 right: `0`: Expected exit status differs.&apos;, tests/integration.rs:398:5

---- wasm::zerooneone stdout ----
thread &apos;wasm::zerooneone&apos; panicked at &apos;assertion failed: `(left == right)`
  left: `[]`,
 right: `[84, 98, 98, 113, 32, 122, 98, 101, 97, 118, 97, 116, 44, 32, 103, 117, 110, 103, 39, 102, 32, 110, 32, 97, 118, 112, 114, 32, 103, 97, 114, 103, 114, 97, 97, 111, 110, 46, 10, 48, 49, 49, 56, 32, 57, 57, 57, 32, 56, 56, 49, 32, 57, 57, 57, 32, 49, 49, 57, 32, 55, 50, 53, 32, 51, 10]`: Expected contents of stdout output differs&apos;, tests/integration.rs:377:13

failures:
    exec::cpuid
    exec::echo
    exec::memory_stress_test
    exec::memspike
    exec::unix_echo
    syscall::exit_one
    syscall::exit_zero
    syscall::read
    syscall::read_udp
    syscall::readv
    syscall::tests
    syscall::write_emsgsize
    syscall::write_stderr
    syscall::write_stdout
    wasm::connect_tcp
    wasm::echo
    wasm::hello_wasi_snapshot1
    wasm::listen_tcp
    wasm::listen_tls
    wasm::memory_stress_test
    wasm::memspike
    wasm::no_export
    wasm::return_1
    wasm::wasi_snapshot1
    wasm::zerooneone

test result: <font color="#CC0000">FAILED</font>. 2 passed; 25 failed; 8 ignored; 0 measured; 0 filtered out; finished in 60.36s

<font color="#EF2929"><b>error</b></font><b>:</b> test failed, to rerun pass `--test integration`
[dpal@dpal enarx]$ 
</pre>

### Expected Behaviour

`cargo test`  does not generate errors.

@bstrie tried doing tn in parallel on the same code and it worked fine so it might be my environment at fault.

### Environment Information

Red Hat Enterprise Linux release 8.7 (Ootpa)
```
[dpal@dpal enarx]$ rustup -V
rustup 1.25.1 (bb60b1e89 2022-07-12)
[dpal@dpal enarx]$ rustc -V
rustc 1.68.0-nightly (77429957a 2023-01-01)
```

### Steps To Reproduce

As described in the current behavior box.

**Comment by haraldh** [comment]
Try disabling selinux...

```
# setenforce 0
```

Look at the journal output..

Check `/dev/kvm` permissions.

**Comment by bstrie** [comment]
If selinux is capable of causing these sorts of failures, I would hope this is reflected somehow in the output of `enarx platform info`.

**Comment by haraldh** [comment]
Also interesting would be the output of trying to run a wasm payload, like:
```
$ cargo run -- run ./tests/client/data/wasm_example/main.wasm
```

**Comment by haraldh** [comment]
and ultimately:

```
$ cargo run --features dbg -- --log-filter trace run  ./tests/client/data/wasm_example/main.wasm
```

**Comment by haraldh** [comment]
But at first we want:
```
$  cargo run -- platform info
```

**Comment by dpal** [comment]
<pre>
[dpal@dpal enarx]$ cargo run -- platform info
    Finished dev [unoptimized + debuginfo] target(s) in 0.67s
     Running `target/debug/enarx platform info`
Enarx version 0.6.4
System Info: Linux 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64
✗ Backend: sgx
  ✗ Driver: /dev/sgx_enclave
  ✔ CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | GenuineIntel
  ✗  SGX Support
  ✗   Version 1
  ✗   Version 2
  ✗   FLC Support
  ✔   Max Size (32-bit): 1 
  ✔   Max Size (64-bit): 1 
  ✔   MiscSelect: (empty)
  ✔   Features: (empty)
  ✔   Xfrm: (empty)
  ✔   EPC Size: 0 
  ✗ Intel CRL cache
  ✗ AESM Daemon Socket: /var/run/aesmd/aesm.socket

  Run `enarx platform sgx cache-crl` to generate the Intel CRL cache file

✗ Backend: sev
  ✗ Driver: /dev/sev
  ✗  SEV-SNP is enabled in host kernel
  ✔ Driver: /dev/kvm
  ✔  API Version: 12
  ✗ CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | GenuineIntel
  ✗  Microcode support
  ✗  Secure Memory Encryption (SME)
  ✗   Physical address bit reduction
  ✗   C-bit location in page table entry
  ✗  Secure Encrypted Virtualization (SEV)
  ✗   Number of encrypted guests supported simultaneously
  ✗   Minimum ASID value for SEV-enabled, SEV-ES disabled guest
  ✗  Secure Encrypted Virtualization Secure Nested Paging (SEV-SNP)
  ✗  Page Flush MSR available
  ✗ /dev/sev is readable by user
  ✗ /dev/sev is writable by user
  ✗ MEMLOCK rlimit allows for: 0 keeps (soft limit = 65536 bytes, hard limit = 65536 bytes)
  ✗ SEV-SNP VCEK key cache file: No such file or directory (os error 2)
  ✗ AMD CRL cache file: Error reading `/var/cache/amd-sev/crls.der`

  The MEMLOCK rlimit must be large enough to accommodate the Enarx shim, exec-wasmtime, and the memory pressure requirements of the target workloads across all deployed SEV keeps.


  enarx expects the directory `/var/cache/amd-sev` to exist and be readable


  Run `enarx platform snp cache-crl` to generate the AMD CRL cache file.

✔ Backend: kvm
  ✔ Driver: /dev/kvm
  ✔  API Version: 12
  ✔ CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | GenuineIntel
  ✔  CPU supports FSGSBASE instructions
  ✔  CPU supports RDRAND instruction
✔ Backend: nil
</pre>

**Comment by dpal** [comment]
<pre>
[dpal@dpal enarx]$ cargo run -- run ./tests/client/data/wasm_example/main.wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/enarx run ./tests/client/data/wasm_example/main.wasm`
</pre>

**Comment by dpal** [comment]
<pre>
[dpal@dpal enarx]$ cargo run --features dbg -- --log-filter trace run  ./tests/client/data/wasm_example/main.wasm
   Compiling enarx-shim-sgx v0.6.4 (/home/dpal/code/enarx/crates/shim-sgx)
   Compiling enarx-shim-kvm v0.6.4 (/home/dpal/code/enarx/crates/shim-kvm)
   Compiling enarx v0.6.4 (/home/dpal/code/enarx)
    Finished dev [unoptimized + debuginfo] target(s) in 21.60s
     Running `target/debug/enarx --log-filter trace run ./tests/client/data/wasm_example/main.wasm`
2023-01-12T17:21:26.540701Z  INFO enarx::cli: logging initialized!
2023-01-12T17:21:26.540783Z  INFO enarx::cli: CLI opts: Options { logger: LogOptions { log_filter: Some("trace"), log_target: Stderr }, cmd: Run(Options { backend: BackendOptions { backend: None }, wasmcfgfile: None, module: "./tests/client/data/wasm_example/main.wasm", unsigned: false, signatures: None }) }
init_gdt
interrupts::init
panicked at 'assertion failed: `(left == right)`
  left: `2097152`,
 right: `4096`', crates/shim-kvm/src/exec.rs:100:9
TRACE:
[src/backend/kvm/thread.rs:181] &syscall = Payload {
    num: 231,
    argv: [
        255,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    ],
    ret: [
        18446744073709551578,
        0,
    ],
}

</pre>

**Comment by dpal** [comment]
SELinux does not change anything.

**Comment by haraldh** [comment]
```
panicked at 'assertion failed: `(left == right)`
  left: `2097152`,
 right: `4096`', crates/shim-kvm/src/exec.rs:100:9
```

very interesting!!!

**Comment by dpal** [comment]
It got better but I think there is still some cleanup needed

<pre>
running 26 tests
test backend::kvm::tests::shim_kvm_binary_size ... ignored, debug_assertions active
test backend::sev::snp::firmware::linux::test::offsets ... ok
test backend::sev::snp::firmware::linux::test::align ... ok
test backend::sev::snp::firmware::linux::test::size ... ok
test backend::nil::test::coverage ... ok
test backend::sev::snp::firmware::test::offsets ... ok
test backend::sev::snp::firmware::test::align ... ok
test backend::sev::snp::firmware::test::size ... ok
test backend::sev::snp::firmware::test::test_tcbversion ... ok
test backend::sev::snp::launch::test::align ... ok
test backend::sev::snp::launch::test::size ... ok
test backend::sev::snp::tests::test_const_id_macro ... ok
test backend::sev::snp::launch::test::offsets ... ok
test backend::sev::snp::firmware::test::test_vcek_url ... ok
test backend::sgx::attestation::tests::request_target_info ... ignored, CPU does not support SGX2 or attestation not possible
test backend::sgx::tests::shim_sgx_binary_size ... ignored, debug_assertions active
test backend::sev::snp::vcek::tests::test_invalid_cache_path ... ok
test cli::platform::info::test_info ... ok
test cli::key::sgx::digest::test::test_digest ... ok
test exec::test::coverage ... ok
test cli::sign::test::test_sgx_vector ... ok
test cli::key::sev::digest::test::test_id_digest ... ok
test cli::key::sev::digest::test::test_author_digest ... ok
test cli::key::sev::sign::test::test_sev_vector ... ok
test cli::sign::test::test_sev_vector ... ok
test backend::sev::snp::vcek::tests::test_write ... ok

test result: ok. 23 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.21s

     Running tests/integration.rs (target/debug/deps/integration-65d73ab7eebed5be)

running 36 tests
test exec::futex ... ignored, Backend does not support SGX
test exec::rust_sev_attestation ... ignored, Backend does not support SEV-SNP
test exec::rust_sgx_attestation ... ignored, Backend does not support SGX
test exec::thread ... ignored, Backend does not support SGX
test exec::thread_channel ... ignored, Backend does not support SGX
test exec::thread_exit_group ... ignored, Backend does not support SGX
test exec::thread_many ... ignored, Backend does not support SGX
test client::test_config_init ... ok
Error: 1
test syscall::exit_one ... ok
test syscall::get_att ... ignored, Backend does not support attestation
test exec::cpuid ... ok
test exec::memspike ... ok
test syscall::exit_zero ... ok
test syscall::read ... ok
test syscall::readv ... ok
test syscall::tests ... ok
test syscall::read_udp ... ok
test syscall::write_emsgsize ... ok
test exec::echo ... ok
hi
test syscall::write_stderr ... ok
test syscall::write_stdout ... ok
test exec::unix_echo ... ok
test exec::memory_stress_test ... ok
test client::full ... ok
Error: failed to get default function

Caused by:
    default export in '' is not a function
test wasm::no_export ... ok
test wasm::hello_wasi_snapshot1 ... ok
test wasm::return_1 ... ok
test wasm::memory_stress_test ... ok
test wasm::memspike ... ok
test wasm::echo ... ok
test wasm::wasi_snapshot1 ... ok
test wasm::listen_tcp ... ok
test wasm::connect_tcp ... ok
test wasm::listen_tls ... ok
test wasm::zerooneone ... ok
test wasm::zerooneone_pkg ... ok

test result: ok. 28 passed; 0 failed; 8 ignored; 0 measured; 0 filtered out; finished in 15.41s

[dpal@dpal enarx]$ 

</pre>

See above "Error: 1", "hi" and then an error:
<pre>
Error: failed to get default function

Caused by:
    default export in '' is not a function
</pre>

**Comment by haraldh** [comment]
```
test result: ok. 28 passed; 0 failed; 8 ignored; 0 measured; 0 filtered out; finished in 15.41s
```

It's a test, which tests the failure. Therefore the error message.
