### ISSUE TITLE
Review and study the kernel patch set v7 for AMD SEV-SNP

### ISSUE THREAD

**Issue by dpal** [enarx/enarx#2471]
Discussion around the kernel patch set v7 for AMD SEV-SNP with associated links provided to lore.kernel.org.

**Comment by jarkkojs** [comment]
My personal scrap book: https://hackmd.io/@jarkko/SJi2ofvoo

**Comment by rjzak** [comment]
No longer required via https://github.com/enarx/enarx/pull/2552
