### ISSUE TITLE
Verify wiki's correctness on attestation process

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#250]
#249 installs a basis for documenting the attestation process in the repo instead of the wiki. We need to ensure there is parity between the two of them. 

They are being added to the repo itself to encourage a pull request-based workflow among vendors & other interested parties.

It might be best if we update the wiki to simply point to the in-tree documentation on attestation so that we aren't duplicating the info anywhere.

**Comment by axelsimon** [comment]
Thanks for opening this issue @connorkuehl. This raises a good point: where should this type of advanced, technical documentation reside.

- enarx/wiki:
  - pros: all documentation in the same place, already used for documentation
  - cons: doesn't get pulled automatically when people `git clone` the enarx repo

- enarx/enarx/docs:
  - pros: gets pulled when people `git clone` repo
  - cons: splits documentation

I'm not sure i understand how having the doc directly in the repo itself to encourages "a pull request-based workflow among vendors & other interested parties", i think i might be missing something. Could you maybe expand on this a bit?

**Comment by connorkuehl** [comment]
> Thanks for opening this issue @connorkuehl. This raises a good point: where should this type of advanced, technical documentation reside.
> 
>     * enarx/wiki:
>       
>       * pros: all documentation in the same place, already used for documentation
>       * cons: doesn't get pulled automatically when people `git clone` the enarx repo
> 
>     * enarx/enarx/docs:
>       
>       * pros: gets pulled when people `git clone` repo
>       * cons: splits documentation

Just for posterity, as this was discussed in the standup this morning: documents that are still taking shape until consensus is reached will be placed under enarx/enarx/docs. The appropriate place for the attestation docs being written right now will be enarx/enarx/docs. The wiki could give a very concise, digestible (almost hand-wavey) summary of attestation, but then also provide a link to the top-level of enarx/enarx/docs for people to go if they'd like a more technical explanation.

> I'm not sure i understand how having the doc directly in the repo itself to encourages "a pull request-based workflow among vendors & other interested parties", i think i might be missing something. Could you maybe expand on this a bit?

Of course! Right now, GitHub doesn't offer a way for us to review changes to the wiki via pull requests. That means that direct contributions to the wiki are only possible by a member of the Enarx team; but even then, we have no review mechanism for changes to the wiki like we do for changes to our code (i.e., it must be specifically approved, can be commented on, etc).

Since we are encouraging vendors to contribute documentation similar to #266, we want to make sure there's an accessible way for contributors to formally propose a change to certain documents. Since we can't make pull requests against the wiki, having the documentation inside the repo where we can make pull requests is the next best thing while we iterate on these deeply technical documents to gain consensus.

**Comment by connorkuehl** [comment]
This is a duplicate of #748 and individual technology attestation flows should be separate issues, not one.
