### ISSUE TITLE
Add SGX attestation documentation

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#252]
PR #249 adds a new form of documenting attestation. The goal is to provide a single page to compare and contrast attestation primitives that can receive contributions in the form of PRs.

However, this documentation currently lacks anything on SGX. So we need to add SGX attestation.

**Comment by lkatalin** [comment]
We need:
- [ ] A diagram of the certificate chain (see: #261 )
- [ ] A process diagram of attestation
