### ISSUE TITLE
How many syscalls does Enarx support?

### ISSUE THREAD

**Issue by Antone077** [enarx/enarx#2553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

       After I looked through Enarx, wasitime, wasi-sdk, wasi-libc and other information, and did relevant testing and verification, I found that wasi has a large number of syscalls that are not supported. I only find this link about wasi API/syscall([https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md]). Just over forty syscalls.

**Comment by Antone077** [comment]
After I looked through Enarx, wasitime, wasi-sdk, wasi-libc and other information, and did relevant testing and verification, I found that wasi has a large number of syscalls that are not supported. I only find this link about wasi API/syscall([https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md]). Just over forty syscalls.

**Comment by Antone077** [comment]
After I looked through Enarx, wasitime, wasi-sdk, wasi-libc and other information, and did relevant testing and verification, I found that wasi has a large number of syscalls that are not supported. I only find this link about wasi API/syscall(https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md). Just over forty syscalls.

**Comment by rjzak** [comment]
We've added syscalls when needed, is there something in particular you need?

**Comment by Antone077** [comment]
@rjzak I am very happy to receive your reply, but the number of syscalls supported by Enarx/wasi is too small (compared to TEE containers such as Occlum and gramine). 
And I also find sallyport crate, but How to use syscall supported in sallyport?

**Comment by rjzak** [comment]
@Antone077 syscalls can be added when needed, which do you need? I'd ask that you not rush to judgement due to some syscalls not being supported, maybe all syscalls aren't needed?

In our testing we found the syscalls we support to be sufficient and we are happy to hear about other uses and use cases.

The reason for not supporting all, because the development time vs usefulness tradeoff, a design decision is to make sure data doesn't leak out, and Sallyport enforces this.

**Comment by rjzak** [comment]
@Antone077 the supported syscalls are shown here: https://github.com/enarx/enarx/tree/main/crates/sallyport/src/guest/call/syscall

Enarx returns a fake PID of 1000, as shown here https://github.com/enarx/enarx/blob/3325d7114ac531664a539070a45d4fc442511ce5/crates/sallyport/src/guest/call/syscall/stub.rs#L18, so getpid should work.

Wasi syscalls are syscalls supported by Wasi (like you'd expect), whereas Enarx syscalls are special non-standard syscalls only understood by Enarx. At present, this is used by an Enarx shim (SGX or KVM for SNP) to get attestation evidence (cached data like the CRL, the AMD CPU public key, etc).

**Comment by Antone077** [comment]
@rjzak Thank you very sincerely for your patience in answering my questions.

**Comment by rjzak** [comment]
@Antone077 No problem! I'm happy to help and would like Enarx to be useful for you.
