### ISSUE TITLE
[Feature]: Enable LFX Insights On The Enarx Project 

### ISSUE THREAD

**Issue by bensternthal** [enarx/enarx#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is to track the request to enable LFX Insights for the Enarx project. LFX Insights has already been activated for several other CCC projects and we enable this by default for new projects

**What Is LFX Insights**
Insights provide projects with more visibility into their community dynamics, particularly around contributors, organizations, issues, and pull request metrics. It does this through an app (similar to the DCO bot) installed at the organization level. This is then enabled for one or more repos under the organization. Insights uses [crowd.dev](http://crowd.dev/) under the hood to gather read-only data about specified public repositories in a GitHub organization.

**What Information Is Collected (only public information from Github)**

- Stars/Un-stars
- Forks
- Issues
- Pull requests
- Discussions
- Comments on issues/pull requests/discussions
- Closing of issues/pull requests/discussions

**What I Need From The Project**

If folks have any questions or objections, please note this in the issue. If there are none we will enable insights in a week. 

**How Do We Turn This On**

I need to be made an admin (this can be temporary) on the org, this will allow me to install the read only Linux Foundation app. Once I install the app my privileges can be revoked.

Note I am currently on staff at the LF and one of the Program Managers on CCC. Feel free to verify my identity with folks on CCC.

**More Info**
You can find [Insights documentation here](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current).

### Acceptance Criteria

N/A

### Suggestions for a technical implementation

N/A

**Comment by rjzak** [comment]
I've invited you to the org.

**Comment by rjzak** [comment]
App approved.

**Comment by bensternthal** [comment]
@rjzak looks like i need to be an owner of the org to complete this. Are you OK upping my permissions? Note once I finish the install you can entirely remove me as an admin.

**Comment by rjzak** [comment]
Done.

**Comment by bensternthal** [comment]
@rjzak Woo, ok I have added the project and you can disable my admin access. It can take some time for metrics to appear as LF loads and processes information.  In a few days metrics for the project should be visible at the following URL:

https://insights.lfx.linuxfoundation.org/foundation/ccc

**Comment by rjzak** [comment]
Neat!
