### ISSUE TITLE
SGX: Test IOCTLs

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#27]
Write tests for `SGX_IOC_ENCLAVE_ADD_PAGES` and `SGX_IOC_ENCLAVE_SET_ATTRIBUTE`, as well as `SGX_IOC_ENCLAVE_CREATE`. These are specified in `sgx-sys/src/ioctls/sgx.rs`.

There is already one test for `SGX_IOC_ENCLAVE_CREATE` in `sgx-sys/src/lib.rs`.

All of these tests should be labeled with `#[cfg_attr(not(has_sgx), ignore)]` so that they do not run if SGX is not present on the system.

**Comment by steveeJ** [comment]
replaced by #32 #31 #30

**Comment by steveeJ** [comment]
f
