### ISSUE TITLE
Cache Github Actions dependencies

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#270]
Actions allows us to [cache](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) dependencies to speed up workflows. This would be very helpful, as the majority of test time is actually spent downloading and booting up our testing container. If we're able to cache it, things might go quicker.

**Comment by platten** [comment]
We now use prebuilt containers for this, so this is no longer an issue.
