### ISSUE TITLE
Move enarx.io domain to CCC

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#291]
Now that the project has been fully moved over to the CCC, the enarx.io domain should be transferred as well (along with anything else which hasn't been).

**Comment by axelsimon** [comment]
I have been discussing this with Stephano of the Linux Foundation over the past few days. We should have a more concrete idea of what the LF can offer before the end of the week.

**Comment by axelsimon** [comment]
The Confidential Computing Consortium board has approved the funding of the move. The next step is for the Technical Advisory Council to look into it, should happen next Tuesday and then get an email from the Linux Foundation's IT folks.

**Comment by axelsimon** [comment]
Waiting on the LF IT folks, this is otherwise on track.

**Comment by axelsimon** [comment]
Ok, the ball is in our court right now, i'm trying to suss out the way to do this properly with regards to the LF's process.

Here's my current summary of the situation:
- website: remains hosted on Github pages, only need to update the right DNS entries for enarx.io
- domain: registered with comlaude.com, will need to be unlocked to move to the LF's registrar
-- subdomains: we currently don't use any but want to use one for our CI/CD and the servers Packet is graciously making available to us.
- email: we currently only have 4 addresses, all forwards, and this doesn't need to change
- mailing lists: currently none, but we get some with the LF if want to use them

With these elements in mind (and following the LF-provided flowchart) my understanding is that we will transfer both domain and DNS service to the Linux Foundation.

Here are some questions i have:
-  Do we agree that simply having one subdomain delegated to "our" DNS provider (currently, Red Hat) is enough for our needs, but *beyond that* we won't need to make future changes to the zone ourselves?
- Regarding the subdomain, i'm thinking infra.enarx.io would be good. Thoughts?
- Who will be in charge of providing DNS service for the delegated subdomain? Do we stick with ns{1,4}.redhat.com, or should we use something else?

Then there is this bit:
> For compliance reasons, the Linux Foundation needs to have access to each GitHub organization you use to host your code.  Your governance body and authorized community members will still be responsible and accountable for day-to-day administration of repositories, teams, and users.
> 
> Then, invite the user “thelinuxfoundation” as an owner at the organization level (not per repository) to your project organization(s).

I don't think this poses any concerns, but i wanted to raise it with you all.
@npmccallum @mbestavros please provide guidance :)

**Comment by npmccallum** [comment]
Let me start by saying that there are currently three entities:
* The Linux Foundation (CCC)
* The Enarx Project
* Red Hat, Inc.

Therefore, I propose:

1. The Linux Foundation (CCC) owns the domain and pays for renewals.

2. Red Hat, Inc. transfers the domain to The Linux Foundation.

3. The Linux Foundation grants the Enarx Project full management of the email forwards and DNS.

We are a highly technical, security-aware project that needs low level control for our CI pipeline. We also need our infrastructure management to be agile and responsive. Our current experience with both Red Hat, Inc. and The Linux Foundation has been that neither can provide the kind of agility or control that we need to be successful. Waiting days (or months as we've experienced) to get a DNS update for a CI server is simply not workable.

Currently, our CI pipeline is entirely blocked on DNS. We simply can't wait longer for this.

**Comment by npmccallum** [comment]
@axelsimon IMHO, our DNS layout should go through the RFC process.

**Comment by axelsimon** [comment]
> Therefore, I propose:
> 
>     1. The Linux Foundation (CCC) owns the domain and pays for renewals.
>     2. Red Hat, Inc. transfers the domain to The Linux Foundation.
>     3. The Linux Foundation grants the Enarx Project full management of the email forwards and DNS

The LF has a specific process for this, which i'm trying to follow.
1. is mandatory, LF must own the domain and as such, it must be transferred to its registrar
2. is a consequence of 1. (or simply a means to achieve it)
3. Is possible, if non-standard, from my understanding. But deciding to do this (manage email and DNS ourselves) doesn't clear up the 3rd question i was asking in my previous comment: 
> Who will be in charge of providing DNS service for the delegated subdomain? Do we stick with ns{1,4}.redhat.com, or should we use something else?
This is still a question, whether LF delegate a subdomain that we can manage as we see fit or we keep control over the whole DNS configuration: which DNS servers/service de we rely on? I really don't think we should be managing our own name servers.

That being said, i agree we should define our DNS architecture in an RFC, but i think that document should reflect the state of what we (will) have rather than be a prerequisite to getting the changes in place. As you've said, things are taking long enough as they are.

**Comment by npmccallum** [comment]
> > Who will be in charge of providing DNS service for the delegated subdomain? Do we stick with ns{1,4}.redhat.com, or should we use something else?

I'm proposing that and individual in the Enarx project have **direct** access to change DNS and email forwards. We currently **do not** have that with `ns{1,4}.redhat.com`. We are simply developing too quickly to not have this agility.

**Comment by MikeCamel** [comment]
@axelsimon - do we have a specific blocker that I can identify, please?

**Comment by axelsimon** [comment]
@MikeCamel Yes: we want to be able to manage at least _some_ DNS configuration, but we don't know what DNS server / service we would actually be using for said management.
Not Red Hat's and we don't want to run our own. And the LF allows this, but if using a "3rd party DNS service".

Quoting the LF might be helpful here:

The LF…
> …can configure any domains to point to any server as a 1-time setup. Also, if we need the ability to create sub domains on the fly (for CI/CD), the LF can "delegate" a subdomain, for instance, LF can delegate dev.enarx.io to our 3rd-party DNS service, and we can create as many sub-sub-domains under it as we want if needed for CI/CD-based setup/teardown. 

(pronouns adjusted for grammatical clarity)

**Comment by MikeCamel** [comment]
So we need to decide on one. Suggestions / preferences?

**Comment by axelsimon** [comment]
I'm going to look at what DNS service Packet uses/offers for their service, it could be the simplest solution at the end of the day.
@npmccallum will look into inviting me to the Enarx project on Packet.

**Comment by axelsimon** [comment]
Unfortunately, it doesn't appear that Packet offers a way to manage DNS entries (sorry, resource records :wink:)  as a user.
I will be talking with the LF tomorrow hovewer, and we will find a way to sort this out.

**Comment by axelsimon** [comment]
Quick summary of yesterday's conversation with the LF:
- LF IT is pretty fast, so any changes we'd need to DNS entries should be done fast (ie: ~1 day)
- given that, transferring domain + DNS to LF IT sounds like the best solution
- LF is up for trying to automate as much as possible, as we are, so good grounds for collaboration there (DNS zone updates by PR in a git repo?)
- should we need more flexibility on DNS record updates, we can always change this setup and delegate a subdomain to a different DNS service (but not DNSimple, which appears to be incompatible with LF IT).

**Comment by axelsimon** [comment]
Update: trying to find the right path to get the changes requested + DNS zone from Red Hat internal IT.

**Comment by axelsimon** [comment]
Domain hand-over to LF is underway. :balloon:

**Comment by axelsimon** [comment]
Finally, the transfer is all done! 🎉
Thanks everyone for your help and patience.

```
$ dig -t NS enarx.io +nostats +nocomments +nocmd
;enarx.io.                      IN      NS
enarx.io.               3559    IN      NS      ns1.dnsimple.com.
enarx.io.               3559    IN      NS      ns2.dnsimple.com.
enarx.io.               3559    IN      NS      ns3.dnsimple.com.
enarx.io.               3559    IN      NS      ns4.dnsimple.com.
```

Any further requests regarding IT we can make directly to the Linux Foundation. I'm closing this issue now.
