### ISSUE TITLE
SGX: Test the failure cases of SGX_IOC_ENCLAVE_CREATE IOCTL

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#30]
There is already one test for this in `sgx-sys/src/lib.rs`.

Any tests should be labeled with #[cfg_attr(not(has_sgx), ignore)] so that they do not run if SGX is not present on the system.

**Comment by steveeJ** [comment]
We have a test for this to ensure positive outcome at https://github.com/enarx/enarx/blob/27ead2abb679dbcab5bf72543d20dd3631c87550/sgx-sys/src/lib.rs#L105-L111.

I would like to see a test covering an error case. 

@npmccallum @lkatalin what could possibly go wrong when creating the enclave, and how can we simulate that in a test?

**Comment by platten** [comment]
Kernel is the arbiter of what cases fail and returns an exist status which we correctly handle, therefore this is not our problem.
