### ISSUE TITLE
Improve Linux kernel's permission checks for SEV ioctls

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#301]
Right now, the SEV ioctls that affect the state of the platform require CAP_SYS_ADMIN to run. This is not a capability we can give to an automated test runner, because it means that anyone who would like to contribute to the project would be able to run any code they want (for good or evil) as  AP_SYS_ADMIN on our machine.

[Patch v1](https://lkml.org/lkml/2020/3/6/800)

**Comment by connorkuehl** [comment]
[The patch has been applied to the crypto subsystem](https://lkml.org/lkml/2020/3/12/449)

**Comment by npmccallum** [comment]
@connorkuehl Please file a separate issue for a copr kernel build.

**Comment by npmccallum** [comment]
(Which is unsupported, to be clear.)

**Comment by connorkuehl** [comment]
Done! #319

**Comment by connorkuehl** [comment]
[This has been merged into Linux 5.7](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b61028135843d5418f0469d11e2769ca77159463).

I've requested a backport of this patch into Fedora. [BZ: 1827393](https://bugzilla.redhat.com/show_bug.cgi?id=1827393).

I think our work here is done until the backport is performed and I can drop the patch from my packaging repo for the Enarx kernels.
