### ISSUE TITLE
Improve ELF header sanity checking

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#308]
Currently, the SGX ELF header checks just assert. We probably want errors. Also, we should probably check more header fields to ensure we're looking at the right kind of binary.

~~https://github.com/enarx/enarx/blob/master/enarx-keep-sgx/src/component.rs~~

[ @connorkuehl: the component in question now lives in the enarx-keepldr repo, under file path src/binary/component.rs ]

**Comment by platten** [comment]
Implemented during backend rewrite.
