### ISSUE TITLE
Investigate serde incremental serialization

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#312]
We need to be able to serialize commands between the host and the guest. A self-describing format would be preferred for its security benefits. Performance and memory usage are always a concern. We also need a `#![no_std]` implementation.

We have identified `serde` and `serde-cbor` as a strong potential candidate.

However, one thing that isn't clear from the documentation is how to perform incremental serialization. A concrete example will show why this is needed.

Let's say that we want to proxy the `write()` syscall to the host. The guest calls `write()` and in the shim we have to handle the `write()` syscall. This means we need to forward the request to the host. In order to do this we have one or more bounce buffers (for example, a ring buffer).

Our syscall data structure might look like this:

```rust
#[derive(Serialize, Deserialize)]
enum Syscall {
   Write { fd: u32, data: &[u8] }
}
```

When we attempt to serialize this, the `data` field could be arbitrarily large. But since our bounce buffers are fixed size, we might need to break this serialization into multiple chunks and send it incrementally. What makes this problem particularly hard is that we need to do this in a `#![no_std]` environment without allocation. Therefore, we can't just do the full serialization into a `Vec` and then frame it from there.

So the question are: what are our options? Can `serde` actually help us here?

**Comment by mbestavros** [comment]
We are no longer using `serde`, so we're closing this.
