### ISSUE TITLE
Containerize GH Actions self-hosted runner setup

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#320]
As we ramp up the hardware infrastructure available for our self-hosted CI testing, we should automate the currently very manual setup for adding a GH Actions self-hosted runner with a container.

@npmccallum and I have preliminarily talked about this; we figure that runner keys could be given as input to the container, which would then
- set up a runner with all dependencies and necessary configuration
- connect it to Github with that key

[This container](https://github.com/tcardonne/docker-github-runner/blob/master/debian-buster/Dockerfile) might be a good starting point.

**Comment by platten** [comment]
We moved to a different testing infrastructure and this is no longer applicable.
