### ISSUE TITLE
save/restore/clear extended CPU state

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#334]
Since #326, we can now context switch between an enclave and the outside world. We don't currently do anything with the extended CPU state. The workflow should look like this:

1. Clear exCPU state when entering and exiting enclave.
2. Save exCPU state before calling syscall().
3. Restore exCPU state after syscall() returns.

**Comment by lkatalin** [comment]
@npmccallum I'm looking through the [doc](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3d-part-4-manual.pdf), 42.7 INTERACTIONS WITH THE PROCESSOR EXTENDED STATE AND MISCELLANEOUS STATE. It describes the way `xfrm` specifies which extended states to save in SSA on an AEX, among other things. Does this sound right?

Specifically, it's describing:

- At enclave entry, `xcr0` is saved internally to the enclave and replaced by `xfrm`. On exit, `xcr0` is restored. Is this the same as (1)?
- On an AEX, `xfrm`-enabled states are saved into SSA. Is this the same as (2)?
- On resuming from AEX, the states from SSA are restored. Is this the same as (3)?

You also mentioned our asm function can take a pointer to a Rust buffer to set/clear the state. Does this correspond to all 3 workflow steps?

**Comment by npmccallum** [comment]
> @npmccallum I'm looking through the [doc](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-3d-part-4-manual.pdf), 42.7 INTERACTIONS WITH THE PROCESSOR EXTENDED STATE AND MISCELLANEOUS STATE. It describes the way `xfrm` specifies which extended states to save in SSA on an AEX, among other things. Does this sound right?
> 
> Specifically, it's describing:
> 
> * At enclave entry, `xcr0` is saved internally to the enclave and replaced by `xfrm`. On exit, `xcr0` is restored. Is this the same as (1)?
> * On an AEX, `xfrm`-enabled states are saved into SSA. Is this the same as (2)?
> * On resuming from AEX, the states from SSA are restored. Is this the same as (3)?

No. None of this will be in the manual. It is presumed that we know what we're doing.

Specifically, we need to use the following instructions:
* https://www.felixcloutier.com/x86/xsaveopt (or one of its variants)
* https://www.felixcloutier.com/x86/xrstor

(1) this basically means the first thing and last thin in the `entry()` and `event()` functions.

(2) and (3) refer to before and after calling the `syscall()` function.

> You also mentioned our asm function can take a pointer to a Rust buffer to set/clear the state. Does this correspond to all 3 workflow steps?

Yes. Basically, you call `XSAVEOPT` and `XRSTOR` with a pointer to a buffer.

**Comment by lkatalin** [comment]
One future concern with this as raised by @haraldh is that in the future, there could be more / larger extended CPU state registers, so our buffer would be too small to hold the values that will be written during `xsave`. Normally this can be checked by reading `cpuid`, but `cpuid` is not available in SGX.

Possible safety checks could include reading `xcr0` before the `xsave`, asserting that `xgetbv == 0x1f`, or setting a mask in `edx:eax` of `0:0x1f` to check that the CPU is not using more registers than the buffer expects. However, future CPUs assuming a larger buffer size for `xsave` is unlikely according to @npmccallum . Also, with SGX, the enclave author sets the buffer size and signs the enclave+metadata with the flags appropriately set. This can be validated in attestation.

We are considering putting safety checks for this type of assumption in the loader directly, and/or creating an `enarx-keep-scan` binary that integrates both `sgx-info` and `sev-info` and detects which keep technology is supported by the hardware.

**Comment by npmccallum** [comment]
We should ask Intel directly about this.

**Comment by haraldh** [comment]
So AMD apparently has defined an area for cpuid presets, which the hypervisor provides and which the SEV firmware corrects, if the hypervisor tries to lie about the xsave size, e.g.

**Comment by haraldh** [comment]
Page 16 of https://www.amd.com/system/files/TechDocs/SEV-SNP-strengthening-vm-isolation-with-integrity-protection-and-more.pdf

**Comment by lkatalin** [comment]
We can address this with #501 .

**Comment by lkatalin** [comment]
Instead of #501  , we're checking the flags in `xcr0` here and checking the sizes associated with each flag in the host.

**Comment by lkatalin** [comment]
The most updated branch for saving and restoring the xCPU state is here: https://github.com/lkatalin/enarx/blob/SAVEBRANCHxrstor/enarx-keep-sgx-shim/src/start.S

It's a WIP but manipulating the trusted stack before/after the syscall mostly works. Biggest issue is how to do the hardcoded offsets at the end after the alignment.

**Comment by lkatalin** [comment]
We have learned that the xCPU state is defined in the systemd x86 ABI as volatile, so when calling syscall to proxy out to the host, the compiler has to have already backed up any state it wants to preserve across that function. This means we don't need to back up the xCPU state ourselves.

We plan to lean more on the systemd ABI: 
- all registers listed as nonvolatile will be preserved and returned to host;
- all other registers (volatile) will be zeroed on entry/exit
- all xcpu state will be zeroed on entry/exit
- because we'll zero the volatile cpu state, we can do most of it from Rust.

The PR to clear xCPU state on enclave entry and exit was already merged earlier (#562 ), and we don't need to do more, so this issue is closed.
