### ISSUE TITLE
sgx shim tamper detection

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#337]
We should add a trusted variable to `SSA[0]` that indicates that we have detected tampering. Since the enclave can't really terminate itself without the host's cooperation, we should use this switch to immediately exit an enclave if it is on. That way, if we detect "odd" situations (such as being asked to handle an exception that doesn't match AEX SSA contents) we can flip the switch and never run most of the code in the enclave again.

**Comment by npmccallum** [comment]
Another great example of an odd situation is if we proxy the exit syscall and it returns.

**Comment by MikeCamel** [comment]
+1 for tamper-evidence.

**Comment by lkatalin** [comment]
@npmccallum If tampering is detected, would it make sense to immediately exit by calling `handler.attacked()`? Do we want to add more situations that would trigger `attacked()` via this trusted variable, or were we hoping to have the trusted variable result in some other action?

**Comment by npmccallum** [comment]
@lkatalin Currently `handler.attacked()` sends the exit syscall to the host.

The host can choose to ignore that syscall and re-enter the enclave. That's what we need to prevent.
