### ISSUE TITLE
SGX: Include an sgx-hasher crate

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#34]
This crate will include a `hasher` struct that:
- [x] Takes in `Secs` and outputs a hash based on SGX documentation for `EADD` and `EEXTEND`
- [ ] Generates an RSA pubkey from OpenSSL and extracts relevant data for `sgx-types::sig::Signature`:
    - [x] modulus
    - [x] exponent
    - [ ] q1
    - [ ] q2
- [x] Goes through the same steps as the `Builder` trait but without actually creating the enclave

**Comment by mbestavros** [comment]
Fixed in #49.
