### ISSUE TITLE
CI tests seem to disagree with each other regarding newline at EOF

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#340]
We have [a test that ensures our files have a blank line at EOF](https://github.com/enarx/enarx/blob/master/.tests/misc-eof). This appears to be at odds with `cargo fmt`, which complains that there _is_ a line at EOF. For an example, see [this pull request's failed check](https://github.com/enarx/enarx/pull/202/checks?check_run_id=514742834).

The requirement for a new line at EOF is not specified in our [style guide](https://github.com/enarx/enarx/wiki/Coding-Style). Our style guide does make a point of deferring to the official Rust formatting guide (which `cargo fmt` enforces). If `cargo fmt` does not want new lines at EOF, then do we?

If so, we will need to convince `cargo fmt` of this, otherwise some pull requests will spurriously fail in the CI pipeline.

**Comment by npmccallum** [comment]
We will always defer to `cargo fmt` on this point.
