### ISSUE TITLE
Add docs to `enarx-keep-sgx-shim`

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#343]
The `enarx-keep-sgx-shim` crate currently fails the `#![deny(missing_docs)]` lint test. It's been grandfathered in to make the tests pass, but we should add docs to make the test pass properly.

**Comment by lkatalin** [comment]
Looks like there is already a `#![deny(missing_docs)]` in this [module](https://github.com/enarx/enarx-keepldr/blob/master/internal/shim-sgx/src/main.rs#L11), should we close? @npmccallum @mbestavros

**Comment by npmccallum** [comment]
Yup. This is done.
