### ISSUE TITLE
Social Media Image

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#35]
GitHub allows us to set a "social preview" image. Preferred size is 1280x640px.

**Comment by MikeCamel** [comment]
Complete for enarx/enarx.  Do we want the same for the other projects?

**Comment by npmccallum** [comment]
@MikeCamel I was hoping for something a little more custom (and the proper size).

**Comment by MikeCamel** [comment]
Better to have something than nothing, I'd say.  And it is the proper size, I believe: the template specified borders (to which I've kept).

**Comment by mbestavros** [comment]
Image is here, so I'm closing this.
