### ISSUE TITLE
Managing of ongoing and/or recurring tasks

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#356]
**Description**
We regularly are faced ongoing tasks, such as #232 or #221, which require to start a document but then keep it up to date.

**Solutions**
One solution, as suggested by @connorkuehl, is to close the inital issue and then have a regular "update" issue created automatically to track the progress of the ongoing task: if there is something to do to keep, say, the document up to date, the issue serves as a reminder to do it. If there isn't anything to do, the issue can be closed until the next one pops up.

This system would take care of both ongoing and recurring tasks.

The question is, can it be put in place with the current Github tooling?

**Comment by npmccallum** [comment]
After review, we felt we could close this issue since we're now handling this during the sprint process.
