### ISSUE TITLE
crt0stack should take [usize]

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#363]
Currently, `crt0stack` works in terms of `&[u8]` buffers. However, this almost guarantees that alignment will be incorrect, wasting space in the buffer. We should switch to `&[usize]` buffers instead.

FYI: @haraldh

**Comment by haraldh** [comment]
yeah

**Comment by npmccallum** [comment]
It appears that the alignment requirement is 16 bytes for x86_64. But `usize` only aligns to 8 bytes. `u128` only aligns to 8 bytes too. So it might not be straightforward.

**Comment by haraldh** [comment]
Do you think this is still an issue?

**Comment by npmccallum** [comment]
@haraldh We should probably do a sensible `align_to()` inside the constructor.

**Comment by haraldh** [comment]
@npmccallum 

Hmm, thinking about this, we have a stack where we fill the bottom of the slice.
And we already align there. And the resulting handle is somewhere near the bottom.

**Comment by npmccallum** [comment]
I think we only align to 8 there. We need to align to at least 16. But our SGX code crashes if we don't align to 32 bytes, I don't know why.

**Comment by haraldh** [comment]
This is fixed now, but we might want to wait to close it until #613 is merged
