### ISSUE TITLE
Use libc w/ no_std instead of nolibc

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#364]
https://github.com/enarx/enarx/pull/362

The above PR adds the nolibc crate for housing libc stuff in no_std contexts. We should replace this with the actual `libc` crate in `no_std` mode. However, our current workspace layout makes that impossible because all features in the dependency graph are summed.

**Comment by connorkuehl** [comment]
Closing in favor of #500 since it already has been assigned.
