### ISSUE TITLE
Sorting Hat: Figure out a way for non-project members to label their PRs without needing elevated permissions

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#379]
As detailed in #218 and #243, we need a way to allow potential contributors (that is, people that want to contribute, but do not yet have elevated permissions) to interact with and, to an extent, manage the organization of issues and PRs. Right now, that is pretty much entirely restricted to members of the Enarx Github organization's project team.

Our infrastructure plan centers on normalizing most issue/PR metadata around labels. If we can allow the public to set labels on their own PRs, our other actions would then organize it correctly, for the most part. We should look into ways to allow that.

**Comment by dpal** [comment]
Two years passed and it is unclear whether we will do something about it any time soon. Suggest closing.
