### ISSUE TITLE
Investigate availability of TEEs on Alibaba Cloud

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#389]
**Description**
Alibaba Cloud support SGX [https://www.alibabacloud.com/help/faq-detail/89859.htm](https://www.alibabacloud.com/help/faq-detail/89859.htm).  It would be good to find out more, and possibly procure resources for CI/testing.

**Comment by MikeCamel** [comment]
I've emailed Xiaoning Li, Alibaba Cloud TAC member on the CCC, for more information.

**Comment by MikeCamel** [comment]
https://www.alibabacloud.com/help/doc-detail/108507.htm

**Comment by MikeCamel** [comment]
Have emailed CCC folks to find a contact within Alibaba, as I've heard nothing back from the contact I had.

**Comment by platten** [comment]
No longer applicable.
