### ISSUE TITLE
Investigate Krustlet

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#414]
**Description**
Krustlet is a way of running WebAssembly binaries as kubelets in kubernetes.  It needs investigation to see if we can use any of the project, or collaborate with them at all.

*

**Comment by MikeCamel** [comment]
https://deislabs.io/posts/introducing-krustlet/
https://github.com/deislabs/krustlet

**Comment by npmccallum** [comment]
It is basically just a thin veneer around wasmtime.

**Comment by axelsimon** [comment]
As discussed, taking this one! Thanks.

**Comment by squillace** [comment]
@npmccallum not really; wasmtime and wascc at the moment (v0.1.0), and others coming. The attempt is to find a way to explore using wasm/wasi runtimes with k8s; not to choose a specific one this early in the game.

**Comment by npmccallum** [comment]
@squillace Thanks for the correction!

**Comment by squillace** [comment]
not a problem. The project is all oss, and we'd be happy to see whether there's any way to see enarx running on it -- a great exercise.

**Comment by npmccallum** [comment]
@squillace Enarx is another WASM runtime with low-level hardware integration. It probably won't run on krustlet very well. :)

**Comment by squillace** [comment]
probably not, but then the question is what would NEED to be done to enable it? That's good information, as Krustlet is an experiment to see whether the use of wasm/i in clusters is a good thing, a useful thing, or not. if it proves useful, then we need to build a better, more flexible and useful implementation.

**Comment by npmccallum** [comment]
@squillace I completely agree. Good luck!

**Comment by MikeCamel** [comment]
@squillace I'm particularly interested in any work you end up doing around packaging of Wasm binaries.  Any plans in that area?

**Comment by squillace** [comment]
By packaging, do you mean distribution? If so, we use the emerging "artifacts" support in oci distribution. https://radu-matei.com/blog/wasm-to-oci/

At the moment, Azure Container Registry supports it, as does docker distribution > 2.7,but the other major registries will shortly add well.

There are other ways to do this, and while we think this approach is familiar for people who are on the container and K8s world there will be other distribution mechanism that come. 

Is this what you meant?
