### ISSUE TITLE
Propose to run execution and attestation decentralized to improve security

### ISSUE THREAD

**Issue by kevingzhang** [enarx/enarx#42]
Our current design has done all that we have in 2019 to improve the security unless for one possible thing I propose to improve: that is to decentralize the execution and attestation from one node to a consensus between a group of nodes. 

We can add a few steps as the following

- Connect all Enarx nodes into a huge p2p network (swarm)

- When a client deploys a wasm task, all nodes need to run a VRF to decide which node will actually run this task. At this moment, only the node who wins this VRF competition knows he is the winner. The client, the host, and other nodes do not know what a node is currently running which task until the task is completed we will discuss later time.

- The host or the attestation code in the same node cannot claim itself a “trusted” TEE. The attestation is done by other VRF selected nodes. No one can predict or decide who is validator for who. If necessary, those VRF selected validators can run a BFT consensus to decide the truthfulness of the node who is under attestation. 

- Executors and validators will be paid for doing an honest job after the execution is completed. That means who has run which task will only be disclosed after the task is completed. (So no security information exists any more at this moment)

- A credit score system can be used to incentivize good behavior. As well as slashing can be used for punishment.

By doing so we can get these benefits:

- No matter a task is a high attacking value or not, no one knows which node it is executing on. This reduces the profit attraction to hackers. A hacker has to hack more nodes to get enough profit to cover his costs.

- If one kind of under layer TEE has any secure issue, we can easily adjust the VRF function factor in real-time, so new tasks will be automatically routed away from those unsecured nodes until the problem fixed. 

- Unless hackers can comprise a large number of nodes at the same time, one comprised node can hardly pass the attestation of other healthy nodes. So it will be easily quarantine. 
Bitcoin-like token incentives can be used to fast boost the ecosystem.

- Red hat doesn't need to run an attestation service. No single point of failure, no centralization.

Sorry, I did not find any designated place to propose this kind of improvement idea, so I post here as an issue. I hope I did not break any contribution rules here for discussion. If I did, I am sorry.

BTW, all technologies I mentioned here are mature and widely used in blockchain. If this idea can be adopted as an improvement proposal, I can contribute to this child project as this is what I was researching recently.

**Comment by npmccallum** [comment]
We love forward thinking like this. I'm going to invite some others to join this conversation.

One big question I have is: who attests the attestation validator? We probably need some bootstrap phase where the first validator is manually validated. Then its job is to bring up a validation cluster.

**Comment by MikeCamel** [comment]
Kevin -

This is great!  And it's exactly the sort of use case that we think Enarx should enable.  I'm particularly passionate about p2p use cases, so this fits very closely with my interests.

I'd be interested in hosting a mini-seminar (open to all!) at some point in the new year, and inviting other folks who we think might have overlapping thoughts in this area.  How do you feel about this?  We'd probably do it solely online, unless a number of us happen to be in the same place at the same time (an existing conference, maybe)? 

-Mike.

**Comment by jrlinton** [comment]
I agree that this is good thinking and see this being in line with the general (very positive) trend toward decentralization. I would suggest pursuing a decentralized/stochastic structure like the one Kevin describes, while also maintaining support for today's prevalent centralized/deterministic orchestration methods such as K8s / OpenShift.

@MikeCamel I would definitely be interested in participating.

**Comment by kevingzhang** [comment]
Thank you for so many positive feedbacks, it is out of my expectation already. 
Let me answer those questions one by one.
>>> One big question I have is: who attests the attestation validator? We probably need some bootstrap phase where the first validator is manually validated. Then its job is to bring up a validation cluster.

MY ANSWER: Let’s assume we use some kind of BFT as our consensus, we would assume that more ⅔ of attestation validators are honest good nodes. Existing validators can approve other new validators to join the network. So in the beginning, we need to guarantee a few 100% trusted nodes to “cold” start. Usually, our core team members, Redhat, or CCC’s big members can start work as original or bootstrap validators. As time goes by, new validators joining will dilute this kind of “original” decentralization. I designed an algorithm to reduce the Mathew Effect so that there are always opportunities for newcomers. So, yes @npmccallum , we do need the bootstrap phase you mentioned in your question.

**Comment by kevingzhang** [comment]
> I'd be interested in hosting a mini-seminar (open to all!) at some point in the new year, and inviting other folks who we think might have overlapping thoughts in this area. How do you feel about this? We'd probably do it solely online, unless a number of us happen to be in the same place at the same time (an existing conference, maybe)?
Hi  @MikeCamel , of course, I d love to. I’d like to have more people discuss this idea and more people to join. My holiday schedule is like this. I will be FL for a cruise vacation in Bahama Islands for 10 days. I will be back in the bay area (where I live) in CA on Jan7. I am open anytime after Jan 8. BTW, the current standup meeting time is kind of too early to me. It starts at 6 am Pacific time. You know no coder is an early bird. So please consider my time zone (and all other Californians).

I work totally online with remote team members for so many years. I am (and only) happy with online meetings due to the terrible traffic situation in Silicon Valley these years.

**Comment by MikeCamel** [comment]
@kevingzhang -
We've been waiting to see where external contributors will start turning up, so we can decide when to have meetings.  We'll probably change one or more of the daily meetings to a later time: would any particular day suit you?
-Mike

**Comment by kevingzhang** [comment]
> I agree that this is good thinking and see this being in line with the general (very positive) trend toward decentralization. I would suggest pursuing a decentralized/stochastic structure like the one Kevin describes, while also maintaining support for today's prevalent centralized/deterministic orchestration methods such as K8s / OpenShift.

A well-designed consensus can fit both decentralized and today's prevalent centralized system. My idea is a so-called credit score system. The credit points work like the "S" in the PoS, but you cannot buy your points using any kind of money / crypto so that we can prevent Billionaire Attack. The credit score only generated by honest work over a relatively long period of time. In our current capitalism system, money is NOT a fair measurement to everyone, but time is, and always is fair to everyone. Bill Gates has 24 hours a day too.

In order to protect the decentralized validation system when it is still a baby, we should make sure the few well-known trusted validators to keep more than 2/3 voting power for a relatively long period. When the p2p network grown while many other nodes join in, the algorithm should dilute and distributes more score to other nodes so that we can get an overall balanced distribution. 

Furthermore, a client can decide to join either the global decentralized Enarx swarm , or, a federal swarm, or even a private even single node based on the client's needs. General speaking, a decentralized system is usually slower and expensive, in return, better security if large enough.

**Comment by kevingzhang** [comment]
Hi @MikeCamel In my typical daily schedule, I work 9:30 am to 10:30 pm Pacific time. So any time in between is OK to me as long as scheduled in advance. It is still OK if we only have team members spread in North America and Europe. It would get harder to find a common awake time if people from Asia join too. At any given time, there would always be someone sleep among the Americas, Europe or Asia. That's why we can our world global.

**Comment by kevingzhang** [comment]
Before the "formal" meeting, we can always discuss here, or gitter synchronized. I'd like to hear more from others so that we can improve the idea together. I also have many detail technical design on this idea, would like to share with all of us.

**Comment by jrlinton** [comment]
@kevingzhang  I agree in principle that a well-designed consensus system might work for centralized and decentralized systems; I was more concerned that we stay flexible enough to support systems that aren't consensus based at all. 

When it comes to consensus mechanisms, I'd also suggest considering something along the lines of what Dfinity recently came up with - it seems to sidestep a lot of BFT-related problems.

**Comment by kevingzhang** [comment]
Hi @jrlinton to make sure I fully understand your concern, could you give me some example in detail on the system that not consensus-based.

**Comment by MikeCamel** [comment]
@kevingzhang - some systems (such as private blockchains) might provide round-robin or elections, or even assign randomly. Is this what you had in mind, @jrlinton?

**Comment by MikeCamel** [comment]
@kevingzhang We haven't got around to doing anything around this yet, for which many apologies. The project is currently focused firmly on development issues, but that doesn't mean that we don't to keep options open around this.  I'd like to propose that we close this issue as it's been dormant for a while, but that we maybe create a page in the Wiki to summarise this discussion as a forward-looking option, with a link to this issue.  How does this sound to you?

**Comment by kevingzhang** [comment]
sound good
