### ISSUE TITLE
Port existing types to use memory crate

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#423]
https://github.com/enarx/enarx/commit/3c9c8f6992c6254837c2e673ec7d3ee10e7bed6f

Now that we have the memory crate, we should port existing structure to use these types. In particular, `sgx_types::ssa::Gpr`.

@lkatalin FYI

**Comment by lkatalin** [comment]
Note to self: the `Register` type should also be used on:

- [ ] https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/entry.rs#L72
- [ ] https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/handler.rs#L116
- [ ] https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/event.rs#L18

**Comment by npmccallum** [comment]
Probably. But I no longer want to track this individually.
