### ISSUE TITLE
Deduplicate Layout struct

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#424]
Currently, the SGX Layout struct is defined in two places. This is because the `enarx-keep-sgx-shim` uses `u64` and `enarx-keep-sgx` uses `usize`. This can be fixed with the aid of the new `memory` crate. https://github.com/enarx/enarx/commit/3c9c8f6992c6254837c2e673ec7d3ee10e7bed6f

The two sgx crates should grow a third, shared crate that contains `Layout` and is used by both existing crates. Additionally, the use of `u64` for registers should be converted to `memory::Register<usize>` or `memory::Register<u64>` as appropriate.

Related: https://github.com/enarx/enarx/issues/423

**Comment by npmccallum** [comment]
See #541 for a related prerequisite.

**Comment by npmccallum** [comment]
@blazebissar You might consider tackling this...

**Comment by blazebissar** [comment]
Looks interesting, I'll give it a shot.

**Comment by lkatalin** [comment]
@npmccallum I think this was de-duplicated some PRs back, though I am not sure which PR. Should we close the issue?

**Comment by npmccallum** [comment]
This is fixed in https://github.com/enarx/enarx-keepldr/commit/62249d240d4eeab3a91428be7ab0fe9edf7b69fe .
