### ISSUE TITLE
Containerize Github Actions' runner application

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#435]
Github Actions' runner application is not well-suited for ephemeral use. It's meant to be kept running on a server 24/7, listening for new jobs and running them. When the application is down, the runner as a whole is unreachable.

We'd like to make this less of a problem by containerizing it. This would allow us to deploy the same "runner" even when the underlying hardware is wiped and reprovisioned.

[This repo](https://github.com/myoung34/docker-github-actions-runner) might be a good starting point.

**Comment by platten** [comment]
Complete.
