### ISSUE TITLE
Make enarx.io DNS work

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#437]
This is necessary for both our packet.com servers as well as other resources like the website.

**Comment by axelsimon** [comment]
The DNS will soon be transferred over to the Linux Foundation (cf. #291). Can you be more specific, in what way does the enarx.io domain need to work? If i understand correctly, we want a subdomain of enarx.io to point to the packet.com servers, and the bare domain to point to Github to make use of Github pages.

We should probably decide on the subdomain we want to use for the Packet.com machines however :)

DNS configuration is currently as follows:
```
$ dig enarx.io
(…)
;; QUESTION SECTION:
;enarx.io.                      IN      A

;; ANSWER SECTION:
enarx.io.               300     IN      A       185.199.109.153
enarx.io.               300     IN      A       185.199.108.153
enarx.io.               300     IN      A       185.199.110.153
enarx.io.               300     IN      A       185.199.111.153

;; AUTHORITY SECTION:
enarx.io.               86400   IN      NS      ns4.redhat.com.
enarx.io.               86400   IN      NS      ns2.redhat.com.
enarx.io.               86400   IN      NS      ns3.redhat.com.
enarx.io.               86400   IN      NS      ns1.redhat.com.

;; ADDITIONAL SECTION:
ns1.redhat.com.         3270    IN      A       209.132.186.218
ns2.redhat.com.         3270    IN      A       209.132.183.2
ns3.redhat.com.         3270    IN      A       66.187.233.212
ns4.redhat.com.         3600    IN      A       209.132.188.218
```

and

```
$ dig -t MX enarx.io
(…)
;; QUESTION SECTION:
;enarx.io.                      IN      MX

;; ANSWER SECTION:
enarx.io.               300     IN      MX      20 mx2.redhat.com.
enarx.io.               300     IN      MX      10 mx1.redhat.com.
```

**Comment by npmccallum** [comment]
I see our task list as:
1. Get enarx.io transferred
2. Get DNS we have access to
3. Set up DNS for our packet.com servers

**Comment by axelsimon** [comment]
Here is our current DNS zone:
```
$TTL 300
@               IN      SOA     ns1.redhat.com. hostmaster.redhat.com. (
                                        2020051500   ; Serial
                                        1800         ; Refresh
                                        180          ; Retry
                                        604800       ; Expire
                                        300          ; TTL
                                        )

                        IN      NS      ns1.redhat.com.
                        IN      NS      ns2.redhat.com.
                        IN      NS  ns3.redhat.com.
                        IN      NS  ns4.redhat.com.

                        IN      TXT    "v=spf1 -all"

                        IN  MX  10  mx1.redhat.com.
                        IN  MX  20  mx2.redhat.com.

@              IN     A   185.199.108.153
               IN     A   185.199.109.153
               IN     A   185.199.110.153
               IN     A   185.199.111.153

chat  3600     IN     CNAME  cdms.rocket.chat.
;;;
;; EOF
;;;
```

The apex `A` records are for our use of Github pages. I'm checking with the Linux Foundation if they supporte `ANAME` or `ALIAS` or not, which would be neater alternatives.

Otherwise, all we need to do here is add the right records for the Packet machines destined to be reachable at `dev.enarx.io` and i think the LF IT folks will do the rest.

**Comment by axelsimon** [comment]
As part of our migration to LF, i have given then the above DNS zone for the inital onboarding.

What DNS records do we want for our Packet machines? I should be able to make the request for these DNS record updates very soon now (ie: today or tomorrow, i expect).

**Comment by npmccallum** [comment]
@axelsimon 

```
coffeelake.sgx.dev.enarx.io   147.75.68.177
rome.sev.dev.enarx.io         147.75.68.181
```

**Comment by axelsimon** [comment]
Just picked up that these are `lab.enarx.io`, i though we were going with `dev.enarx.io`.
In any case, i've made the request LF-side, for `enarx.io` and `.dev`.

**Comment by npmccallum** [comment]
> Just picked up that these are `lab.enarx.io`, i though we were going with `dev.enarx.io`.
> In any case, i've made the request LF-side, for `enarx.io` and `.dev`.

I suggested the change to `lab` because `dev.enarx.dev` seemed redundant.

**Comment by axelsimon** [comment]
Thanks for the explanation Nathaniel.

```
$ dig +short rome.sev.lab.enarx.io
147.75.68.181
```

```
dig +short  coffeelake.sgx.lab.enarx.io
147.75.68.177
```

🌈🎉
Closing this issue now :)
