### ISSUE TITLE
Open Networking & Edge Summit North America 2020 (ONES, formerly Open Networking Summit)

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#44]
**Dates**
- CFP closes: 23:59 PST, Monday 3 February 2020
- CFP results: ?
- Event: 20-21 April 2020

**Location**
Los Angeles, CA 

**CFP**
https://events.linuxfoundation.org/open-networking-edge-summit-north-america/program/cfp

**Comment by mbestavros** [comment]
Closed due to missing CFP deadline.
