### ISSUE TITLE
Merge intel-types into x86_64

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#442]
@haraldh brought this up. Most of these types probably belong in x86_64 so we don't have to maintain them.

**Comment by npmccallum** [comment]
@lkatalin FYI

**Comment by lkatalin** [comment]
@npmccallum We don't have the `intel-types` crate anymore. Is this done?

**Comment by npmccallum** [comment]
Yes. Most of `intel-types` is here https://github.com/enarx/xsave
