### ISSUE TITLE
Move Build struct from 'sev' into 'sev-types'

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#446]
Right now it lives in [`sev/src/lib.rs`](https://github.com/enarx/enarx/blob/master/sev/src/lib.rs#L19) but it belongs in the `sev-types` crate.

Move it to the `sev-types` crate.

**Comment by CyberEpsilon** [comment]
Im in!

**Comment by connorkuehl** [comment]
> Im in!

Sorry, @CyberEpsilon! This issue's spoken for, but you got the other 2!
