### ISSUE TITLE
.automation/add-to-project-when-labeled throws an IndexError

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#448]
I've been making a few issues this morning and noticed that GitHub was yelling at me for failed automation runs.

I've been creating issues, labeling them, and manually putting them in the SEV project before clicking "Submit new issue"

Here's a run that GitHub sent me: https://github.com/enarx/enarx/runs/623246553?check_suite_focus=true

```bash
Run .automation/add-to-project-when-labeled *** $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
  .automation/add-to-project-when-labeled *** $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
  shell: sh -e {0}
Traceback (most recent call last):
  File ".automation/add-to-project-when-labeled", line 41, in <module>
    project = [p for p in repo.get_projects() if p.name == LABEL_PROJECTS[label_name]][1]
IndexError: list index out of range
##[error]Process completed with exit code 1.
```

**Comment by connorkuehl** [comment]
@mbestavros This issue never made it onto the Triage lane, but I have not seen it lately so I think it is resolved.

**Comment by mbestavros** [comment]
Yes, I fixed this last Friday. Should have linked to it, but thanks for closing it.

**Comment by npmccallum** [comment]
@mbestavros Please link it now by adding the commit hash.

**Comment by mbestavros** [comment]
@npmccallum Done in above comment.
