### ISSUE TITLE
Mentorship request for Mike Dombrowski

### ISSUE THREAD

**Issue by m-dombrowski** [enarx/enarx#475]
**About**
I'm a small business owner with a background in physical security, investigations, threat assessments, and audits all through the lens of industrial espionage and security architecture. I am enrolled to retrain in network security and pen testing via the (US) VET TEC intensive study program during the last half of 2020.

**Skills**
I am migrating from a physical and personnel security background to infosec and cybersecurity. I've got a few years of basic Linux sysadmin experience as a result of building my small business on Linux production systems. I would rate my sysadmin competency conservatively at entry level or about 2 out of 10. I've dabbled in Python, Bash, Powershell, and Rust but make no claim of competency. My coming VET TEC retraining will provide an intensive study of languages pertinent to pen testing.

**Interest areas**
I'm interested in the overall project and value its core security objective. I don't know where I would best contribute now but I can produce various types of documentation for target audiences with some technical guidance. I recognize the possibility of additional contributions as my skills evolve through 2020 and beyond.

I gladly accept mentorship, suggestions, and direction on how to constructively contribute to the project. My commitment to project contributions would be long term assuming the project folks determine I am a good fit.

Best regards,
Mike Dombrowski

**Comment by axelsimon** [comment]
Hi @m-dombrowski and thanks a lot for your request.

We'v had the opportunity to talk on the enarx [chat](chat.enarx.io), but it makes sense to put down here the result of some of these conversations.

The best way to get started is to go through the documentation and look at what you find helpful, what you don't, what you think is missing. As a someone completely new to the project, your fresh perspective on the documentation is very useful! We've already started making some [changes](https://github.com/enarx/enarx/wiki/How-to-contribute) thanks to you.

Going into more specific documentation, we have a [`documentation` label](https://github.com/enarx/enarx/labels/documentation) to find all documentation-related issues, and we have #221 in particular regarding the improvement of the TEE vulnerabilities and attacks page, for which we have a meeting today and which you are joining.

One more thing that is a good start, especially as you are still discovering the depth of the project and its possible implications is to try and keep Enarx in mind when you encounter a security / trust problem and wonder how could Enarx help with it. Anything you find can be an interesting use case, and writing those down and then building them up together sounds like another very valuable thing you can do!

Thanks again for offering your help!

**Comment by m-dombrowski** [comment]
Thanks @axelsimon !

I'm enjoying this opportunity to serve and contribute. It is certainly an interesting project. If I can improve and better contribute, please let me know. I welcome your feedback.
