### ISSUE TITLE
Mentorship request for Kevin Pouget

### ISSUE THREAD

**Issue by kpouget** [enarx/enarx#476]
**About**

I worked for the University of Grenoble several years (PhD+Postdoc), studying how to improve interactive debugging for multicore&embedded programming, then joined a small company to work on various topics around virtualization. In RedHat since 1 year, I worked on an in-depth benchmarking of SPICE video streaming pipeline. I'm now looking for a new project to work on, and Enarx project tickles my interest!

**Skills**

**a) programming with multiple actors**
  - SPICE benchmarking (7 processes involved)
  - mediated passthrough for a GPU driver (host&guest linux drivers + qemu)
  - OpenCL API Remoting (VM/host remote calls)

**b) low level programming (system libraries/kernel/hypervisor)**
  - mediated passthrough (Linux drivers, Qemu virtual devices)
  - OpenCL API Remoting (vm/contain/host IPC or virtio communication)
  - Qemu live&incremental memory checkpointing (page-fault tracking, live copy-to-disk of the RAM)

**c) programming tools for debugging and performance analysis**
* everything above at some point

**Interest areas**

The syscall propagation of the VM-based keep definitely interests me, with the different aspects of the communication between the WASI, the μKernel and the host kernel.
The discussion about the debugging traces vs confidentiality also sounds interesting.

**Comment by npmccallum** [comment]
Hi Kevin! Thanks for your request. Someone will be following up shortly (might be Monday). In the meantime, take a look at our [getting started page](https://github.com/enarx/enarx/wiki/How-to-contribute). Our development is very rapid at this point, so if you find anything there out of date, please let us know.

**Comment by haraldh** [comment]
Hi Kevin!
Great to have you here! Sounds like you have more VM experience than I have, so I am looking forward working with you.

Have a nice weekend! I'll get back to you on Monday.

**Comment by kpouget** [comment]
Hello Harald, thanks for accepting the mentorship!

Today I read the [Enarx Syscall Proxy](https://github.com/enarx/enarx/wiki/Enarx-Syscall-Proxy) wiki page, and I see very interesting work ahead ... but I wonder what's the current state of the different components? 
I've just see this [milestone announcement](https://aliceevebob.com/2020/04/28/an-enarx-milestone-binaries/), and it seems that things are actually running already, great :D

I understand that what I'm (particularly) interested in is the AMD-SEV side, is it possible to run it without an AMD processor, for the dev & early testing?

**Comment by haraldh** [comment]
> Hello Harald, thanks for accepting the mentorship!
> 
> Today I read the [Enarx Syscall Proxy](https://github.com/enarx/enarx/wiki/Enarx-Syscall-Proxy) wiki page, and I see very interesting work ahead ... but I wonder what's the current state of the different components?

Current design discussion is here: https://github.com/enarx/enarx/pull/416
Although there was a decision on videoconf, to go with the register struct for now.

> I understand that what I'm (particularly) interested in is the AMD-SEV side, is it possible to run it without an AMD processor, for the dev & early testing?

Yes, we haven't switched on AMD-SEV yet. So currently it's all testable on every kvm CPU.

**Comment by haraldh** [comment]
If you switch to the `demo2020` branch, there is the `enarx-keep-sev-shim` directory... including a `README.md`. This is a draft of what will be landing as PRs in the next weeks on the main branch.
Expect a lot of cleanups.
https://github.com/enarx/enarx/tree/demo2020/enarx-keep-sev-shim

**Comment by haraldh** [comment]
@kpouget pinged you in RH google chat
