### ISSUE TITLE
Upstream a default 'cargo make deny' task

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#485]
`cargo-make` offers a number of [really helpful builtin tasks](https://github.com/sagiegurari/cargo-make/blob/master/src/lib/descriptor/makefiles/rust.toml) that can be overridden or extended.

Try to upstream the [`deny`](https://github.com/enarx/enarx/blob/master/Makefile.toml#L29) task which is used to enforce licensing of crates.

**Comment by platten** [comment]
No longer applicable.
