### ISSUE TITLE
Port the Makefile in docs/ to use 'cargo-make'

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#487]
I think off the top of my head the preference would be for these tasks to be defined in the root `Makefile.toml` to keep things simple.

The `misc-diagrams` test script will need to be updated accordingly if it is not outright superceded by the `cargo-make' task that results from this issue.

**Comment by squidboylan** [comment]
I can look into this later today

**Comment by squidboylan** [comment]
Looks like cargo-make might not support the `%` pattern stuff seen at https://github.com/enarx/enarx/blob/master/docs/Makefile#L10 . I briefly looked at the docs and repo and couldnt find anything about it. I'll have to look for an alternative solution
