### ISSUE TITLE
Remove nolibc crate

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#500]
The `nolibc` crate emerged because we needed `libc` constants and types in a `no_std` environment. However, our previous workspace setup made it impossible to link against the `libc` crate (since all features were coalesced across all subprojects). This has now been fixed in #420.

We should remove the `nolibc` crate and replace it with the upstream `libc` crate using `no_std`.

**Comment by blazebissar** [comment]
Sounds like a good next step, I'll take it.
