### ISSUE TITLE
DNS: chat.enarx.io

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#504]
We want a general chat.enarx.io subdomain which we can easily send people to.

Record should be a CNAME pointing to enarx.rocket.chat.

**Comment by grealish** [comment]
Looks like it's expired, why not use the discord develop-ecosystem server? 

> This Workspace has Expired
> This Workspace has expired and scheduled for deletion. If this is in error please contact: cloud.support@rocket.chat and include the URL of your workspace.

**Comment by axelsimon** [comment]
The workspace has been reinstated, we are waiting on changes at the DNS level (or the transfer of the overall domain + DNS to the Linux Foundation, whichever can happen first).

Regarding Discord, it was eliminated from the list of options early on. If you'd like to know more about the reasoning behind our change of chat system, you can read [RFC 00000](https://github.com/enarx/rfcs/tree/master/features/00000-migrate-enarx-public-chat) :)

**Comment by axelsimon** [comment]
Changes have been pushed:
```
$ dig chat.enarx.io

; <<>> DiG 9.11.14-RedHat-9.11.14-2.fc30 <<>> chat.enarx.io

<snip>

;; QUESTION SECTION:
;chat.enarx.io.			IN	A

;; ANSWER SECTION:
chat.enarx.io.		3557	IN	CNAME	enarx.rocket.chat.
enarx.rocket.chat.	1757	IN	A	35.171.99.94
enarx.rocket.chat.	1757	IN	A	3.93.108.170
enarx.rocket.chat.	1757	IN	A	50.16.88.73
```

However, we now have a TLS error, as the enarx.rocket.chat certificate is a Rocket Chat cert only valid for *.rocket. chat.

**Comment by npmccallum** [comment]
@axelsimon Unfortunately, the changes are incorrect. See: https://desk.rocket.chat/portal/kb/articles/how-can-i-set-up-a-custom-domain

**Comment by axelsimon** [comment]
The correct CNAME is now in place:

**Comment by axelsimon** [comment]
Closing this, as it complete.
