### ISSUE TITLE
Improve "How to contribute: documentation" page

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#505]
The newly created [page](https://github.com/enarx/enarx/wiki/How-to-contribute-documentation) is still very light on details and needs improvements. Opening this issue to track them (and encourage others to suggest improvements too).

Add the following to the page:
- (how to) create a github account
- guide to using (github-flavoured) markdown
- guide to editing a github wiki

**Comment by m-dombrowski** [comment]
To complement the guide, we may consider resource links such as:
https://opensource.guide/how-to-contribute/
https://guides.github.com/features/mastering-markdown/ (thanks for that one @axelsimon )

It may be worthwhile to integrate resources in a logical order that complements the mentorship process. Aspiring contributors are usually enthusiastic to engage immediately upon contact. Having a "waiting, but not idle" set of training or study opportunities available will encourage immediate volunteer engagement thereby preventing loss of interest during those critical first few days. It could also help establish contributor expectations and norms for the project moving forward (eg know this, understand that...). Brought together, these aspects of on-boarding will provide added cohesion and hopefully streamline the process.

Having said that, it may be more organized and logical to provide this information on a dedicated mentorship Wiki page. It would probably come down to whether this information would be best on contribution specific pages or a condensed one-stop shop for orientation.

**Comment by axelsimon** [comment]
Agreed with this, this is the path i have in mind:
- potential contributor arrives on "[how to contribute](https://github.com/enarx/enarx/wiki/How-to-contribute)"
- they read the basics, find the best way to contribute for them
- follow the "waiting, but not idle" steps that @m-dombrowski mentioned, which i see as follows:
  - learning about how to contribute to open source in general
  - markdown
  - creating a Github account
  - connecting to the chat
  - understanding how issues work
  - join meetings / board review
- finally, at this point, they should be all ready to go and contribute code, RFCs, bug reporting, etc.

Clearly, the "waiting, but not idle" steps are not compulsory, many people will already know how to do some or all of those things.

Lastly, i agree with the fact that these steps should all be on a secondary page, maybe "How to contribute: getting started" or "How to contribute: basics".

**Comment by axelsimon** [comment]
I've made quite a few changes to the How to contribute page and created a [How to contribute: getting started](https://github.com/enarx/enarx/wiki/How-to-contribute:-getting-started) page which follows the path laid out above.

Hopefully it will help newcomers find a way. Any feedback on this much apprecieated (@m-dombrowski, @CyberEpsilon, @jyotsna-penumaka ?).

**Comment by mbestavros** [comment]
@axelsimon considers this done; closing.
