### ISSUE TITLE
Test for merge commits on incoming pull requests

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#51]
We'd like Enarx to maintain a clean commit history. We have soft guidelines around logical commits and commit etiquette, but we can directly test incoming PRs to ensure they do not have merge commits. We should implement such a test in Travis.

**Comment by mbestavros** [comment]
Currently having trouble getting this command to work:

`git rev-list origin/master.. | xargs -n1 -I{} sh -c '! git rev-parse {}^2 || exit 255'`

`rev-list` seems to be behaving differently on Travis compared to local. @npmccallum wants to take this on, so I'm reassigning to him.

**Comment by dpal** [comment]
Is this still relevant? Should we close it?
