### ISSUE TITLE
Consolidate 'sev' crates

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#518]
Supersedes: #280 
Obsoletes: #281 
Obsoletes: #113 
Obsoletes: #480 
Affects: #180 
Affects: #112 
Affects: #447 

We are no longer fighting against limitations imposed by the cargo workspace which was one of the motivating factors for decomposing these larger crates into smaller ones. Since this is no longer the case, we can simplify the project structure by consolidating the smaller pieces into 'sev'.

**Comment by connorkuehl** [comment]
@whitebrandy FYI: this means our PRs no longer need to put their functionality into an `iocuddle-sev` crate, they will indeed live in the `sev` crate... sorry for the back-and-forth... this is a design decision we landed on today. SGX is taking a similar approach with consolidating their crates.

**Comment by whitebrandy** [comment]
> @whitebrandy FYI: this means our PRs no longer need to put their functionality into an `iocuddle-sev` crate, they will indeed live in the `sev` crate... sorry for the back-and-forth... this is a design decision we landed on today. SGX is taking a similar approach with consolidating their crates.

@connorkuehl Thanks! What does this mean for #180 ? Do I simply wait for this PR to close and base the ketuvim changes on top ?

**Comment by connorkuehl** [comment]
> Thanks! What does this mean for #180 ? Do I simply wait for this PR to close and base the ketuvim changes on top ?

I don't think there's any reason to wait. Off the top of my head I was thinking of making a submodule of `linux.rs` called `ioctl` and adding the Ioctls there. Something like this:

```
sev/src/firmware
├── linux
│   ├── ioctl.rs
│   └── mod.rs
└── mod.rs
```

**Comment by whitebrandy** [comment]
@connorkuehl Alright, I took a stab at this and redid the old PR: https://github.com/enarx/enarx/pull/290. Please take a look when you can!

Also, I see CI failing when initializing containers with a 500 error), do you know what that means ?
