### ISSUE TITLE
Consolidate sgx crates

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#519]
We should consolidate the following crates:

- [x] rename sgx-types => sgx
- [x] merge sgx-crypto => sgx
- [x] merge iocuddle-sgx => sgx
- [x] merge attestation-types => sgx
- [ ] ~~merge intel-types => upstream x86_64 as outlined in #442~~

SEV crates are undergoing similar change, detailed here: #518 

Edit: This would allow us to easily merge the `testing` crate into the remaining `sgx` crate as detailed in #592 .

EDIT: As discussed during planning, upstreaming `intel-types` into `x86_64` will be treated as a separate issue #442, while this one will pertain mainly consolidates the crates in the workspace.

**Comment by kubkon** [comment]
Unless somebody is already working on this, I'm keen to do this to have a poke around different crates here and there.

**Comment by npmccallum** [comment]
@kubkon Note that there is also a `Builder` structure in `enarx-keep-sgx` that we probably want to make the public interface of the `sgx` crate. That is, we probably don't want to expose the ioctls directly. We probably want a higher level interface.

**Comment by kubkon** [comment]
> @kubkon Note that there is also a `Builder` structure in `enarx-keep-sgx` that we probably want to make the public interface of the `sgx` crate. That is, we probably don't want to expose the ioctls directly. We probably want a higher level interface.

Thanks for the heads up! If you don't mind, I'd like to split this effort between a handful of PRs. In the first one, I'd focus on merging the relevant crates together, and afterwards, I'd move on to exposing the `Builder` structure. Does that make sense?
