### ISSUE TITLE
sevctl: status - unreadable char

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#525]
```console
$ cargo run -q -- verify
PDH EP384 D256 a19ef679477f2256d802ce9054ee6d1145dbeed52998c66ea97499a01d977c54
 ⮤ PEK EP384 E256 a37b51038cbaec1062f7b5f93e8caa55cc7798b1a813c26fae1cabc96320fa0a
   •⮤ OCA EP384 E256 deae2d45b8d1456c94b514fba0e6f6fb9f13afc9df9ba9670e9c9e9e54b4af6e
    ⮤ CEK EP384 E256 ce2cba2df8808d188f445192418e008ecf9bd1464db35ea64afa3b3b6966396c
       ⮤ ASK R4096 R256 1f668d63e0a7cb120a41bfb1bcefca715564a187305237f058f6e62c3d4ba5b0
         •⮤ ARK R4096 R256 ae2456af6c6ad234badd6c75e58915be61568286766083853bf668e6e23977c3
```

I haven't found a font, which displays `⮤` correctly.. 

https://github.com/enarx/enarx/blob/d9d5c24f2ebc802b906c210193935bed4edf82cc/sevctl/src/main.rs#L288

**Comment by ueno** [comment]
According to `fc-list :charset=2BA4`, the following fonts seem to have the coverage:
```console
/usr/share/fonts/vlgothic/VL-Gothic-Regular.ttf: VL Gothic,VL ゴシック:style=regular
/usr/share/fonts/gdouros-symbola/Symbola.ttf: Symbola:style=Regular
```

**Comment by haraldh** [comment]
* vlgothic-fonts: is in group `@Fonts` but marked optional
* gdouros-symbola-fonts: is in group `@Fonts` but marked optional

**Comment by haraldh** [comment]
hmm... still no clue, what the `•` means here in this context

**Comment by haraldh** [comment]
@connorkuehl , @npmccallum even if we only have linux machines, there are people using other OSes to ssh into those machines, so we should probably care about the default MacOS fonts.

**Comment by npmccallum** [comment]
@haraldh ACK. Patches welcome.
