### ISSUE TITLE
Produce an RPM package of 'sevctl' for Fedora

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#535]
Effectively moving https://github.com/enarx/sevctl/issues/16 to here since `sevctl` lives here now.

- [x] Push a sevctl release to crates.io and tag it on the GitHub repository
- [ ] Update `sevctl.spec` to download the tagged release from GitHub
- [x] Upload `sevctl` package into the Enarx copr repo (for now)
- [x] Package `sevctl` properly in Fedora Rawhide
- [ ] Commit the .spec file in an Enarx repo

**Comment by connorkuehl** [comment]
@haraldh @npmccallum FYI I've moved this issue here.

Just some background for Harald since this may be the first he's heard of it: the TL;DR is that I'm placing this in your guys' capable hands as Fedora proven packagers. The reasoning here is that once it's packaged the approval process into Fedora will be much smoother/quicker since you guys already know what you're doing.

**Comment by haraldh** [comment]
who will own and maintain the package?

**Comment by connorkuehl** [comment]
> who will own and maintain the package?

Unfortunately we don't have any downstream presence, so it would probably have to be us.

**Comment by haraldh** [comment]
Hmm, I really don't need more bugzilla reports...

**Comment by connorkuehl** [comment]
Soon-to-be available in F34 repos.
Already available in Rawhide.
