### ISSUE TITLE
Enarx chat: allow Github authentication

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#544]
Chat.enarx.io now points to our Rocket Chat instance (don't login by email account at this point, please).
We now want to enable two things on this instance
- authenticate using Github credentials
- open up unsigned (anonymous) chat

@npmccallum is currently the only admin on the Rocket Chat instance, so he'll likely have to make @mbestavros or myself admins to help out.

**Comment by axelsimon** [comment]
Github auth now enabled, please try it!

On my first attempt, i got the following error:
> 504 Gateway - Time-out

But second attempt worked fine.

Another small thing to fix: the welcome message reads:
> deploying WebAssembly applications into Trusted **Exeuction** Environments

**Comment by mbestavros** [comment]
Our chat instance now supports Github auth, so this should be done!
