### ISSUE TITLE
Test Signature generation

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#55]
Make sure all fields of Signature struct are the same as those produced by selftests in https://github.com/jsakkine-intel/linux-sgx/tree/master/tools/testing/selftests/x86/sgx. 

Specifically, dump bytes and retrieve: rsa key, sigstruct file, bytes submitted to hasher. `make` in selftest directory above will generate these structures. 

Goal: produce same SIGSTRUCT as selftest.

**Comment by mbestavros** [comment]
Fixed in #33.
