### ISSUE TITLE
libunwind warning when built against musl-libc

### ISSUE THREAD

**Issue by ueno** [enarx/enarx#558]
When keep-runtime is linked against musl-libc, it prints the following warning at run time:
```console
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
```
We should research and fix the issue.

**Comment by MikeCamel** [comment]
There is an associated issue in github/libunwind/libunwind: https://github.com/libunwind/libunwind/issues/138

It was filed on 2019-11-19 and has been untouched since then.  I've added a comment on it.

**Comment by ueno** [comment]
I think this comes from:
https://github.com/llvm/llvm-project/blob/master/libunwind/src/DwarfParser.hpp#L172

That means that a DWARF FDE (Frame Description Entry) is corrupted as the ID is set to zero. As I can reproduce it with wasmtime compiled with `cargo build --target x86_64-unknown-linux-musl`, I'll open an issue against wasmtime.
