### ISSUE TITLE
keep-runtime: avoid syscalls on /dev/null

### ISSUE THREAD

**Issue by ueno** [enarx/enarx#559]
When running under strace, keep-runtime opens `/dev/null` and issues the `fcntl` and `ioctl`:
```console
open("/dev/null", O_RDWR|O_CLOEXEC)     = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(0x1, 0x3), ...}) = 0
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(0x1, 0x3), ...}) = 0
ioctl(3, TIOCGWINSZ, 0x7ffd7c78d698)    = -1 ENOTTY (Inappropriate ioctl for device)
fcntl(3, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
```
We should investigate the cause and define a plan to remove them.

**Comment by ueno** [comment]
This seems to be because we don't associate stdin/stdout/stderr to anything. Then `wasi-common` internally [opens `/dev/null`](https://github.com/bytecodealliance/wasmtime/blob/master/crates/wasi-common/src/sys/unix/osother.rs#L30) and redirect any input/output to it. There are [`WasiCtxBuilder.stdin`](https://docs.rs/wasi-common/0.16.0/wasi_common/struct.WasiCtxBuilder.html#method.stdin) etc. to override the behavior but those currently take a `File` argument.

I guess one solution to this would be to modify `wasi-common` and implement the loopback I/O behavior without relying on the host.

**Comment by npmccallum** [comment]
@ueno interesting. Are we able to write to an internal ring buffer rather than a fine descriptor?
