### ISSUE TITLE
Simplify Vendor/Author in sgx-types

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#565]
The [Vendor](https://github.com/enarx/enarx/blob/master/sgx-types/src/sig.rs#L16) and [Author](https://github.com/enarx/enarx/blob/master/sgx-types/src/sig.rs#L50) types are probably over-complicated given [this new information](https://lkml.org/lkml/2020/5/20/1398). We should simplify this. We might even just consider removing `Vendor` altogether and just enforcing `0`.

@lkatalin FYI

**Comment by lkatalin** [comment]
Good to know; that field didn't make much sense.

**Comment by lkatalin** [comment]
@jyotsna-penumaka Based on the [link](https://lkml.org/lkml/2020/5/20/1398) above, the [Vendor struct](https://github.com/enarx/enarx/blob/master/sgx-types/src/sig.rs#L16) should be replaced with `0u32` wherever we are using it. 

It may also be a good idea to take [header1](https://github.com/enarx/enarx/blob/master/sgx-types/src/sig.rs#L33) and [header2](https://github.com/enarx/enarx/blob/master/sgx-types/src/sig.rs#L36) and use them in a constructor for `Author` (separate from `Vendor`, which wouldn't exist any more as a type).

@npmccallum Did you have anything additional in mind for this?

**Comment by npmccallum** [comment]
Other than removing the `Vendor` type altogether, not really.

**Comment by jyotsna-penumaka** [comment]
Thank you @lkatalin and @npmccallum
