### ISSUE TITLE
Record more interviews, with new community members

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#575]
We'd like to add more team interviews to the current collection (cf. #175).

New community members, @m-dombrowski, @CyberEpsilon, would you be up for this?

We would record over Bluejeans, as we did for the original batch, and we'd prepare by having a conversation before about the questions etc.

Tagging as "documentation" as we don't have an "outreach" label and i'm not sure i want to create one, for now.

**Comment by m-dombrowski** [comment]
Yes, I would be glad to provide an interview. If the questions are predetermined, I would appreciate receiving them via direct message in advance.

**Comment by CyberEpsilon** [comment]
Apologies for the late response. Yes, I'd be interested in doing an interview.

**Comment by axelsimon** [comment]
Sorry for the slow reply, the easiest is probably to watch one of the interviews to see what we are talking about : https://www.youtube.com/watch?v=TOQmY41uzII
The questions would be the same, unless we decide to change them together (which is entirely an option too).

**Comment by npmccallum** [comment]
Since this issue has no deliverable, we're closing it. In the future, create one issue per person so there is a clear deliverable.
