### ISSUE TITLE
Investigate possible issues with .io TLD

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#576]
It appears draw.io has [moved to diagrams.net](https://www.diagrams.net/blog/move-diagrams-net) for reasons to do with issues with the .io Top Level Domain name.

We (/i) should investigate this as we are using enarx.io and issue a recommendation to the team.

**Comment by axelsimon** [comment]
So here is some background:
- https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/ (6 year-old article)
- http://domainincite.com/18181-start-ups-protest-the-dark-side-of-io (5 year-old article)

There are several issues at play here.

### Ethical issue
First of all, there is an ethical problem. It is not recent, although i was sadly unaware about the problematic history of the .io and, more generally, of the British Indian Ocean Territories it represents, as the Giagom article mentioned above is from 2014.

The short version of the problem is summarised by the website that was set up to .io-using organisations to act: http://www.thedarksideof.io/
> .io is the TLD for the [Chagos Archipelago](http://en.wikipedia.org/wiki/Chagos_Archipelago).
50 years ago, the UK Government [deported](http://en.wikipedia.org/wiki/Depopulation_of_Chagossians_from_the_Chagos_Archipelago) all Chagossians.
They lost all rights to their homeland, now including the [valuable](https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/) .io TLD.
To this day, the Chagossians [continue](http://www.chagossupport.org.uk/) their fight for the right to return. 

### Future of .io issue
Then there is the problem of the possible disappearance of the .io ccTLD.

In this [article](http://domainincite.com/23957-un-ruling-may-put-io-domains-at-risk) from Feb 2019, we learn that the ICJ (International Court of Justice) ruled that "the United Kingdom is under an obligation to bring to an end its administration of the Chagos Archipelago as rapidly as possible”, which could *possibly* mean an end of the British Indian Territory, and as such of the .io ccTLD that represents it. It's not clear it will happen, however, given 1/ .io's huge popularity and 2/ .su's continued existence, since the Soviet Union's end in 1991.

### DNS security issue
Lastly, and possibly of most immediate concern to a security project like ours, is [this story](https://thehackerblog.com/the-io-error-taking-control-of-all-io-domains-with-a-targeted-registration/) of how a security researcher was able to take control of 4 out of 7 of .io's root DNS servers, in 2017. It is mentioned by draw.io/diagrams.net as their reason to retire their .io domain: loss of trust in the seriousness of how .io is managed.

### What should we do?
For the ethical problem, making a donation matching the renewal fee seems both straightforward and reasonable.

For the future of the .io ccTLD, i must say i'm not too worried, so i'd put that one aside.

For the security issue, i am more worried, especially as we are likely to want to use our domain name as some sort of root of trust for distribution of Enarx components, once we start releasing.

@MikeCamel, @npmccallum, everyone, what do you think?

**Comment by axelsimon** [comment]
Quick but important update: the `enarx.dev` domain has been acquired for us by the LF.

**Comment by axelsimon** [comment]
Although @npmccallum  added enarx.dev to the Github Pages CNAME config [yesterday](https://github.com/enarx/enarx.github.io/commit/da42e68185a9dd1c1bc53307d18604fe6952d718), it doesn't seem to work.
I'm now doubting that one can have more than one line in that file, as i've not seen anything to make me think that's possible in the documentation.

**Comment by npmccallum** [comment]
We are mostly moved to `enarx.dev`. Closing.
