### ISSUE TITLE
Verify Rome ARK and ASK correctness

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#581]
#509 and #546 introduce the Rome ARK and ASK certificates, respectively.

However, `sevctl verify` output suggests the ARK is not self-signed and that the ARK does not sign the ASK. Both of those entries are colored red.

`sevctl verify` works correctly for Naples.

**Comment by haraldh** [comment]
https://github.com/AMDESE/sev-tool/blob/7e58d94867806617c9eb84bd8332e590afdbf3ee/src/amdcert.cpp#L136-L146

Note the difference in the sha calculation:
