### ISSUE TITLE
Allow reporting of the capabilities granted a Wasm workload

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#583]
**Description**
Some functionality within WASI contexts are constrained by capabilities, which need to be granted.  For example, in order to access a particular part of the filesystem, the workload needs to be granted that capabilty.  The same is expected for sockets, networking, etc..  One of the things we expect to wish to do is grant different capabilities to different workloads within a Keep - particularly if we're running multiple Wasm packages in the same Keep.  In order to do this, we'll need to know which capabilities have been granted in each Keep.  We may also wish to:

1. change capabilities at runtime
1. log capabilities
1. log attempts to access capabilities which aren't allowed
1. react to attempts to access capabilities with actions (blocking, allowing, panicking)
1. doubly enforce capability management with lower level restrictions (a la SELinux)?

I'm investigating whether such accounting is currently available within wasmtime: it may not yet have been proposed.

**Comment by platten** [comment]
Not applicable as we will be declaring the required capabilities as part of the deployment policy.
