### ISSUE TITLE
Apply SGX v32 patches to the Enarx kernel

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#585]
These have been rebased to 5.7, so depending on the backporting involved it may or may not be feasible to apply these to our Fedora 32-based kernel which is based on 5.6. Some backporting may be involved.

**Comment by npmccallum** [comment]
@connorkuehl FYI: https://koji.fedoraproject.org/koji/packageinfo?packageID=8

Rawhide has 5.7 and 5.8 already. At some point, F32 will have 5.7 too.

**Comment by npmccallum** [comment]
Also, this issue is for v31. However, v32 is already out.

**Comment by connorkuehl** [comment]
> Also, this issue is for v31. However, v32 is already out.

Thanks! That was a mistake on my part. Fixed.

**Comment by connorkuehl** [comment]
Only minor offset adjustments were required to apply SGX revision 32 onto a 5.6-based kernel.

Build successful: https://copr.fedorainfracloud.org/coprs/npmccallum/enarx/build/1465691/

Closing.
