### ISSUE TITLE
Merge `testing` crate into other SGX crate(s)

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#592]
There isn't much in that crate, so a separate crate for this probably isn't needed. The macro from `testing` is used mainly (but not only) in `sgx-types`, which I believe is also going to get merged into another crate eventually. This will reduce unnecessary directories and also help to avoid confusion since we're creating the new `tests/` crate for general testing (of SGX payload, syscalls, etc.).

**Comment by ziyi-yan** [comment]
Currently, `testing` is used by `sgx-types`, `intel-types`, and `attestation-types`. If we merge that code into multiple crates that means we copy-and-paste the same code three times, which is not a good way to organize codes in my opinion. We could rename `testing` to `test_util` if we need to avoid confusion.

**Comment by lkatalin** [comment]
@ziyi-yan This is a good point. Our broader idea is to merge some of those crates you named together as well. For example, we have issue #442 open, which would get rid of  `intel-types` as a separate crate by merging into upstream `x86_64`, and similarly #519 outlines merging `attestation-types` into the same upstream `x86_64`. We should do a slightly better job of clarifying how all of these issues fit together (though it looks like the overarching plan is in #519 ).
