### ISSUE TITLE
Achieve static linking with rust and gcc

### ISSUE THREAD

**Issue by steveeJ** [enarx/enarx#6]
There is [a thread on the rust users forum](https://users.rust-lang.org/t/statically-link-executable-with-glibc) which discusses this topic.
All examples I've seen online to link statically with rust rely on the musl libc.

**Comment by haraldh** [comment]
hmm.. as mentioned in the thread:

> (to be clear: it is unsafe to ship these executables to systems that don't have exactly the same glibc, as glibc will be dynamically loading nss modules internally and there might be ABI conflicts, even silent crashy ones, although this likely only matters if you do DNS lookups)

**Comment by haraldh** [comment]
Seems like this would require musl-gcc on Fedora/RHEL, too
There is no way around it, because openssl-sys compiles .c files

https://github.com/sfackler/rust-openssl/tree/master/openssl-sys/build

**Comment by haraldh** [comment]
@npmccallum 

If we would choose glibc we would run into some problems:
```
$ cat hello.c
#include <stdio.h>
#include <stdlib.h>
#include <openssl/ssl.h>

int main(void)
{
        OpenSSL_add_ssl_algorithms();
        printf("Hello World!\n");
        return 0;
}
$ gcc -static hello.c -lssl -lcrypto -lz -ldl -Wl,--whole-archive -lpthread -Wl,--no-whole-archive
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libcrypto.a(fips.o): in function `verify_checksums':
(.text+0x516): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libcrypto.a(b_addr.o): in function `BIO_lookup_ex':
(.text+0xd02): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
(.text+0x75): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

* because of `pthread` we need special linking arguments because of the `weak` symbols.
`-Wl,--whole-archive -lpthread -Wl,--no-whole-archive`
* for `getaddrinfo` and `gethostbyname` glibc uses `dlopen()` for the nss modules.
* seems like libcrypto wants to use dlopen(), too

glibc might have a failure path, if dlopen() failts. I don't know

**Comment by haraldh** [comment]
Also, we can't link the static libs generated by gcc with glibc with musl libc. So, the openssl-static on fedora doesn't help here. It would have to be recompiled with `musl-gcc`.

**Comment by haraldh** [comment]
Also https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/developing_applications_in_rhel_8/using-libraries-with-gcc_creating-c-or-c-applications#static-and-dynamic-linking_using-libraries-with-gcc
