### ISSUE TITLE
Open Source Summit North America 2020

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#60]
There's also Embedded Linux Conference at the same time/place, but it seems less obvious a conference for Enarx.

**Dates**
- CFP opens: 17 December 2019
- CFP closes: 23:59pm PST on Sunday 16 February 2020
- CFP results: Monday 23 March 2020
- Slides Due Date: Monday 15 June 2020
- Event: 22-24 June 2020

**Location**
W Marriott Austin, Texas, USA

**CFP**
https://events.linuxfoundation.org/open-source-summit-north-america/program/cfp/

**Comment by MikeCamel** [comment]
Title:
Running sensitive workloads on untrusted hosts: Project Enarx 

Presenters:
Mike Bursell & Nathaniel McCallum

Abstract:
There are many sensitive workloads that you shouldn't entrust to a public cloud to run, or may even have concerns about running on on-premises systems. Trusted Execution Environments (TEEs) such as Intel's SGX and AMD's SEV provide a great opportunity to help secure these workloads, but they're not easy to use.

Enarx is a project which aims to make it simple to deploy workloads to a variety of different TEE technologies in the cloud, on premises or elsewhere, whilst ensuring that your application workload is as secure as possible. It is written in Rust, and provides a WebAssembly (WASI) runtime. This session will outline the various parts of the sensitive workload deployment problem and how Enarx is architected to solve them, including attestation, a key pain point when considering deployment on TEEs. It will also include a demo of the current state of Enarx and talk about opportunities for involvement in the project.

Enarx is a fully open source project, under the Apache 2.0 license, and a part of the Confidential Computing Consortium, a Linux Foundation community project.

Differences from previous version:
- new code, architecture, demo
- accent on open source & ecosystem
