### ISSUE TITLE
Mentorship request for Nishant Mishra

### ISSUE THREAD

**Issue by nishant0078** [enarx/enarx#625]
**About**
Hi I am Nishant Mishra Age 24 an IT Graduate with Interest in Open Source Technologies , I read Mike's Article and found out about this Project. I am an avid Travel Enthusiast and Photographer and a Technology Enthusiast too...

**Skills**
C, C++ and Networking . Have programmed an Android pp as part of College Internship. I have 0 experience in devlopment but my prior experience has been of 6 months in Microsoft Office 365 Technical Support in Wipro Limited.
**Interest areas**
I would like to contribute to the Code of the Project.

**Comment by connorkuehl** [comment]
Hi @nishant0078! It is always exciting for us to see a newcomer that is interested in Enarx. 

> I have 0 experience in devlopment

We've all been here :slightly_smiling_face:. Just speaking from my own experience: it can be very frustrating to ramp up on a project without first being familiar with the programming language it uses (Rust). Furthermore, based on what you've mentioned about your development experience, I would also like to emphasize the importance of being familiar with version control software (we, like many other projects, use `git`). It is a critical skill to have for collaborating with others.

Before diving into Enarx, I'd suggest building a foundation for your development skills first. It will ultimately result in a better experience with contributing code to Enarx.

These are some of my favorite resources for learning Git and Rust:

* [The Book](https://doc.rust-lang.org/book/) & [other official resources](https://www.rust-lang.org/learn)
* [Programming Rust](https://www.oreilly.com/library/view/programming-rust/9781491927274/) - This book is not free, but I've been reading through it and I like it very much.
* [Pro Git 2nd Edition](https://git-scm.com/book/en/v2) - You can get very far with `git` by just reading Chapters 2, 3, and 5.
* Once you've got the basics of Git, a good skill to develop is how to create atomic commits. These might also appear in search results as "logical commits".

I hope this helps.

Best regards,

Connor
