### ISSUE TITLE
Document usage of enarx.io's hosted SGX/SEV dev boxes

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#626]
With #437 handed off to the LF, we now have SGX and SEV dev boxes available via SSH.

We should document how to use these for development, as well as how to request access for new users and register their SSH key.

**Comment by axelsimon** [comment]
initial version: https://github.com/enarx/enarx/wiki/How-to-use-the-lab-machines

**Comment by axelsimon** [comment]
Looks like we are good with this for now, closing the issue.
