### ISSUE TITLE
Mentorship request for Ziyi Yan

### ISSUE THREAD

**Issue by ziyi-yan** [enarx/enarx#628]
**About**
Tell us a bit about yourself! How did you find the project? What's your favorite IT Crowd episode? etc.

I am working as a backend software engineer for about two years after I graduated from university. Recently, I want to find a project for me to get my hands dirty in new technologies and I found Enarx innovative and exciting. I learned something about WASM and WASI from RustConf videos and then found out wasmtime/cranelift projects and [Bytecode Alliance](https://bytecodealliance.org/). And, I saw Enarx at bytecodealliance.org website.

**Skills**
Tell us a bit about your background: what skills you have, relevant prior
experience, etc. Don't copy-paste your entire resume -- this is not an
interview! We just need enough to get the ball rolling.

I learned C/C++, Java in the university. After that, I also learned Python, JavaScript, Node.js, and Go by myself for projects in students' tech group. I had project experience in web development and network programming in Node.js and Go. This year, I learned Rust and started to contribute open-source projects, such as [TiKV](http://tikv.org).

**Interest areas**
Are there any particular parts of the project you would like to contribute to?

I would like to contribute to wasm runtime and cloud-native ecosystem integration parts. But I don't mind starting with other components or any easier tasks for me to get started and gain the whole pictures of the project.

I really love the openness of the way you guys doing this project and I'm looking forward to joining the community and have fun. :smile:

**Comment by connorkuehl** [comment]
Hi, @ziyi-yan! :wave: 

> I would like to contribute to wasm runtime and cloud-native ecosystem integration parts. But I don't mind starting with other components or any easier tasks for me to get started and gain the whole pictures of the project.

This is exactly the subsystem we'd love to get some help on. A lot of our attention has been focused on lower-level components but we have @ueno and @MikeCamel who have been making headway in the Wasm-layer.

We have a [stand-up Monday-Friday](https://github.com/enarx/enarx/wiki/How-to-contribute#meetings) (barring some rare exceptions) and each day focuses on an Enarx subsystem. Thursdays are our WebAssembly days. These meetings are 100% open to everyone and are a great opportunity to learn more about what's happening day-to-day with the Enarx project. Feel free to attend if your schedule allows. :slightly_smiling_face:

Thanks again for your earlier PRs!

**Comment by MikeCamel** [comment]
@ziyi-yan - I'm very happy to work with you as a mentor, if you'd like.  What timezone are you on, btw?

**Comment by ziyi-yan** [comment]
@MikeCamel Hi, Mike! I'm happy to work with you too! I on UTC+8 and I have joined the chat using the same name as my GitHub username.
