### ISSUE TITLE
CI: also build with `--release`

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#635]
**Description**
In CI also build with `--release` to catch something like https://github.com/enarx/enarx/pull/634

**Comment by connorkuehl** [comment]
Our core repos now have a testing matrix that will test in both debug and release with varying combinations of feature flags if applicable.

* [enarx-keepldr](https://github.com/enarx/enarx-keepldr/blob/master/.github/workflows/test.yml#L39)
* [enarx-wasmldr](https://github.com/enarx/enarx-wasmldr/blob/master/.github/workflows/test.yml#L28)
* [sev](https://github.com/enarx/sev/blob/master/.github/workflows/test.yml#L25)
* [sgx](https://github.com/enarx/sgx/blob/master/.github/workflows/test.yml#L29)
