### ISSUE TITLE
Update Rocket.Chat config for enarx.dev

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#637]
Currently, chat.enarx.dev throws an error, as the Rocket.Chat backend is not configured for that domain.
We need to configure that. As far as i know, only @npmccallum has the rights to do that.
There is no emergency here, however.

**Comment by npmccallum** [comment]
Rocket.Chat configuration has been updated, with no advance notice. This means that `chat.enarx.io` is broken but `chat.enarx.dev` is working. @axelsimon Please have `chat.enarx.io` redirect to `chat.enarx.dev`. Thanks!

**Comment by axelsimon** [comment]
Redirection active:
```bash
$ curl -LI chat.enarx.io
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: http://chat.enarx.dev
X-Redirector-Version: 2.9.1-e845328
Date: Wed, 22 Jul 2020 15:10:00 GMT
Connection: close

HTTP/1.1 307 Temporary Redirect
Location: https://chat.enarx.dev:443/
Date: Wed, 22 Jul 2020 15:10:01 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8

HTTP/2 200 
content-type: text/html; charset=utf-8
date: Wed, 22 Jul 2020 15:10:01 GMT
set-cookie: _bbf1e=http://10.42.15.236:3000; Path=/
vary: Accept-Encoding
x-instance-id: hcYTMukrLrtBqvkfM
x-xss-protection: 1
```

Our move to enarx.dev is now complete, i believe. Closing this issue!
