### ISSUE TITLE
Mentorship request for Adam Baxter

### ISSUE THREAD

**Issue by ambaxter** [enarx/enarx#640]
**About**
Hello! I'm a Software Consultant and have worked with a number of Fortune 100 companies over my tenure at Red Hat. This project was suggested to me as something I might be interested in. 

In my free time I help moderate a Stoicism Discord channel and am teaching myself the art of cheese making.

**Skills**
The vast majority of my day-to-day is working on either JDK8 web microservices or Drools rules (business rules/expert system). 

I am, however, mostly excited about Rust.

My GH repo is https://github.com/ambaxter and you can see my glorious project graveyard and what I'm currently working on.

I've created the better part of a rules engine (expert-rs, metis-rs), but at this point it's not an end to end product. I'm working on language parsing and a virtual machine right now.

I've worked a bit on Redox when it first came out, but for a variety of reasons I stopped contributing.

I created a number of minor libraries, (R*, R+ Spatial tree algorithms, a compile time sized port of bit-set and bit-array), and did some work on a Rust wrapper for libsolv though I didn't get too far due to time constraints. 

**Interest areas**
Are there any particular parts of the project you would like to contribute to?

Attestation sounds interesting, but I'm willing to pick up any small tasks that help me get my feet wet.

**Comment by npmccallum** [comment]
@ambaxter Welcome! I'll be your mentor.

Generally our mentorship program shepherds a new contributor through their first contribution. However, considering as you've already got two maybe we want to do something different?

What can I help you with?

**Comment by ambaxter** [comment]
I'm OK with generic Rust development. I think a good next step is for some relatively easy work that's a bit more project specific. Something I can work on and get feedback relatively easily for.
