### ISSUE TITLE
Run the 'audit' cargo-make task as part of our CI flow

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#645]
When we switched to `cargo-make` I thought the `audit` target was part of the `ci-flow` target. I haven't seen any `cargo audit` output in any of the logs I've been reading from our CI runs or locally when running `ci-flow`.

This task is built into `cargo-make`. Add it to the `pre-ci-flow` step.

**Comment by platten** [comment]
We no longer use `cargo-make` and this is no longer applicable.
