### ISSUE TITLE
'misc-diagrams' test is not ran during ci-flow

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#646]
**To reproduce:**

1. Modify a diagram source file and commit your change:

```diff
diff --git a/docs/attestation/amd/sev/certchain.dot b/docs/attestation/amd/sev/certchain.dot
index 743c182..895064d 100644
--- a/docs/attestation/amd/sev/certchain.dot
+++ b/docs/attestation/amd/sev/certchain.dot
@@ -10,5 +10,5 @@ digraph G {
     ASK -> CEK;
     CEK -> PEK;
     PEK -> PDH;
-    OCA -> PEK;
+    OCA -> CEK;
 }
```

2. Run `cargo make pre-ci-flow`

**Expected result:**

CI fails with message "This diagram is out-of-date: ./docs/attestation/amd/sev/certchain.dot.png. Please generate an updated diagram and commit it to include it with your pull request."

**Actual result:**

CI succeeds without error message, and any mention of `misc-diagrams` just says that it was skipped.

```bash
$ cargo make pre-ci-flow 2>&1 | grep misc-diagrams
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams 
[cargo-make][1] INFO - Skipping Task: misc-diagrams
```

**Comment by sagiegurari** [comment]
there is a condition on that task: 
```toml
condition = { env_not_set = ["CARGO_MAKE_CRATE_NAME"]}
```
so if this was skipped, it means that env var is set.
there are no other conditions.

**Comment by ambaxter** [comment]
@sagiegurari I took a few minutes to look at what the build process is trying to accomplish. I think the goal is to have misc-diagrams be run _once_ during the pre-ci-flow. However, since the pre-ci-flow runs for each crate the script would be run for each crate which isn't the ideal.

**Comment by sagiegurari** [comment]
ya, so you should split it the same way you split the integration tests if i remember correctly.
so that task would run only on the workspace level (if i understood the requirement correctly).
i think that the PR fixes this. but could be wrong

**Comment by ambaxter** [comment]
It doesn't. It doesn't execute at a workspace level, but still executes at a crate level

**Comment by ambaxter** [comment]
I'll try to play with it a bit more later today.

**Comment by ambaxter** [comment]
Ok, I get it. misc-diagrams is workspace only if called directly, but not as part of the pre-ci-flow.
