### ISSUE TITLE
enarx-keep-sgx-shim: stdio fd inspection

### ISSUE THREAD

**Issue by ueno** [enarx/enarx#661]
If stdio is inherited in wasmtime, `wasi-common` examines stdio fds (0, 1, 2) to check the rights:
```console
$ strace ./target/debug/wasmtime tests/wasm/hello_wasi_snapshot1.wat
...
statx(0, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_BASIC_STATS, stx_attributes=0, stx_mode=S_IFCHR|0620, stx_size=0, ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
fcntl(0, F_GETFL)                       = 0x2 (flags O_RDWR)
```
Currently I'm patching `wasi-common` to use a fixed value, but it would be nice if the shim provides a stub implementation for those syscalls when called against stdio fds.

**Comment by npmccallum** [comment]
@ueno Ultimately, we don't want stdio going to the host. But since we have no persistent storage, we also have no way to log it locally.

Here's my proposal. We make a ring buffer and log stdout/stderr into it. Next, we have remote methods for reading the buffer and writing to stdin. Thoughts?

@MikeCamel @haraldh @connorkuehl @whitebrandy @lkatalin @jyotsna-penumaka @mbestavros

**Comment by MikeCamel** [comment]
Rather than consider the host _ever_ to be a fitting recipient of debug, an alternative would seem to be create a Socket at level above, and output there. If we keep this outside of the TEE, we can multi-threaded, so this is OK.  Are we confident that we have a stable enough connection up to the layer above that this is plausible?

**Comment by haraldh** [comment]
We could also make the log forward perfect secrecy safe like the systemd journal, so it is tamper proof.

**Comment by haraldh** [comment]
I also assume the ring buffer lives in the keep.

**Comment by haraldh** [comment]
So, because the log cannot live in the keep, if you want the logs post-mortem, I suggest we at least encrypt them somehow, so only the owner can read them.

**Comment by MikeCamel** [comment]
I guess this is a question of whether we plan to extend use of this logging beyond _our_ debugging to allow logging for running Keeps.  If so, then we need an encryption key: we can establish that as part of our attestation steps (it's not currently explicitly called out, but we have a session-key (see [https://github.com/enarx/enarx/pull/632](https://github.com/enarx/enarx/pull/632) for more details), so it's not difficult.  If not, then we probably don't care as much about confidentiality.  

Maybe we need an RFC on debugging and logging?

**Comment by ueno** [comment]
IMO, no matter how stdio (or a generic logging facility) is implemented, I guess we would need a way to override stdio in a more flexible manner. Currently, the wasi-common API can only inherit stdio from the host, or redirect from/to a given `File` argument.

The options I can think of are:
1. implement `statx`, `ioctl(TCGETS)`, and `fcntl` in the shim for known file descriptors, or
2. extend the wasi-common API to take a virtual stream or explicit capabilities as an argument

@kubkon any thoughts?

**Comment by kubkon** [comment]
@ueno option 2 should be achievable with the current state of the API, i.e., `wasi-common` should accept virtual file as a valid stdio handle: [WasiCtxBuilder::stdout](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasi-common/src/ctx.rs#L257) (or at least that was my aim when refactoring the API a while back). In fact, any struct that inherits from `Handle` trait should do here. If `wasi_common::virtualfs::InMemoryFile` is not sufficient for our purposes, we can define our own struct and implement `Handle` trait. Either way, I'm happy to provide assistance with either.

**Comment by ueno** [comment]
@kubkon, that's good to know, thank you for the pointer! I was looking at the 0.18.0 documentation ;-)

**Comment by ueno** [comment]
It seems that the scope of this issue is diverged over time. While it is not ideal, I'd propose the following minimal feature:
- keep-runtime provides an option (or a predefined value) of a preopened FD
- it connects both stdin/stdout to the FD through [virtfs::pipe](https://docs.rs/wasi-common/0.19.1/wasi_common/virtfs/pipe/index.html)

The data sent over this FD is not encrypted, but it might be sufficient for services like [tang](https://github.com/latchset/tang), though it would need `listen`, `accept`, and connection based activation to make such services fully functional.
