### ISSUE TITLE
Network framework analysis

### ISSUE THREAD

**Issue by ambaxter** [enarx/enarx#665]
**Description**
Create simple test harness system for testing each of the network frameworks for the following datapoints:

- Syscall count
- Syscall time
- Memory consumption
- Binary size (already completed)

Strace or perf will likely be used. 

The harness will start the server via the tracing application, preferably with a delay as to when tracing begins. After the delay, the harness will connect and send dummy data request. Client will collect the trace results, format their output, then shut down the server.

I am concerned with how best to interpret the microbenchmark results.

Client tracking:
- [ ] tcp
- [ ] tcp-tokio
- [ ] tcp-tokio-rustls
- [ ] tcp-tokio-native-tls
- [ ] http-warp-rustls
- [ ] http-rocket-rustls
- [ ] jsonrpc-http
- [ ] jsonrpc-tcp
- [ ] cborrpc-rustls

**Comment by npmccallum** [comment]
@ambaxter Status?

**Comment by ambaxter** [comment]
@npmccallum I was told we would be focusing on http-warp-rustls. Unless something has changed this should be closed

**Comment by npmccallum** [comment]
ACK
