### ISSUE TITLE
Payload should detect whether it's running in a TEE

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#671]
The payload should be able to detect whether it is running in an SGX or SEV TEE and begin the attestation process accordingly. It should issue a syscall with a new number (not one of [these](http://blog.rchapman.org/posts/Linux_System_Call_Table_for_x86_64/)) and the shim(s) should process this syscall by returning the correct variant of an `enum`, ex. `TEE::SGX`. If the payload is not running in a TEE, this new syscall will return `ENOSYS` via [here](https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/event.rs#L65).

TODO:
- [ ] Add new environment variable `KEEP=sgx` [here](https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/entry.rs#L39).
- [ ] Implement a payload test that reads the environment variable

**Comment by lkatalin** [comment]
@jyotsna-penumaka See above, avoid working on the shared library first. A new payload test will issue the new syscall, which will be processed in the SGX shim `event.rs` and `handler.rs`. 

@npmccallum I'm understanding `0` means the new syscall was successful and `!0` in `rax` indicates running in a TEE - is that correct?

**Comment by npmccallum** [comment]
I have a better idea! We will inject that we are running in a TEE in an auxiliary vector.

**Comment by npmccallum** [comment]
https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/entry.rs#L58

**Comment by npmccallum** [comment]
Nope, even better: an environment variable.

**Comment by npmccallum** [comment]
`TEE=sgx`

**Comment by npmccallum** [comment]
This is a one line patch to here -- https://github.com/enarx/enarx/blob/master/enarx-keep-sgx-shim/src/entry.rs#L39

But we need a test for it.

**Comment by jyotsna-penumaka** [comment]
so the function sets the environment variable?

**Comment by npmccallum** [comment]
Nope. No more function at all. The initial variables are set at the link above.

**Comment by jyotsna-penumaka** [comment]
Oh got it!

**Comment by npmccallum** [comment]
@jyotsna-penumaka You will probably want to implement a syscall test for `write()` first. Then your test for this feature will simply read the environment variable and write its value to standard out.

**Comment by jyotsna-penumaka** [comment]
Yeah that would make more sense
I will fix my exit syscall test first and then I will move to write syscall test.

**Comment by lkatalin** [comment]
@npmccallum Is this done since `enarx-keep` detects the correct backend?

**Comment by npmccallum** [comment]
No, but I have a different plan. So let's close this.
