### ISSUE TITLE
Enarx build failed on Fedora 32

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#673]
HW: Intel NUC
SW&OS: Fedora 32
Source code: https://github.com/enarx/enarx.git

Steps:
1. set up Enarx development environment according to wiki: https://github.com/enarx/enarx/wiki/How-to-contribute-code#enarx-development-environment-set-up
2. git clone git clone https://github.com/enarx/enarx.git and cd it
3. cargo make build

Error message is as below:

......
error: failed to run custom build command for `openssl-sys v0.9.55 (https://github.com/npmccallum/rust-openssl?branch=patch#1173c09f)`

Caused by:
  process didn't exit successfully: `/home/sgx/enarx/enarx/enarx-keep-sgx/target/debug/build/openssl-sys-55ec77b8633aca63/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running "perl" "./Configure" "--prefix=/home/sgx/enarx/enarx/enarx-keep-sgx/target/debug/build/openssl-sys-173cd1db75fa7080/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64"
Configuring OpenSSL version 1.1.1g (0x1010107fL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
running "make" "depend"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/sgx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.1+1.1.1g/src/lib.rs:389:22
stack backtrace:
   0:     0x5569e480eb54 - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5569e480eb54 - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5569e480eb54 - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5569e480eb54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5569e483675c - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5569e480b443 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x5569e4812f85 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5569e4812f85 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5569e4812f85 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x5569e4812cc2 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x5569e48135e2 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:511
  11:     0x5569e48131cb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x5569e4835b41 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  13:     0x5569e4835963 - core::option::expect_none_failed::hb01994a49b20448c
                               at src/libcore/option.rs:1268
  14:     0x5569e478b6ab - core::result::Result<T,E>::unwrap::hd78cfd0bd6baf7f3
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/result.rs:1005
  15:     0x5569e4787f0f - openssl_src::Build::run_command::hc7aace74ed1a2c95
                               at /home/sgx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.1+1.1.1g/src/lib.rs:389
  16:     0x5569e4787187 - openssl_src::Build::build::heed24a4475174cd4
                               at /home/sgx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.1+1.1.1g/src/lib.rs:349
  17:     0x5569e4750ac5 - build_script_main::find_vendored::get_openssl::hd91f0c66d0efd8bd
                               at /home/sgx/.cargo/git/checkouts/rust-openssl-3ac8ecaf6f2ca476/1173c09/openssl-sys/build/find_vendored.rs:5
  18:     0x5569e474349b - build_script_main::find_openssl::h6ec9af67c4a6bfae
                               at /home/sgx/.cargo/git/checkouts/rust-openssl-3ac8ecaf6f2ca476/1173c09/openssl-sys/build/main.rs:50
  19:     0x5569e47435ad - build_script_main::main::hefc84024f804083f
                               at /home/sgx/.cargo/git/checkouts/rust-openssl-3ac8ecaf6f2ca476/1173c09/openssl-sys/build/main.rs:61
  20:     0x5569e4747d3b - std::rt::lang_start::{{closure}}::h84ef3d9eb980a931
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:67
  21:     0x5569e4813a28 - std::rt::lang_start_internal::{{closure}}::h44dc84346eeba462
                               at src/libstd/rt.rs:52
  22:     0x5569e4813a28 - std::panicking::try::do_call::h3559ee6be71549e2
                               at src/libstd/panicking.rs:331
  23:     0x5569e4813a28 - std::panicking::try::h78f4c77016541848
                               at src/libstd/panicking.rs:274
  24:     0x5569e4813a28 - std::panic::catch_unwind::hfe46f382761b3d41
                               at src/libstd/panic.rs:394
  25:     0x5569e4813a28 - std::rt::lang_start_internal::he05790f0cb2000df
                               at src/libstd/rt.rs:51
  26:     0x5569e4747d17 - std::rt::lang_start::he8dbbaeacc0dd25a
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:67
  27:     0x5569e4746e7a - main
  28:     0x7fe7ee9b1042 - __libc_start_main
  29:     0x5569e473e21e - _start
  30:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
......

**Comment by connorkuehl** [comment]
Hi @xiaonan-INTC!

My first thought in reading this stack trace is that openssl might be missing on your system.

1. What Enarx commit do you have checked out? (`git log -1 --format="%H"`)
2. What is the output of: `rpm -q openssl-devel musl-devel musl-libc-static musl-gcc musl-clang`
3. What is the output of: `rustup target list | grep "x86_64-unknown-linux-musl (installed)"`

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC!
> 
> My first thought in reading this stack trace is that openssl might be missing on your system.
> 
> 1. What Enarx commit do you have checked out? (`git log -1 --format="%H"`)
> 2. What is the output of: `rpm -q openssl-devel musl-devel musl-libc-static musl-gcc musl-clang`
> 3. What is the output of: `rustup target list | grep "x86_64-unknown-linux-musl (installed)"`

@connorkuehl 

Dear connorkuehl, thanks very much for your help, I have succeeded in build Enarx source code with above errors disappeared, :)

**Comment by connorkuehl** [comment]
Happy to hear it! :slightly_smiling_face:

**Comment by xiaonan-INTC** [comment]
> Happy to hear it! 🙂

This issue re-occurred, I think maybe some others meet it too?
Following https://github.com/enarx/enarx/wiki/How-to-contribute-code to install openssl-devel, musl, rust(cargo), 
then do $cargo make build, error would be like this:


   Compiling openssl-sys v0.9.55 (https://github.com/npmccallum/rust-openssl?branch=patch#1173c09f)
   Compiling heck v0.3.1
   Compiling clap v2.33.1
   Compiling intel-types v0.1.0 (/home/sgx/enarx/intel-types)
   Compiling quote v1.0.7
   Compiling mmap v0.1.0 (/home/sgx/enarx/mmap)
error: failed to run custom build command for `openssl-sys v0.9.55 (https://github.com/npmccallum/rust-openssl?branch=patch#1173c09f)`

Caused by:
  process didn't exit successfully: `/home/sgx/enarx/enarx-keep-sgx/target/debug/build/openssl-sys-b8382c071e22d417/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running "perl" "./Configure" "--prefix=/home/sgx/enarx/enarx-keep-sgx/target/debug/build/openssl-sys-e539853b298d9241/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64"
Configuring OpenSSL version 1.1.1g (0x1010107fL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
running "make" "depend"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/sgx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.2+1.1.1g/src/lib.rs:408:22
stack backtrace:
   0:     0x55e5f4e76e25 - backtrace::backtrace::libunwind::trace::h396c07d2071b43af
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55e5f4e76e25 - backtrace::backtrace::trace_unsynchronized::h7aa0e4bb23d9c158
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55e5f4e76e25 - std::sys_common::backtrace::_print_fmt::hd15ac5d4adcd355b
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55e5f4e76e25 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec5354be8ccc3ecc
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55e5f4e9e05c - core::fmt::write::h3d34909eeb4f225b
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55e5f4e735c3 - std::io::Write::write_fmt::h1da287b3de55ed16
                               at src/libstd/io/mod.rs:1537
   6:     0x55e5f4e7b1e0 - std::sys_common::backtrace::_print::h4d206838e1ace354
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55e5f4e7b1e0 - std::sys_common::backtrace::print::h1f778e9940ee5977
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55e5f4e7b1e0 - std::panicking::default_hook::{{closure}}::h704403a56cbf5783
                               at src/libstd/panicking.rs:198
   9:     0x55e5f4e7af2c - std::panicking::default_hook::ha4567a10dec4ef8d
                               at src/libstd/panicking.rs:218
  10:     0x55e5f4e7b817 - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at src/libstd/panicking.rs:486
  11:     0x55e5f4e7b41b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x55e5f4e9d461 - core::panicking::panic_fmt::hbddb7fe6f399b81a
                               at src/libcore/panicking.rs:101
  13:     0x55e5f4e9d283 - core::option::expect_none_failed::h60849c4323f09783
                               at src/libcore/option.rs:1272
  14:     0x55e5f4dfb1bb - core::result::Result<T,E>::unwrap::h53c8a28ca23f06e3
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/result.rs:1005
  15:     0x55e5f4df65ef - openssl_src::Build::run_command::hc7125e66c409168e
                               at /home/sgx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.2+1.1.1g/src/lib.rs:408
  16:     0x55e5f4df5861 - openssl_src::Build::build::h5358a2dd97365b5d
                               at /home/sgx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.2+1.1.1g/src/lib.rs:368
  17:     0x55e5f4dc29d5 - build_script_main::find_vendored::get_openssl::h74cf6ede9d08059a
                               at /home/sgx/.cargo/git/checkouts/rust-openssl-3ac8ecaf6f2ca476/1173c09/openssl-sys/build/find_vendored.rs:5
  18:     0x55e5f4db645b - build_script_main::find_openssl::he3043bfeb742e8bb
                               at /home/sgx/.cargo/git/checkouts/rust-openssl-3ac8ecaf6f2ca476/1173c09/openssl-sys/build/main.rs:50
  19:     0x55e5f4db656d - build_script_main::main::h92c025713c72ba83
                               at /home/sgx/.cargo/git/checkouts/rust-openssl-3ac8ecaf6f2ca476/1173c09/openssl-sys/build/main.rs:61
  20:     0x55e5f4dc560b - std::rt::lang_start::{{closure}}::h9ebe6a898dceea84
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:67
  21:     0x55e5f4e7bbe8 - std::rt::lang_start_internal::{{closure}}::h6d21eebfa4beaf70
                               at src/libstd/rt.rs:52
  22:     0x55e5f4e7bbe8 - std::panicking::try::do_call::h560a27b87db38b9c
                               at src/libstd/panicking.rs:297
  23:     0x55e5f4e7bbe8 - std::panicking::try::h453d4afd696011f9
                               at src/libstd/panicking.rs:274
  24:     0x55e5f4e7bbe8 - std::panic::catch_unwind::h211d02671f23030f
                               at src/libstd/panic.rs:394
  25:     0x55e5f4e7bbe8 - std::rt::lang_start_internal::h464df2bbf46c7e7c
                               at src/libstd/rt.rs:51
  26:     0x55e5f4dc55e7 - std::rt::lang_start::h6c17f2b66c615042
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:67
  27:     0x55e5f4db9e2a - main
  28:     0x7fc8bf9f8042 - __libc_start_main
  29:     0x55e5f4db121e - _start
  30:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.

**Comment by xiaonan-INTC** [comment]
kernel-5.7.10-200.fc32.enarx.sgx.32.x86_64 also meets this issue.
It is very boring, cannot find solution which blocks the cargo make build for Enarx...
