### ISSUE TITLE
Add a cursor to sallyport Block

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#705]
The cursor contains a method to sequentially allocate chunks of the Block of a specified size; it also contains a pointer to the next allocatable chunk of the Block and and error type passed in at instantiation.

TODO:
- [x] Implement Cursor in sallyport
- [x] Cursor field should not be an `Option`
- [x] `alloc()` should be `unsafe` or initialize the returned array
- [x] Cursor should store an error value to return in case of `alloc()` failure
- [x] `sallyport::Block` should have a function `fn cursor<'a, T>(err: T) -> Cursor<'a, T>` that replaces `Cursor::new()`
- [ ] `Block.buf` should become a private field
- [x] It should have tests

First referenced in comments on #680 and #682 .

**Comment by npmccallum** [comment]
Let's have:
* `unsafe fn alloc<T>(size)` - Allocates an uninitialized array.
* `fn alloc_default<T: Default>(size)` - `Default::default()` for all array items.
* `fn alloc_copy<T: Copy>(size, value: T)` - Copies `value` for all array items.
