### ISSUE TITLE
iocuddle-sgx  test failed on 5.7.7-200.fc32.enarx.sgx.35

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#716]
This failure is similar to https://github.com/enarx/enarx/issues/715
I am not sure if they are the same root cause.

running 10 tests
test test::test::flags_1::perms_2 ... FAILED
test test::test::flags_1::perms_1 ... FAILED
test test::test::flags_1::perms_4 ... FAILED
test test::test::flags_1::perms_5 ... FAILED
test test::test::flags_2::perms_1 ... FAILED
test test::test::flags_1::perms_3 ... FAILED
test test::test::flags_2::perms_2 ... FAILED
test test::test::flags_2::perms_4 ... FAILED
test test::test::flags_2::perms_3 ... FAILED
test test::test::flags_2::perms_5 ... FAILED

failures:

---- test::test::flags_1::perms_2 stdout ----
-------------- TEST START --------------
thread 'test::test::flags_1::perms_2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/lib.rs:165:9
stack backtrace:
   0:     0x55da5ebeb6a4 - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55da5ebeb6a4 - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55da5ebeb6a4 - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55da5ebeb6a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55da5ec13dec - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55da5ea78cc5 - std::io::Write::write_fmt::h56b56792c7d07453
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/io/mod.rs:1504
   6:     0x55da5ebe5c91 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h10302bdfac08fd75
                               at src/libstd/io/impls.rs:156
   7:     0x55da5ebedf75 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x55da5ebedf75 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x55da5ebedf75 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
  10:     0x55da5ebedc5b - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:215
  11:     0x55da5ebee5d2 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:511
  12:     0x55da5ebee1bb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  13:     0x55da5ec12811 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  14:     0x55da5ec12633 - core::option::expect_none_failed::hb01994a49b20448c
                               at src/libcore/option.rs:1268
  15:     0x55da5ea73a9b - core::result::Result<T,E>::unwrap::h1e90b5896f9bd7be
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/result.rs:1005
  16:     0x55da5ea7727a - iocuddle_sgx::test::test::hf153caa09600cb70
                               at src/lib.rs:165
  17:     0x55da5ea74af6 - iocuddle_sgx::test::test::flags_1::perms_2::ha4c95d3688cdbc8e
                               at src/lib.rs:136
  18:     0x55da5ea7772a - iocuddle_sgx::test::test::flags_1::perms_2::{{closure}}::had261d13a2eadd09
                               at src/lib.rs:136
  19:     0x55da5ea761ae - core::ops::function::FnOnce::call_once::hc0c22c9cd200c0a6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  20:     0x55da5eaa0156 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hfa18b27dedffd191
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  21:     0x55da5eaa0156 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hcdf500d264863dfc
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  22:     0x55da5eaa0156 - std::panicking::try::do_call::h9ce8dace81c3cff7
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  23:     0x55da5eaa0156 - std::panicking::try::h0f958fd2e4b932c4
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  24:     0x55da5eaa0156 - std::panic::catch_unwind::hbace0809b8fc0484
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  25:     0x55da5eaa0156 - test::run_test_in_process::hc0677c322c7fffb3
                               at src/libtest/lib.rs:541
  26:     0x55da5eaa0156 - test::run_test::run_test_inner::{{closure}}::h51cd043e42d800e9
                               at src/libtest/lib.rs:450
  27:     0x55da5ea78176 - std::sys_common::backtrace::__rust_begin_short_backtrace::h581d0c005dff3b2a
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys_common/backtrace.rs:130
  28:     0x55da5ea7d495 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hbd32afed4e9d62d2
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:475
  29:     0x55da5ea7d495 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha6bff588e9d98dd1
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  30:     0x55da5ea7d495 - std::panicking::try::do_call::hf5630a82199e9dd0
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  31:     0x55da5ea7d495 - std::panicking::try::hd8315cf5d61c31d8
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  32:     0x55da5ea7d495 - std::panic::catch_unwind::hccddf03ae1944915
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  33:     0x55da5ea7d495 - std::thread::Builder::spawn_unchecked::{{closure}}::h614be43726ca14a8
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:474
  34:     0x55da5ea7d495 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1d6542ef544e3c38
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  35:     0x55da5ebf4dca - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf207c3654ee300a0
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  36:     0x55da5ebf4dca - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h66e0c6190e34816b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  37:     0x55da5ebf4dca - std::sys::unix::thread::Thread::new::thread_start::h30687bc0b1c3cd55
                               at src/libstd/sys/unix/thread.rs:87
  38:     0x7ff07ce77432 - start_thread
  39:     0x7ff07cd8a9d3 - __clone
  40:                0x0 - <unknown>

Detailed log is attached:
[iocuddle-sgx.txt](https://github.com/enarx/enarx/files/4929508/iocuddle-sgx.txt)

**Comment by npmccallum** [comment]
This is almost certainly a permissions issue. Do you have permissions to read `/dev/sgx/enclave`?

**Comment by xiaonan-INTC** [comment]
> This is almost certainly a permissions issue. Do you have permissions to read `/dev/sgx/enclave`?

@npmccallum 
Yes, npmccallum, the permissions is no problem. I suppose it is the same with issue [715](https://github.com/enarx/enarx/issues/715)

**Comment by connorkuehl** [comment]
@xiaonan-INTC Do these tests pass on the latest Enarx kernel: `5.7.8-201.fc32.enarx.sgx.32.x86_64`?

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Do these tests pass on the latest Enarx kernel: `5.7.8-201.fc32.enarx.sgx.32.x86_64`?

No, on 5.7.8-201.fc32.enarx.sgx.32.x86_64 it will get PASS.
But on 5.7.8-201.fc32.enarx.sgx.32.x86_64, issue #734 still exists.

**Comment by connorkuehl** [comment]
Okay, since it sounds like these tests pass for you on the latest kernel I will close this issue.
