### ISSUE TITLE
Load and run a Linux ELF binary inside a VM that calls SYS_exit

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#72]
This is done when we can load and run a toy static Linux ELF binary inside a VM that does nothing more than call `SYS_exit` with the code in the `enarx/enarx` repo.

**Comment by connorkuehl** [comment]
(Now) duplicate of #309

**Comment by connorkuehl** [comment]
Actually, this issue's main comment does capture an item on our SEV roadmap.
