### ISSUE TITLE
Proposal: use anyhow crate and pass extra context to error messages

### ISSUE THREAD

**Issue by kubkon** [enarx/enarx#726]
**Description**
Currently, from what I gather, we either implement our own `Error` type or throw a `std::io::Error`. In general, I'm a fan of having the least external dependencies as possible and I also like to re-use as much as possible of the `libstd` (in this case, `std::io::Error`). However, in this case, I believe depending on the [`anyhow`](https://github.com/dtolnay/anyhow) crate so that we get additional context info for free might be a good idea.

For example, consider this bit in "enarx-keep-sgx" crate:

```rust
// main.rs
fn load() -> enclave::Enclave {
    // ...
    Builder::new(layout.enclave).expect("Unable to create builder");
}
```

```rust
use anyhow::{Context, Result};

// builder.rs
impl Builder {
    pub fn new(span: impl Into<Span<usize>>) -> Result<Self> {
        // ...
        let mut file = OpenOptions::new()
            .read(true)
            .write(true)
            .open("/dev/sgx/enclave")
            .context("failed to open /dev/sgx/enclave for reading and writing)?;
    }
}
```

This way, if there's a problem with `/dev/sgx/enclave`, the user will receive an error message such as:

```
thread 'main' panicked at 'Unable to create builder: failed to open /dev/sgx/enclave for reading and writing

Caused by:
    File not found (os error 2)
```

instead of a much more cryptic:

```
thread 'main' panicked at 'Unable to create builder: Os { code: 2, kind: FileNotFound, message: "File not found" }', src/main.rs:121:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Lemme know what y'all think!

**Comment by npmccallum** [comment]
Yes. I've been wanting better error handling for a while now. Part of the difficulty is that we have a variety of `no_std` crates, so we just haven't focused on error handling which don't work in that context. But it is probably time to think about this.

Please note that we're also in the middle of merging `enarx-keep-sgx` and `enarx-keep-sev` into the unified `enarx-keep`. So there's some active churn going on. But I'm on board.

**Comment by kubkon** [comment]
> Yes. I've been wanting better error handling for a while now. Part of the difficulty is that we have a variety of `no_std` crates, so we just haven't focused on error handling which don't work in that context. But it is probably time to think about this.

Actually, [`anyhow` compiles under `no_std` setting](https://docs.rs/anyhow/1.0.31/anyhow/#no-std-support). In this case though it is necessary to explicitly map between `Anyhow` and other error types (which otherwise would be automatically facilitated via the `std::error::Error` trait); however, in those cases, I reckon a couple of `From`s should do the trick.

> Please note that we're also in the middle of merging `enarx-keep-sgx` and `enarx-keep-sev` into the unified `enarx-keep`. So there's some active churn going on. But I'm on board.

Thanks for the heads up! I won't touch any of the code until the migration is done then.

**Comment by connorkuehl** [comment]
I also agree that a more consistent error-handling story across our crates would be great, but my only hesitation is that (exaggeration incoming) it seems like the Rust ecosystem has a new favored error handling crate on an almost weekly basis.

**Comment by kubkon** [comment]
> I also agree that a more consistent error-handling story across our crates would be great, but my only hesitation is that (exaggeration incoming) it seems like the Rust ecosystem has a new favored error handling crate on an almost weekly basis.

Yeah, I don't think you're exaggerating at all. Having said that though, I've purposely suggested `anyhow` (and it's sister crate `thiserror`) since this is the crate currently favoured by the Wasmtime and Lucet projects, plus, it's pretty straightforward to use.

**Comment by bstrie** [comment]
After poking around, anyhow is already being used a fair bit in the codebase. At this point it seems like that if there are any places left that could benefit from using anyhow, then it makes sense to just treat that as a casual best-effort refactoring rather than anything that needs to be tracked by a dedicated issue.

> my only hesitation is that (exaggeration incoming) it seems like the Rust ecosystem has a new favored error handling crate on an almost weekly basis

The Error Handling Project Group has made great progress towards integrating the lessons learned from external crates back into std, and I fully expect that these efforts will start filtering into stable this year, with the result of at last standardizing error handling. A taste of the work being done here (all of it with a mindful eye toward facilitating the no_std use case as well):

https://github.com/rust-lang/rfcs/pull/2895

https://github.com/rust-lang/rust/pull/90328

https://github.com/rust-lang/rfcs/pull/3192

https://github.com/rust-lang/rust/pull/91970

https://github.com/yaahc/rust/pull/1
