### ISSUE TITLE
SGX integration test failed on kernel-5.7.7-200.fc32.enarx.sgx.33.x86_64

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#734]
HW: Intel NUC7JY
SW: Fedora kernel-5.7.7-200.fc32.enarx.sgx.33.x86_64, latest Enarx source code

$make cargo integration

Output:
[sgx@localhost enarx]$ cargo make integration
[cargo-make] INFO - cargo make 0.32.0
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: integration
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: integration
[cargo-make] INFO - Running Task: cargo_make_run_fork
[cargo-make] INFO - Execute Command: "cargo" "make" "--disable-check-for-updates" "--no-on-error" "--loglevel=info" "--profile=development" "--allow-private" "--skip-init-end-tasks" "--makefile=/home/sgx/enarx/enarx/Makefile.toml" "integration-test"
[cargo-make][1] INFO - Build File: /home/sgx/enarx/enarx/Makefile.toml
[cargo-make][1] INFO - Task: integration-test
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Running Task: workspace
[cargo-make][2] INFO - Project: integration-tests
[cargo-make][2] INFO - Build File: Makefile.toml
[cargo-make][2] INFO - Task: integration-test
[cargo-make][2] INFO - Profile: development
[cargo-make][2] INFO - Running Task: integration-test
[cargo-make][2] INFO - Execute Command: "cargo" "test"
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/x86_64-unknown-linux-musl/debug/deps/exit_one-b1221fe052a70f69

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/exit_zero-dbc7b208f0b76f00

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/integration_tests-ab84324179520fbe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/watchdog-59f63b709162408c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/syscall_exit-6df05641cea4adec

running 3 tests
test exit_one ... FAILED
test exit_zero ... FAILED
test watchdog ... ok

failures:

---- exit_one stdout ----
thread 'exit_one' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
stack backtrace:
   0:           0x465f44 - backtrace::backtrace::libunwind::trace::h234d741a55b60f88
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:           0x465f44 - backtrace::backtrace::trace_unsynchronized::h350b2c8c65b00d1d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:           0x465f44 - std::sys_common::backtrace::_print_fmt::h4a536ea1c8e8e74a
                               at src/libstd/sys_common/backtrace.rs:78
   3:           0x465f44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had63074188e24509
                               at src/libstd/sys_common/backtrace.rs:59
   4:           0x4a22cc - core::fmt::write::h0f3ca38b916f7bdd
                               at src/libcore/fmt/mod.rs:1069
   5:           0x409e15 - std::io::Write::write_fmt::h0492a51fb8624240
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/io/mod.rs:1504
   6:           0x45ffb1 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h8359eb06f0e4ddf2
                               at src/libstd/io/impls.rs:156
   7:           0x468815 - std::sys_common::backtrace::_print::h5b567d4903ca6eb3
                               at src/libstd/sys_common/backtrace.rs:62
   8:           0x468815 - std::sys_common::backtrace::print::hf98b9b1b18a4dc81
                               at src/libstd/sys_common/backtrace.rs:49
   9:           0x468815 - std::panicking::default_hook::{{closure}}::h5fbf8e21242992f2
                               at src/libstd/panicking.rs:198
  10:           0x4684fb - std::panicking::default_hook::hb4d89e36502020cd
                               at src/libstd/panicking.rs:215
  11:           0x468e72 - std::panicking::rust_panic_with_hook::hc36f90fb81cc1268
                               at src/libstd/panicking.rs:511
  12:           0x447eb1 - std::panicking::begin_panic::h0c3a023adf1fb5d6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:438
  13:           0x406f77 - syscall_exit::common::IntegrationTest::run::h53d276ed8f331740
                               at tests/common/mod.rs:86
  14:           0x401f41 - syscall_exit::exit_one::h6437e59280e3085b
                               at tests/syscall_exit.rs:24
  15:           0x4078ca - syscall_exit::exit_one::{{closure}}::h9819c89e04e73ceb
                               at tests/syscall_exit.rs:23
  16:           0x407b2e - core::ops::function::FnOnce::call_once::h4d37d8dcd6e4a1f9
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  17:           0x4312a6 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h34e14509e8982243
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  18:           0x4312a6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7a0f3692b9cf21e9
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  19:           0x4312a6 - std::panicking::try::do_call::h6b042e109eabd10b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  20:           0x4312a6 - std::panicking::try::he23c7d17e54debd6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  21:           0x4312a6 - std::panic::catch_unwind::hfd0da0b297bc397e
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  22:           0x4312a6 - test::run_test_in_process::hc5d00775b0b23280
                               at src/libtest/lib.rs:541
  23:           0x4312a6 - test::run_test::run_test_inner::{{closure}}::hf19ad6a495a863dd
                               at src/libtest/lib.rs:450
  24:           0x4092c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h52c084346f15b8c1
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys_common/backtrace.rs:130
  25:           0x40e5e5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h4fca3783524d97d4
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:475
  26:           0x40e5e5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4ef6a476bc195a31
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  27:           0x40e5e5 - std::panicking::try::do_call::hf02c604e01de768d
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  28:           0x40e5e5 - std::panicking::try::h3859ed57a08a9683
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  29:           0x40e5e5 - std::panic::catch_unwind::h940c64426ea173b6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  30:           0x40e5e5 - std::thread::Builder::spawn_unchecked::{{closure}}::h634f3e3b3ced0ab1
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:474
  31:           0x40e5e5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0867808dbef17df7
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  32:           0x46f12a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7791eef1c6f45098
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  33:           0x46f12a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd7ef21d55fcbd5c6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  34:           0x46f12a - std::sys::unix::thread::Thread::new::thread_start::he4cd09b6f7a97324
                               at src/libstd/sys/unix/thread.rs:87

---- exit_zero stdout ----
thread 'exit_zero' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
stack backtrace:
   0:           0x465f44 - backtrace::backtrace::libunwind::trace::h234d741a55b60f88
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:           0x465f44 - backtrace::backtrace::trace_unsynchronized::h350b2c8c65b00d1d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:           0x465f44 - std::sys_common::backtrace::_print_fmt::h4a536ea1c8e8e74a
                               at src/libstd/sys_common/backtrace.rs:78
   3:           0x465f44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had63074188e24509
                               at src/libstd/sys_common/backtrace.rs:59
   4:           0x4a22cc - core::fmt::write::h0f3ca38b916f7bdd
                               at src/libcore/fmt/mod.rs:1069
   5:           0x409e15 - std::io::Write::write_fmt::h0492a51fb8624240
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/io/mod.rs:1504
   6:           0x45ffb1 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h8359eb06f0e4ddf2
                               at src/libstd/io/impls.rs:156
   7:           0x468815 - std::sys_common::backtrace::_print::h5b567d4903ca6eb3
                               at src/libstd/sys_common/backtrace.rs:62
   8:           0x468815 - std::sys_common::backtrace::print::hf98b9b1b18a4dc81
                               at src/libstd/sys_common/backtrace.rs:49
   9:           0x468815 - std::panicking::default_hook::{{closure}}::h5fbf8e21242992f2
                               at src/libstd/panicking.rs:198
  10:           0x4684fb - std::panicking::default_hook::hb4d89e36502020cd
                               at src/libstd/panicking.rs:215
  11:           0x468e72 - std::panicking::rust_panic_with_hook::hc36f90fb81cc1268
                               at src/libstd/panicking.rs:511
  12:           0x447eb1 - std::panicking::begin_panic::h0c3a023adf1fb5d6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:438
  13:           0x406f77 - syscall_exit::common::IntegrationTest::run::h53d276ed8f331740
                               at tests/common/mod.rs:86
  14:           0x401ebe - syscall_exit::exit_zero::h47593a1360d1c6ed
                               at tests/syscall_exit.rs:11
  15:           0x40788a - syscall_exit::exit_zero::{{closure}}::h3396bd7e217ccc9c
                               at tests/syscall_exit.rs:10
  16:           0x407b9e - core::ops::function::FnOnce::call_once::heaf3b23be7c0a834
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  17:           0x4312a6 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h34e14509e8982243
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  18:           0x4312a6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7a0f3692b9cf21e9
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  19:           0x4312a6 - std::panicking::try::do_call::h6b042e109eabd10b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  20:           0x4312a6 - std::panicking::try::he23c7d17e54debd6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  21:           0x4312a6 - std::panic::catch_unwind::hfd0da0b297bc397e
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  22:           0x4312a6 - test::run_test_in_process::hc5d00775b0b23280
                               at src/libtest/lib.rs:541
  23:           0x4312a6 - test::run_test::run_test_inner::{{closure}}::hf19ad6a495a863dd
                               at src/libtest/lib.rs:450
  24:           0x4092c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h52c084346f15b8c1
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys_common/backtrace.rs:130
  25:           0x40e5e5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h4fca3783524d97d4
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:475
  26:           0x40e5e5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4ef6a476bc195a31
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  27:           0x40e5e5 - std::panicking::try::do_call::hf02c604e01de768d
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  28:           0x40e5e5 - std::panicking::try::h3859ed57a08a9683
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  29:           0x40e5e5 - std::panic::catch_unwind::h940c64426ea173b6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  30:           0x40e5e5 - std::thread::Builder::spawn_unchecked::{{closure}}::h634f3e3b3ced0ab1
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:474
  31:           0x40e5e5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0867808dbef17df7
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  32:           0x46f12a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7791eef1c6f45098
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  33:           0x46f12a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd7ef21d55fcbd5c6
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  34:           0x46f12a - std::sys::unix::thread::Thread::new::thread_start::he4cd09b6f7a97324
                               at src/libstd/sys/unix/thread.rs:87

failures:
    exit_one
    exit_zero

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test syscall_exit'
[cargo-make][2] ERROR - Error while executing command, exit code: 101
[cargo-make][2] WARN - Build Failed.
[cargo-make][1] ERROR - Error while executing command, exit code: 1
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.

**Comment by xiaonan-INTC** [comment]
**Kernel-5.7.8-201.fc32.enarx.sgx.32** also has this issue.

**Comment by connorkuehl** [comment]
@xiaonan-INTC Thanks for the bug report!

What is the output of `ls -lh /dev/sgx`? I am unable to reproduce this on kernel `5.7.8-201.fc32.enarx.sgx.32.x86_64`, so I'm wondering if it's a permissions issue that's different.

Could you paste the output of:

```
$ cd integration-tests
$ cargo test -- --nocapture
```

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Thanks for the bug report!
> 
> What is the output of `ls -lh /dev/sgx`? I am unable to reproduce this on kernel `5.7.8-201.fc32.enarx.sgx.32.x86_64`, so I'm wondering if it's a permissions issue that's different.
> 
> Could you paste the output of:
> 
> ```
> $ cd integration-tests
> $ cargo test -- --nocapture
> ```

[sgx@localhost ~]$ ls -lh /dev/sgx
total 0
crwxrwxrwx. 1 root root 10, 62 Jul 20 14:01 enclave
crw-------. 1 root root 10, 61 Jul 20 14:01 provision


[sgx@localhost integration-tests]$ cargo test -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/x86_64-unknown-linux-musl/debug/deps/exit_one-b1221fe052a70f69

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Running target/x86_64-unknown-linux-musl/debug/deps/exit_zero-dbc7b208f0b76f00

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/integration_tests-ab84324179520fbe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/watchdog-59f63b709162408c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/syscall_exit-6df05641cea4adec

running 3 tests
test exit_one ... ok
thread 'exit_zero' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test exit_zero ... FAILED
thread 'watchdog' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
test watchdog ... ok

failures:

failures:
    exit_zero

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test syscall_exit'


**I changed the permission as below then re-run the integration test, sometimes 1 FAILURE, sometimes 2 FAILURES**
[sgx@localhost integration-tests]$ sudo chmod 777 /dev/sgx/provision
[sudo] password for sgx:
[sgx@localhost integration-tests]$ ls -l /dev/sgx
total 0
crwxrwxrwx. 1 root root 10, 62 Jul 20 14:01 enclave
crwxrwxrwx. 1 root root 10, 61 Jul 20 14:01 provision



[sgx@localhost integration-tests]$ cargo test -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/x86_64-unknown-linux-musl/debug/deps/exit_one-b1221fe052a70f69

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/exit_zero-dbc7b208f0b76f00

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/integration_tests-ab84324179520fbe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/watchdog-59f63b709162408c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/syscall_exit-6df05641cea4adec

running 3 tests
test exit_zero ... ok
thread 'exit_one' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test exit_one ... FAILED
thread 'watchdog' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
test watchdog ... ok

failures:

failures:
    exit_one

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test syscall_exit'



[sgx@localhost integration-tests]$ cargo test -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/x86_64-unknown-linux-musl/debug/deps/exit_one-b1221fe052a70f69

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/exit_zero-dbc7b208f0b76f00

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/integration_tests-ab84324179520fbe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/watchdog-59f63b709162408c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-musl/debug/deps/syscall_exit-6df05641cea4adec

running 3 tests
thread 'thread 'exit_zeroexit_one' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
' panicked at 'test exit_one ... FAILED
killed by watchdog!', tests/common/mod.rs:86:17
test exit_zero ... FAILED
thread 'watchdog' panicked at 'killed by watchdog!', tests/common/mod.rs:86:17
test watchdog ... ok

failures:

failures:
    exit_one
    exit_zero

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test syscall_exit'

**Comment by connorkuehl** [comment]
@xiaonan-INTC Thanks. Just for comparison, the permissions on our device nodes are:

```
[connorkuehl@coffeelake ~]$ ls -lh /dev/sgx
total 0
crw-rw-rw-. 1 root root 10, 62 Jul 20 05:54 enclave
crw-------. 1 root root 10, 61 Jul 20 05:54 provision

[connorkuehl@coffeelake ~]$ getfacl /dev/sgx
getfacl: Removing leading '/' from absolute path names
# file: dev/sgx
# owner: root
# group: root
user::rwx
group::r-x
other::r-x

[connorkuehl@coffeelake ~]$ getfacl /dev/sgx/enclave 
getfacl: Removing leading '/' from absolute path names
# file: dev/sgx/enclave
# owner: root
# group: root
user::rw-
group::rw-
other::rw-

[connorkuehl@coffeelake ~]$ getfacl /dev/sgx/provision 
getfacl: Removing leading '/' from absolute path names
# file: dev/sgx/provision
# owner: root
# group: root
user::rw-
group::---
other::---
```

Could you try making those match? 

Also, could you paste the output of `uname -a`?

And lastly, could you paste the output of `strace -Te trace=ioctl,open --decode-fds=path --follow-forks cargo make integration`

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Thanks. Just for comparison, the permissions on our device nodes are:
> 
> ```
> [connorkuehl@coffeelake ~]$ ls -lh /dev/sgx
> total 0
> crw-rw-rw-. 1 root root 10, 62 Jul 20 05:54 enclave
> crw-------. 1 root root 10, 61 Jul 20 05:54 provision
> 
> [connorkuehl@coffeelake ~]$ getfacl /dev/sgx
> getfacl: Removing leading '/' from absolute path names
> # file: dev/sgx
> # owner: root
> # group: root
> user::rwx
> group::r-x
> other::r-x
> 
> [connorkuehl@coffeelake ~]$ getfacl /dev/sgx/enclave 
> getfacl: Removing leading '/' from absolute path names
> # file: dev/sgx/enclave
> # owner: root
> # group: root
> user::rw-
> group::rw-
> other::rw-
> 
> [connorkuehl@coffeelake ~]$ getfacl /dev/sgx/provision 
> getfacl: Removing leading '/' from absolute path names
> # file: dev/sgx/provision
> # owner: root
> # group: root
> user::rw-
> group::---
> other::---
> ```
> 
> Could you try making those match?
> 
> Also, could you paste the output of `uname -a`?
> 
> And lastly, could you paste the output of `strace -Te trace=ioctl,open --decode-fds=path --follow-forks cargo make integration`

@connorkuehl 

I had changed all permission to your list.

[sgx@localhost enarx]$ uname -a
Linux localhost.localdomain 5.7.8-201.fc32.enarx.sgx.32.x86_64 #1 SMP Fri Jul 17 21:40:12 UTC 2020 x8                          6_64 x86_64 x86_64 GNU/Linux

[sgx@localhost enarx]$ strace -Te trace=ioctl,open --decode-fds=path --follow-forks cargo make integration > strace_output.txt
[strace_output.txt](https://github.com/enarx/enarx/files/4964205/strace_output.txt)

**Comment by connorkuehl** [comment]
@xiaonan-INTC Thanks for working through this so patiently with me.

I'm reading the `strace_output.txt` and it looks like the tests are passing now except for `syscall_clock_gettime`.

We had a regression in our code that caused `syscall_clock_gettime` to fail. Could you pull the latest changes from our `master` branch and try running the tests again?

**Comment by xiaonan-INTC** [comment]
I tried latest Enarx both on kernel-5.7.8-201.fc32.enarx.sgx.32.x86_64, still failed.
[output.txt](https://github.com/enarx/enarx/files/4969898/output.txt)
[strace_output .txt](https://github.com/enarx/enarx/files/4969899/strace_output.txt)

**Comment by connorkuehl** [comment]
> I tried latest Enarx both on kernel-5.7.8-201.fc32.enarx.sgx.32.x86_64, still failed.
> [output.txt](https://github.com/enarx/enarx/files/4969898/output.txt)
> [strace_output .txt](https://github.com/enarx/enarx/files/4969899/strace_output.txt)

Is this from a clean build?

```
$ cargo make clean
$ cargo make build
$ cargo make integration
```

**Comment by xiaonan-INTC** [comment]
> > I tried latest Enarx both on kernel-5.7.8-201.fc32.enarx.sgx.32.x86_64, still failed.
> > [output.txt](https://github.com/enarx/enarx/files/4969898/output.txt)
> > [strace_output .txt](https://github.com/enarx/enarx/files/4969899/strace_output.txt)
> 
> Is this from a clean build?
> 
> ```
> $ cargo make clean
> $ cargo make build
> $ cargo make integration
> ```

yes, just do as your steps.

And I download latest Enarx source code and do above 2 steps, error changes to:
running 3 tests
test exit_one ... FAILED
test exit_zero ... FAILED
test watchdog ... ok
[output.txt](https://github.com/enarx/enarx/files/4969999/output.txt)

**Comment by npmccallum** [comment]
@xiaonan-INTC We are using Enarx every day. We understand that it is not easy to consume right now. But we are working towards making this easier. The most difficult part of this is that Intel has not yet upstreamed their SGX drivers yet. So this means the remaining platform integration hasn't happened yet. Until the drivers are upstream, there will be some difficulty consuming this.

Please provide the latest output from the following:
```
$ uname -r # This shows your current kernel
$ ls -lh /dev/sgx/ # This shows your device permissions
$ git log -1 # This shows which commit you are trying to build and run
```

Please also ensure that SELinux is disabled:
```
$ sudo setenforce 0
```

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC We are using Enarx every day. We understand that it is not easy to consume right now. But we are working towards making this easier. The most difficult part of this is that Intel has not yet upstreamed their SGX drivers yet. So this means the remaining platform integration hasn't happened yet. Until the drivers are upstream, there will be some difficulty consuming this.
> 
> Please provide the latest output from the following:
> 
> ```
> $ uname -r # This shows your current kernel
> $ ls -lh /dev/sgx/ # This shows your device permissions
> $ git log -1 # This shows which commit you are trying to build and run
> ```
> 
> Please also ensure that SELinux is disabled:
> 
> ```
> $ sudo setenforce 0
> ```

@npmccallum 

Dear npmccallum,

I update kernel patch to kernel-5.7.10-200.fc32.enarx.sgx.32.x86_64, and SGX integration test can pass. :)
Thanks very much for your help!
