### ISSUE TITLE
Check Planning board permissions

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#745]
On the [Planning board](https://github.com/orgs/enarx/projects/3), i can't seem to move cards from Backlog to Nominated.

As I'm not seeing an option to change the state after clicking the card on the board either, but can change the state when i go into the issue itself, it makes me think it's a board permission problem.

@npmccallum, assigning to you as requested :slightly_smiling_face:.

**Comment by npmccallum** [comment]
@axelsimon You're currently in the `contributors` team, which has `Write` access to both `Sprint` and `Planning`. I'm not sure what's missing.

**Comment by axelsimon** [comment]
It's working fine now. Weird.
Thanks for checking, i'll close this one then.
