### ISSUE TITLE
Dynamic output from integration tests

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#747]
Currently, our [integration tests allow us to specify](https://github.com/enarx/enarx/blob/master/integration-tests/tests/common/mod.rs#L71-L78) the input to `stdin` and the expected output on `stdout` and `stderr`. However, this presumes that the outputs are deterministic. https://github.com/enarx/enarx/pull/681 breaks that assumption.

When testing `clock_gettime` we should have the payload print the current time to `stdout` and then have the test harness validate that the output is within an acceptable delta from its own version of `clock_gettime`. Therefore, `run()` function for the tests should be made to return the outputs as `Vec<u8>` and the `clock_gettime` test should be rewritten to handle this.

- [x] Make `run()` return the outputs.
- [x] Fix up existing tests.
- [x] Rewrite `clock_gettime` to output the time, evaluated by the harness.

**Comment by npmccallum** [comment]
FYI @jyotsna-penumaka

**Comment by jyotsna-penumaka** [comment]
@npmccallum should I take it up?
