### ISSUE TITLE
Convert sgx::crypto::Signer to a conditionally compiled method

### ISSUE THREAD

**Issue by kubkon** [enarx/enarx#752]
## Description

As reported by @npmccallum in #746:

`sgx::crypto::Signer` should be converted to a conditionally compiled method instead of an extension trait. The use of the trait was only due to needing to extend a type cross-crate. This also means the only thing left in the crypto module is the Hasher, so the module should probably be renamed.

**Comment by lkatalin** [comment]
@npmccallum Is this still relevant after removing the `Signer` trait and moving `sign()` to be a method on `Measurement` #870 ? Can we close this?

**Comment by npmccallum** [comment]
Fixed in 651dc8314e86ec2cecc4db8cf4d652a8d18a58da.
