### ISSUE TITLE
Make sgx::ioctls module private

### ISSUE THREAD

**Issue by kubkon** [enarx/enarx#754]
## Description

As reported by @npmccallum in #746:

Expose a high-level interface. We already have an imperfect one in `enarx-keep-sgx::builder`. We could move that from `enarx-keep-sgx` to `sgx`. Then `sgx::ioctls` could be made private.

**Comment by mbestavros** [comment]
Resolved in 7e0f42f9a4f1dbef9369d88cadf2304d0d5b3021.
