### ISSUE TITLE
Should sgx::attestation_types be no_std compatible?

### ISSUE THREAD

**Issue by kubkon** [enarx/enarx#755]
## Description

This discussion originated in #746. @lkatalin pointed out that `sgx::attestation_types` should be `no_std` compatible. However, as it currently stands, due to the use of `std::vec::Vec`, for the module to be `no_std` compatible we'd either need to replace any structure requiring a global allocator with a statically-sized equivalent such as a slice, or write our own alloc, and then we are OK to use `alloc::vec::Vec`. Note however that in the latter case we're forced to rely on unstable nightly features since not everything has been stabilised in Rust wrt to custom global allocators (in fact, I'm thinking here mainly of [this issue](https://github.com/rust-lang/rust/issues/51540)).

This purpose of this issue is to gather some feedback as to whether `sgx::attestation_types` should be `no_std` and if so, what the best way of achieving this would be.

**Comment by haraldh** [comment]
I don't think the shim has to use `sgx::attestation_types`.

**Comment by lkatalin** [comment]
@haraldh I forget where we left off in this conversation, but the `TargetInfo` and `Report` types are handled only internally in the SGX enclaves and so the shim both needs these types and the types are not useful anywhere else. 

Related: #https://github.com/enarx/sgx/pull/7
