### ISSUE TITLE
Enarx development environment set up wiki page need to update

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#773]
Hi, all,

I have a suggestion that Enarx development environment set up wiki page need to update as below:
Before running $cargo make build, we must ensure **make**, **perl** are installed, otherwise openssl will fail to build.
If you didn't meet it, your host must install them before, but to a new user like me, I met this issue on different kernels...

Could the wiki page keeper help update? Thanks very much!

**Comment by axelsimon** [comment]
Hi @xiaonan-INTC, that's a very good suggestion, thanks.

The wiki can be updated directly, if you'd like to do that. Otherwise, we'll get to it in the near future.

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC, that's a very good suggestion, thanks.
> 
> The wiki can be updated directly, if you'd like to do that. Otherwise, we'll get to it in the near future.

I have updated it, closed this issue. :)
