### ISSUE TITLE
Organise project to use the DCO

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#775]
Now that we have mostly formalised the use of the Developer Certificate Origin in [RFC 00001](https://github.com/enarx/rfcs/tree/master/00001-developer-certificate-of-origin), we need to get various bits and pieces together to enact that choice.

Here's what i can see that we need:

- Display DCO to new contributors and before allowing pull requests to be opened.
- Set up an automated test to ensure that commits are signed-off. 
  - I suggest that for the time being, this test only warn users if commits in their PR are not signed-off, rather than block the PR from going through.
- Update the documentation (wiki) to mention the DCO.
  - I'm thinking the [How to contribute: code](https://github.com/enarx/enarx/wiki/How-to-contribute-code) page mainly, possibly elsewhere.

Anything else?

**Comment by axelsimon** [comment]
This looks useful: https://github.com/apps/dco
@mbestavros, what say you?

**Comment by axelsimon** [comment]
Current status:
- https://github.com/apps/dco looks good, we will try it soon
- i'm writing a PR template to
  - tell contributors that we use the DCO, 
  - let them see what the DCO looks like,
  - help them fix their commits, if they are missing a sign-off.
- i'm writing an update to the wiki page on how to contribute code

**Comment by axelsimon** [comment]
Status: 
- Mark has an [issue open](https://github.com/enarx/enarx/issues/658) for the DCO / sign-off test
- I have a [PR open](https://github.com/enarx/.github/pull/5) for the PR template reminding people to sign-off their commits
- the [how to contribute code](https://github.com/enarx/enarx/wiki/How-to-contribute-code#developer-certificate-of-origin) wiki page has been updated

**Comment by mbestavros** [comment]
> Mark has an issue open for the DCO / sign-off test

Said issue is now complete! The signoff test is active on the three top-level Enarx repos.
