### ISSUE TITLE
does ukernel act as a libos please?

### ISSUE THREAD

**Issue by superajun-wsj** [enarx/enarx#786]
**Question**

we are interested in details about ukernel, could you please give some more introduction to it?

**Comment by haraldh** [comment]
We currently only support executing position independent statically linked elf binaries (static-pie) and only a specific subset of the linux kernel syscalls.

I guess, you are interested in the KVM/SEV ukernel. It handles some syscalls itsself and some are proxied to the host.

In soon to be merged pull requests, you can see both in action.

syscall proxying:
https://github.com/enarx/enarx/blob/2d0cde660254933fac23f3f9045529416ff864e0/enarx-keep/src/backend/kvm/vm/cpu.rs#L109-L121

syscall handling:
https://github.com/enarx/enarx/blob/d648495a3d07a5ebfa5ce4e63cf093d69d70e4b9/enarx-keep-sev-shim/src/syscall.rs

**Comment by haraldh** [comment]
Let me know, if you want to know more.

**Comment by superajun-wsj** [comment]
> We currently only support executing position independent statically linked elf binaries (static-pie) and only a specific subset of the linux kernel syscalls.
> 
> I guess, you are interested in the KVM/SEV ukernel. It handles some syscalls itsself and some are proxied to the host.
> 
> In soon to be merged pull requests, you can see both in action.
> 
> syscall proxying:
> https://github.com/enarx/enarx/blob/2d0cde660254933fac23f3f9045529416ff864e0/enarx-keep/src/backend/kvm/vm/cpu.rs#L109-L121
> 
> syscall handling:
> https://github.com/enarx/enarx/blob/d648495a3d07a5ebfa5ce4e63cf093d69d70e4b9/enarx-keep-sev-shim/src/syscall.rs

Thanks for your reply very much. I still have two questions:
1. could enarx also support elf binaries? In my opinion, enarx could support wasm, it's one kind of bytecode, while not elf binaries, 
    I am a little confused.
2. as we know, there are some kinds of libos ware designed to support SGX, for example, Occlum and Graphene。My question is
    that whether there is a libos between wasm engine and host kernel?

**Comment by haraldh** [comment]
> Thanks for your reply very much. I still have two questions:
> 
>     1. could enarx also support elf binaries? In my opinion, enarx could support wasm, it's one kind of bytecode, while not elf binaries,
>        I am a little confused.

Yes, it will by default execute the wasmtime jit compiler, but you could also execute other elf binaries, as long as all kernel syscall are handled properly.

> 
>     2. as we know, there are some kinds of libos ware designed to support SGX, for example, Occlum and Graphene。My question is
>        that whether there is a libos between wasm engine and host kernel?

yes, these are the `shim` parts in the repository. Currently `enarx-keep-sgx-shim` and `enarx-keep-sev-shim`. They are executing the elf binary (which will be `keep-runtime`, which will execute the wasm binary).

**Comment by haraldh** [comment]
I am closing this issue. If you want to know more, just reopen it.
