### ISSUE TITLE
Change SGX Layout struct to use offsets

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#788]
Now that the SGX shim is `static-pie` (see #774 ), the `Layout` struct should be changed to use offsets from the base of the enclave to describe the enclave's layout instead of absolute addresses. This way each enclave can be instantiated at an arbitrary place in memory (though it will not be moved after its creation) without each enclave instance having a different hash.

**Comment by platten** [comment]
Layout structure has been removed so this is no longer relevant.
