### ISSUE TITLE
Get video of Jyotsna's talk onto Enarx Youtube channel

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#817]
**Description**

Jyotsna created a video about her work on Enarx as an intern.  We should add this to the Enarx Youtube channel.

**Comment by axelsimon** [comment]
The video is [up and visible](https://www.youtube.com/watch?v=JD70E7HHjlc) on the Enarx Youtube channel. It's been added to the "Learning more about Enarx" playlist.
