### ISSUE TITLE
SGX Attestation Service

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#824]
We need to engage Intel SDK and OpenEnclave SDK through the TAC about creating an SGX Attestation Service for Linux. This should be a daemon that contains the Intel Quoting Enclave and speaks (locally) an established protocol so that all the projects can use it.

On our end, the keep loader will communicate with the service to fetch quotes for remote attestation.

cc @MikeCamel @jyotsna-penumaka @lkatalin

**Comment by MikeCamel** [comment]
Email sent to Aeva van der Veen & Dave Thaler of the OESDK project as a starting point.

**Comment by MikeCamel** [comment]
Dave has expressed an interest on working together on this.

**Comment by lkatalin** [comment]
The steps involved to generate a Quote seem to include:

- [ ] Get the PCE and QE (found [here](https://download.01.org/intel-sgx/sgx-dcap/1.8/linux/) as `.so` files signed by Intel) running as two enclaves in one process (this will have some socket interface)
- [ ] Get QE's response to `sgx_qe_get_target_info(*ti_buf)` (this will generate and certify the AK as a side effect)
- [ ] Generate a Report with the returned TargetInfo
- [ ] Get QE's response to `sgx_qe_get_quote(*report, quote_size, *quote_buf)`

For our purposes, the quote size will always be the same, so calling `sgx_qe_get_quote_size()` can be skipped. All of the loading policy stuff can also be skipped unless required to load the PCE and QE. The Quote Provider seems unnecessary as we will not be using the Quote Verification Library.

**Comment by lkatalin** [comment]
Status update: code exists for all of these steps and the TargetInfo is received and used in generating the Report. In order to test the code, the binary must be run in the enclave, which requires networking syscalls implemented in SGX (see [issue](https://github.com/enarx/enarx-keepldr/issues/9)). Then there will need to be some extensive refactoring.
