### ISSUE TITLE
Make SGX high-level interface more generic

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#826]
Currently, we have a builder which takes a `Span`, adds pages at destination addresses and creates a single enclave object that can be entered while passing a few register values into the enclave. This needs to be improved.

1. The builder should take an enclave size which is a power of two. It should let the kernel choose the location of the enclave using the double allocation strategy of the kernel's sgx selftest. The builder can then have a `span() -> Span` method.

2. The builder should take pages using enclave offset values.

3. The builder should keep a `Vec` of all TCS pages added by address.

4. The enclave object should get the `Unmap` and the `Vec` of TCS page addresses.

5. A `Thread` object should be created which steals a TCS address from the enclave.

6. The `Thread` object should be enterable. It should have a `Registers` struct that contains all registers we can pass into/from the enclave.

7. With this high-level interface we can make the `ioctls` module private.

cc @lkatalin

**Comment by platten** [comment]
We no longer have a generic builder.
