### ISSUE TITLE
Ubuntu20.04 dev environment setup

### ISSUE THREAD

**Issue by johnvenn** [enarx/enarx#838]
I was setting up environment on ubuntu20.04

do the steps as in https://github.com/enarx/enarx/wiki/How-to-contribute-code

then run "cargo make build" in enarx rep folder.

I found json scripts in keep-runtime and integration-tests points to /usr/x86_64-linux-musl/lib64 folder, which in my environment
 for musl was /usr/lib/x86_64-linux-musl.

thus there was error.

Is there any better solutions on this ? such as we could make this folder as an env and json just write the env instead of hard code it into the json file.

**Comment by haraldh** [comment]
This will go away with rust `1.46`, so if you can wait until then, it will fix itself.

**Comment by johnvenn** [comment]
ok, so i'll close this issue.
