### ISSUE TITLE
Error occurred during SGX remote attestation process

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#843]
HW: Intel NUC7JY
SW: Ubuntu 18.04

Demo: https://github.com/enarx-archive/demo/tree/master/intel-sgx

Issues:
1. About "How to Run the SGX Demo" - step 7, 
$cd /demo/intel-sgx
$cargo build --release

Error message is as below:
error[E0599]: no function or associated item named `for_target` found for struct `sgx_isa::Report` in the current scope
  --> attestation-enclave/src/main.rs:25:21
   |
25 |             Report::for_target(&qe_id, &report_data)
   |                     ^^^^^^^^^^ function or associated item not found in `sgx_isa::Report`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `attestation-enclave`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

2. About "How to Run the SGX Demo" - step 8, what is the specific command line?

**Comment by lkatalin** [comment]
Hi @xiaonan-INTC , you should know that the demo you are trying to run is currently archived and not maintained. It has various dependencies that are probably out of date or may no longer work correctly with each other. All of our current and maintained code can be found in the [enarx](https://github.com/enarx/enarx) repo of our organization.

However, your issue #1 makes me think you are not compiling for the required Fortanix target. The `attestation-enclave` specifically can only run when compiled for the Fortanix target with `cargo run --target x86_64-fortanix-unknown-sgx`. The Fortanix target must be added to your Rust nightly toolchain first with `rustup target add x86_64-fortanix-unknown-sgx --toolchain nightly` as described on the [Fortanix page](https://github.com/fortanix/rust-sgx) and in step 4 of the archived demo.

Your issue #2 about step 8 involves locating the file containing the partial PCK certificate chain (it should not include the leaf certificate, only root and intermediate) as [described](https://github.com/enarx-archive/demo/tree/master/intel-sgx#retrieving-pck-certificate-chain-for-intel-sgx-remote-attestation). It is assumed that you downloaded this PCK certificate chain in the previous step. Did you download this? 

For example, if my partial PCK certificate chain was downloaded to a file `~/pck_chain.pem` then in step 8 I would run `cargo run ~/pck_chain.pem` in the `attestation-tenant` directory.

I hope that is helpful. Please let me know if you have more questions.

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC , you should know that the demo you are trying to run is currently archived and not maintained. It has various dependencies that are probably out of date or may no longer work correctly with each other. All of our current and maintained code can be found in the [enarx](https://github.com/enarx/enarx) repo of our organization.
> 
> However, your first issue makes me think you are not compiling for the required Fortanix target. The `attestation-enclave` specifically can only run when compiled for the Fortanix target with `cargo run --target x86_64-fortanix-unknown-sgx`. The Fortanix target must be added to your Rust nightly toolchain first with `rustup target add x86_64-fortanix-unknown-sgx --toolchain nightly` as described on the [Fortanix page](https://github.com/fortanix/rust-sgx) and in step 4 of the archived demo.
> 
> Your second issue about step 8 involves locating the file containing the partial PCK certificate chain (it should not include the leaf certificate, only root and intermediate) as [described](https://github.com/enarx-archive/demo/tree/master/intel-sgx#retrieving-pck-certificate-chain-for-intel-sgx-remote-attestation). It is assumed that you downloaded this PCK certificate chain in the previous step. Did you download this?
> 
> For example, if my partial PCK certificate chain was downloaded to a file `~/pck_chain.pem` then in step 8 I would run `cargo run ~/pck_chain.pem` in the `attestation-tenant` directory.
> 
> I hope that is helpful. Please let me know if you have more questions.

hi, @lkatalin 

Thanks a lot for your support~~ I have succeeded in building attestation-enclave & attestation-daemon. :)
But when I built attestation-tenant in /demo/intel-sgx/attestation-tenant by "cargo run ~/pck_chain.pem", I met an error as below:
Error: Compat { error: ErrorMessage { msg: "Invalid certification data type: PpidEncryptedRsa3072" } }
 
And the pck_chain.pem is retrieved from https://github.com/enarx-archive/demo/tree/master/intel-sgx - Retrieving PCK certificate chain for Intel SGX Remote Attestation.

**Comment by xiaonan-INTC** [comment]
I have enabled Intel SGX remote attestation on Enarx, thanks to all of your support!
Here are some points need to be added and updated of the Enarx wiki: https://github.com/enarx-archive/demo/tree/master/intel-sgx
I will do this and close this issue now.
