### ISSUE TITLE
Red Hat Research Day 2020 Enarx Presentation

### ISSUE THREAD

**Issue by axelsimon** [enarx/enarx#9]
Mark and Lily are to present on Enarx at RHRD in San Francisco on April 26, 2020. The abstract was submitted to Gagan Kumar Nov. 15 2019.

# Dates
Event: April 26, 2020

# Location
San Francisco

# CFP
N/A

**Comment by lkatalin** [comment]
This proposal was not accepted for RHRD - it didn't fit with the other topics.
