### ISSUE TITLE
Investigate acceptability of ISC licence for project.

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#909]
The ISC licence has come up as a blocker for acceptance of some of our code.  Need to decide whether to add it to our list of allowed licences.

**Comment by mbestavros** [comment]
According to the ISC license's [Wikipedia](https://en.wikipedia.org/wiki/ISC_license) page:

> It is functionally equivalent to the simplified BSD and MIT licenses, but without language deemed unnecessary following the Berne Convention.

We already accept both MIT and variants of BSD (per [`deny.toml`](https://github.com/enarx/enarx/blob/master/deny.toml)), so I don't think I see a problem also accepting ISC. But I also don't want to make a ruling unilaterally.

**Comment by mbestavros** [comment]
Let's move conversation over to #928. That's an explicit deliverable that we can accept or reject.
