### ISSUE TITLE
Red Hat Summit 2020 - Demo/Session

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#91]
# Dates
Event: April 27-29, 2020

# Location
Moscone Center, San Francisco, California

# CFP
N/A

https://www.redhat.com/en/summit

**Comment by axelsimon** [comment]
Red Hat Summit 2020 is now a virtual event, but this session is still happening and will be recorded very soon :)

**Comment by mbestavros** [comment]
Talk has been delivered and archived!
