### ISSUE TITLE
Get Intel's QE working with the current driver

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#912]
Normally, Intel's Quoting Enclave requires its own separate driver, the DCAP driver listed [here](https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-dcap-linux-1.0-release). We need to know how this differs from the driver we're using now and how to use the QE with this current driver.

There is also a separate Quoting Library, Enclave Common, and Quote Provider that ordinarily must be installed separately to use Intel's DCAP. What do these involve? How can we get them working with our current code? This may be its own separate issue.

**Comment by lkatalin** [comment]
I would consider this done via Intel's AESMD (we may want a more streamlined way to do this in the future).

**Comment by mbestavros** [comment]
Closing at request of author.
