### ISSUE TITLE
What is the plan of Enarx release?

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#922]
Hi, dear Enarx developers and maintainers,

Will Enarx plan to have some release versions or candidates or even tags (like v1.0, etc.) with kernel patch, source code, binaries, installation packages, test cases, documentation, etc.?
We want to do some development on Enarx with Intel SGX, but we saw Enarx updates and changes very frequently, and no stable and mature production for development and validation.
Thanks a lot!

**Comment by npmccallum** [comment]
@xiaonan-INTC 

Our strategy is to have four components:
  * `keepldr`
  * `wasmldr`
  * `keepmgr`
  * `client`

Of these four, the most difficult is the `keepldr`. The good news is that we (just today) split it out of the https://github.com/enarx/enarx repo into the https://github.com/enarx/enarx-keepldr repo. The reason for this move is that we are preparing for an alpha release (without attestation).

We also have proofs-of-concept for the other components which we hope to merge into their own repos in the coming weeks. The easiest way to get things going today is to build `enarx-keepldr`. Apart from installing a few dependencies and the `musl` target, this should be pretty straightforward (as of today).

Does this answer your question?

cc @MikeCamel

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC
> 
> Our strategy is to have four components:
> 
> * `keepldr`
> * `wasmldr`
> * `keepmgr`
> * `client`
> 
> Of these four, the most difficult to build is the `keepldr`. The good news is that we (just today) split it out of the https://github.com/enarx/enarx repo into the https://github.com/enarx/enarx-keepldr repo. The reason for this move is that we are preparing for an alpha release (without attestation).
> 
> We also have proofs-of-concept for the other components which we hope to merge into their own repos in the coming weeks. The easiest way to get things going today is to build `enarx-keepldr`. Apart from installing a few dependencies and the `musl` target, this should be pretty straightforward (as of today).
> 
> Does this answer your question?
> 
> cc @MikeCamel

thanks a lot @npmccallum , very expect Enarx alpha release, :)

**Comment by xiaonan-INTC** [comment]
Sorry to reopen this issue, @npmccallum 

Another question, does Enarx alpha release have crate to support Intel SGX? And are there any SGX related test cases?

**Comment by MikeCamel** [comment]
@xiaonan-INTC - we definitely plan to support SGX as part of the wasmldr crate.

**Comment by npmccallum** [comment]
@xiaonan-INTC Yes. You can checkout `enarx-keepldr` and run `ENARX_BACKEND=sgx cargo test`. That will force it to run the tests on SGX.

**Comment by npmccallum** [comment]
@xiaonan-INTC You can see an example of an SGX test run here: https://github.com/enarx/enarx-keepldr/runs/1095551646?check_suite_focus=true

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Yes. You can checkout `enarx-keepldr` and run `ENARX_BACKEND=sgx cargo test`. That will force it to run the tests on SGX.

Thanks a lot @npmccallum 
But I tried your command line and got the same error as issue [10](https://github.com/enarx/enarx-keepldr/issues/10).

**Comment by xiaonan-INTC** [comment]
Dear @npmccallum 

Sorry to trouble, 
What is the progress of Enarx re-structing and when do you paln to release alpha? 
And will Enarx have an entry of building and running with readme since it will be split into 4 components?

**Comment by platten** [comment]
We have had multiple releases since this issue was filed. Please feel free to reopen in case you have any additional questions.
