### ISSUE TITLE
Get the SGX QE3 and PCE running

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#930]
In order to perform Remote Attestation on an SGX platform, the attesting Keep needs to be able to receive data ("Target Info") from Intel's Quoting Enclave (QE3) and send data ("Report") to it for verification. The QE3 must also be able to communicate with the Provisioning Certification Enclave (PCE) during these steps. The QE3 and PCE are distributed by Intel as signed `.so` libraries found [here](https://download.01.org/intel-sgx/sgx-dcap/1.8/linux/) under `prebuilt_decap_1.8.tar.gz`. The source code is also available, ex. the QE3 code is [here](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/quote_wrapper/quote/enclave/quoting_enclave_3.cpp).

Requirements:
- The QE3 and PCE must run in secure memory. Each should run in its own SGX enclave.
- The QE3 and PCE should run in the same process, which will be a daemon. It is possible to run two SGX enclaves in one process.
- The QE3 and PCE that we use should be the `.so` libraries distributed by Intel because these are signed by Intel and therefore trusted.
- The end result should be that the process with the QE3 and PCE should be able to talk to other processes (such as our attesting Keep) over a socket and use Intel's API to request a `TargetInfo` or a `Quote`.
- It is *not* necessary that the QE3 and PCE process should be loaded into an Enarx Keep. It could run in an SGX enclave without Enarx, for example by using Intel's Architectural Enclave Service Manager (AESM). However, running it in a Keep may be the easiest way for us to get it running quickly if we can load it despite the fact that it is a `.so`.

**Comment by lkatalin** [comment]
I would consider this preliminarily done, as we can currently use Intel's AESMD to retrieve a QE TargetInfo. We will most likely want to construct a more streamlined daemon for this, which could be a continuation of this issue or a separate issue based on the requirements listed above.

**Comment by mbestavros** [comment]
Closing at request of author -- done.
