### ISSUE TITLE
fail to build keepldr on Fedora 32

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#937]
HW: Intel NUC7JY
SW: Fedora 32 64bit

Reproducible steps:
Following https://github.com/enarx/enarx-keepldr
1. Install Dependencies
2. Install Rust, Nightly and the MUSL target
3. Build
    $ git clone https://github.com/enarx/enarx-keepldr
    $ cd enarx-keepldr/
    $ cargo build

Error message:

   Compiling structopt v0.3.20
warning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `x86_64 v0.12.2` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `compiler_builtins v0.1.36` within 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `compiler_builtins v0.1.36` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.12.2` within 30s)
error: failed to download from `https://crates.io/api/v1/crates/x86_64/0.12.2/download`

Caused by:
  [28] Timeout was reached (download of `x86_64 v0.12.2` failed to transfer more than 10 bytes in 30s)
error: failed to run custom build command for `enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)`

Caused by:
  process didn't exit successfully: `/home/sgx/enarx-keepldr/target/debug/build/enarx-keepldr-0a398bc11a31e944/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=PROFILE
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  cargo:rerun-if-changed=internal/rcrt1/Cargo.tml
  cargo:rerun-if-changed=internal/rcrt1/Cargo.toml
  cargo:rerun-if-changed=internal/rcrt1/Cargo.lock
  cargo:rerun-if-changed=internal/rcrt1/.cargo/config
  cargo:rerun-if-changed=internal/rcrt1/src/lib.rs
  cargo:rerun-if-changed=internal/shim-sev/Cargo.tml
  cargo:rerun-if-changed=internal/shim-sev/Cargo.toml
  cargo:rerun-if-changed=internal/shim-sev/Cargo.lock
  cargo:rerun-if-changed=internal/shim-sev/.cargo/config
  cargo:rerun-if-changed=internal/shim-sev/build.rs
  cargo:rerun-if-changed=internal/shim-sev/src/payload.rs
  cargo:rerun-if-changed=internal/shim-sev/src/addr.rs
  cargo:rerun-if-changed=internal/shim-sev/src/asm.rs
  cargo:rerun-if-changed=internal/shim-sev/src/main.rs
  cargo:rerun-if-changed=internal/shim-sev/src/no_std.rs
  cargo:rerun-if-changed=internal/shim-sev/src/paging.rs
  cargo:rerun-if-changed=internal/shim-sev/src/hostlib.rs
  cargo:rerun-if-changed=internal/shim-sev/src/syscall.rs
  cargo:rerun-if-changed=internal/shim-sev/src/hostcall.rs
  cargo:rerun-if-changed=internal/shim-sev/src/lazy.rs
  cargo:rerun-if-changed=internal/shim-sev/src/gdt.rs
  cargo:rerun-if-changed=internal/shim-sev/src/usermode.rs
  cargo:rerun-if-changed=internal/shim-sev/src/start.S
  cargo:rerun-if-changed=internal/shim-sev/src/random.rs
  cargo:rerun-if-changed=internal/shim-sev/src/frame_allocator.rs
  cargo:rerun-if-changed=internal/shim-sev/src/shim_stack.rs
  cargo:rerun-if-changed=internal/shim-sev/src/print.rs

  --- stderr
  Failed to build shim internal/shim-sev

Can anyone help check this error?

**Comment by connorkuehl** [comment]
> Compiling structopt v0.3.20
> warning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `x86_64 v0.12.2` failed to transfer more than 10 bytes in 30s)
> warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `compiler_builtins v0.1.36` within 30s)
> warning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `compiler_builtins v0.1.36` failed to transfer more than 10 bytes in 30s)
> warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.12.2` within 30s)
> error: failed to download from `https://crates.io/api/v1/crates/x86_64/0.12.2/download`
> 
> Caused by:
> [28] Timeout was reached (download of `x86_64 v0.12.2` failed to transfer more than 10 bytes in 30s)
> error: failed to run custom build command for `enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)`

Hi @xiaonan-INTC -- this looks like a network issue. Have you tried this again since posting the issue on a reliable network connection?

**Comment by xiaonan-INTC** [comment]
> > Compiling structopt v0.3.20
> > warning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `x86_64 v0.12.2` failed to transfer more than 10 bytes in 30s)
> > warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `compiler_builtins v0.1.36` within 30s)
> > warning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `compiler_builtins v0.1.36` failed to transfer more than 10 bytes in 30s)
> > warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `x86_64 v0.12.2` within 30s)
> > error: failed to download from `https://crates.io/api/v1/crates/x86_64/0.12.2/download`
> > Caused by:
> > [28] Timeout was reached (download of `x86_64 v0.12.2` failed to transfer more than 10 bytes in 30s)
> > error: failed to run custom build command for `enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)`
> 
> Hi @xiaonan-INTC -- this looks like a network issue. Have you tried this again since posting the issue on a reliable network connection?

@connorkuehl 
Yes, but all other crates could be downloaded normally, so it is a little strange :(

Here is a workaround I used to omit this error:
1. Download **compiler_builtins**, **array-const-fn-init** & **x86_64** from:
https://github.com/rust-lang/compiler-builtins
https://github.com/haraldh/array-const-fn-init
https://github.com/rust-osdev/x86_64
2. Unzip and copy them to enarx-keepldr/internal/.
3. Modify shim-sgx/Cargo.toml:
compiler_builtins = { path = "../compiler-builtins", version = "0.1", default-features = false, features = [ "mem" ] }
    Modify shim-sev/Cargo.toml:
compiler_builtins = { path = "../compiler-builtins", version = "0.1", default-features = false, features = [ "mem" ] }
x86_64 = { path = "../x86_64", version = "0.12", default-features = false, features = ["instructions", "inline_asm"] }
array-const-fn-init = { path = "../array-const-fn-init", version = "0.1" }

Then $cargo build and $cargo test would pass.
