### ISSUE TITLE
Would Soft-RT (kernel-rt) workloads be compatible with Enarx?

### ISSUE THREAD

**Issue by jarcher** [enarx/enarx#945]
**Question**
I'm working with scenarios where we are trying to address Linux usage on control systems. I read that RT use cases are currently out of scope for Enarx. Is this position due to a lack of support for RTOS chipsets or does this statement relate to a lack of support for libraries like kernel-rt?

**Comment by MikeCamel** [comment]
Hi, @jarcher - thanks for the question.

Real-time isn't a property that we're targetting at all with Enarx at the moment, though it's possible that we may look at it in the future.  Given the performance impact of existing TEEs, such work is unlikely to be starting soon.  That said, we'd be interested in any tests you run - we've not really started on performance measurement yet, as we're still working to get the full stack up and fairly stable first.

-Mike.
