### ISSUE TITLE
Does Enarx support CentOS?

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#948]
Question 1: I use **f1f62272df5088ba2ed2adc61cb801c5d2e4a692** of Enarx master on CentOS 8.2, it would fail as below:

error: failed to run custom build command for `enarx-keep-sev-shim v0.1.0 (/root/xzhao24/enarx/enarx-keep-sev-shim)`

Caused by:
  process didn't exit successfully: `/root/xzhao24/enarx/enarx-keep-sev/target/debug/build/enarx-keep-sev-shim-3179f5f6b3bf6c23/build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  Info: default compiler flags are disabled
  running: "cc" "-Wall" "-Wextra" "-O2" "-mtune=znver2" "-o" "/root/xzhao24/enarx/enarx-keep-sev/target/debug/build/enarx-keep-sev-shim-7bf1747e33cfbd7e/out/asm.o" "-c" "/root/xzhao24/enarx/enarx-keep-sev-shim/src/asm.s"
  exit code: 0
  Info: default compiler flags are disabled
  running: "cc" "-Wall" "-Wextra" "-O2" "-mtune=znver2" "-o" "/root/xzhao24/enarx/enarx-keep-sev/target/debug/build/enarx-keep-sev-shim-7bf1747e33cfbd7e/out/rcrt1.o" "-c" "/root/xzhao24/enarx/enarx-keep-sev-shim/src/rcrt1.c"
  cargo:warning=cc1: error: bad value (‘znver2’) for ‘-mtune=’ switch
  cargo:warning=cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 generic native; did you mean ‘znver1’?
  exit code: 1

  --- stderr
  [/root/xzhao24/enarx/enarx-keep-sev-shim/build.rs:30] &entries = [
      "/root/xzhao24/enarx/enarx-keep-sev-shim/src/asm.s",
      "/root/xzhao24/enarx/enarx-keep-sev-shim/src/rcrt1.c",
      "/root/xzhao24/enarx/enarx-keep-sev-shim/src/start.S",
      "/root/xzhao24/enarx/enarx-keep-sev-shim/src/syscall.S",
      "/root/xzhao24/enarx/enarx-keep-sev-shim/src/usermode.S",
  ]

  error occurred: Command "cc" "-Wall" "-Wextra" "-O2" "-mtune=znver2" "-o" "/root/xzhao24/enarx/enarx-keep-sev/target/debug/build/enarx-keep-sev-shim-7bf1747e33cfbd7e/out/rcrt1.o" "-c" "/root/xzhao24/enarx/enarx-keep-sev-shim/src/rcrt1.c" with args "cc" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.

Question 2: Since I saw that Enarx is re-structing project & source code for months, which branch of Enarx master is the final available one?

**Comment by xiaonan-INTC** [comment]
I modified "znver2" to "znver1" and rebuilt:
    cc::Build::new()
        .no_default_flags(true)
        .flag("-O2")
        // Optimize for AMD Zen 2
        .flag("-mtune=znver1")
        .files(&entries)
        .static_flag(true)
        .shared_flag(false)
        .compile("asm");

It still failed due to following error:
   Compiling enarx-keep-sev-shim v0.1.0 (/root/xzhao24/enarx/enarx-keep-sev-shim)
error: missing documentation for a function
  --> src/asm.rs:8:5
   |
8  |     pub fn _enarx_asm_triple_fault() -> !;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/main.rs:11:9
   |
11 | #![deny(missing_docs)]
   |         ^^^^^^^^^^^^

error: missing documentation for a function
 --> src/syscall.rs:6:5
  |
6 |     pub fn _syscall_enter() -> !;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to 2 previous errors
error: could not compile `enarx-keep-sev-shim`

It seems that Enarx cannot build on CentOS, could anyone double-check and confirm in your side? Thanks a lot!

**Comment by haraldh** [comment]
> Question 1: I use f1f6227 of Enarx master on CentOS 8.2, it would fail as below:

Why are you using f1f6227 ?? We moved on to: https://github.com/enarx/enarx-keepldr

> I modified "znver2" to "znver1" and rebuilt […]

You can remove that option completely, it makes no real difference.

> error: missing documentation for a function

Well, that is fixed in later commits ... e.g. 34f33637acc887473cb5c0444caece7886964783

Why do you use f1f6227 ???

**Comment by xiaonan-INTC** [comment]
> > Question 1: I use [f1f6227](https://github.com/enarx/enarx/commit/f1f62272df5088ba2ed2adc61cb801c5d2e4a692) of Enarx master on CentOS 8.2, it would fail as below:
> 
> Why are you using [f1f6227](https://github.com/enarx/enarx/commit/f1f62272df5088ba2ed2adc61cb801c5d2e4a692) ?? We moved on to: https://github.com/enarx/enarx-keepldr
> 
> > I modified "znver2" to "znver1" and rebuilt […]
> 
> You can remove that option completely, it makes no real difference.
> 
> > error: missing documentation for a function
> 
> Well, that is fixed in later commits ... e.g. [34f3363](https://github.com/enarx/enarx/commit/34f33637acc887473cb5c0444caece7886964783)
> 
> Why do you use [f1f6227](https://github.com/enarx/enarx/commit/f1f62272df5088ba2ed2adc61cb801c5d2e4a692) ???

@haraldh 
Thanks haraldh!

BTW, now Enarx entry has been changed to the keepldr(https://github.com/enarx/enarx-keepldr) as you mentioned, right? 
I tried keepldr on CentOS 8.2 and it works well!

**Comment by haraldh** [comment]
> BTW, now Enarx entry has been changed to the keepldr(https://github.com/enarx/enarx-keepldr) as you mentioned, right?
> I tried keepldr on CentOS 8.2 and it works well!

@xiaonan-INTC : yes, cool
