### ISSUE TITLE
How does Enarx keep for Intel SGX use in latest Enarx architecture?

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#951]
In latest enarx_slides_2020-12.pdf, if user wants to use Intel SGX within Enarx, the command is as below: 
$target/x86_64-unknown-linux-musl/debug/enarx-keep-sgx --shim target/x86_64-unknown-linux-musl/debug/enarx-keep-sgx-shim --code ~/test
But at prsent, Enarx entry changes to https://github.com/enarx/enarx-keepldr, so how does Enarx keep for Intel SGX use in latest Enarx architecture?

**Comment by lkatalin** [comment]
Hi @xiaonan-INTC , sorry that demo is out of date and will be replaced with a new one as it is available. For now, I think what you want is to clone the `enarx-keepldr` repo and run `cargo test --features=backend-sgx` to specify that you want to run our current tests for the SGX backend. Does this work for you?

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC , sorry that demo is out of date and will be replaced with a new one as it is available. For now, I think what you want is to clone the `enarx-keepldr` repo and run `cargo test --features=backend-sgx` to specify that you want to run our current tests for the SGX backend. Does this work for you?

Thanks a lot @lkatalin 

But when I cargo build latest enarx-keepldr on Fedora 32, I met an error as below:
   Compiling enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)
warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `spinning v0.1.0` within 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `spinning v0.1.0` within 30s)

I cannot find this package: spinning v0.1.0, and cannot download from network by manual.
Does you and anyone meet this error and have solutions?

**Comment by lkatalin** [comment]
@xiaonan-INTC Hmm, I've never actually seen that issue. A few ideas:

- Do you have any `Cargo.lock` file yet? If you have one, can you delete `Cargo.lock` and see if the error persists?
- Do you have anything in your `~/.cargo/config` under `[http]`? Does the error persist if you set `multiplexing = false` under `[http]`?
- How are you trying to download `spinning v0.1.0` manually - what command do you use and what error do you get?

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Hmm, I've never actually seen that issue. A few ideas:
> 
> * Do you have any `Cargo.lock` file yet? If you have one, can you delete `Cargo.lock` and see if the error persists?
> * Do you have anything in your `~/.cargo/config` under `[http]`? Does the error persist if you set `multiplexing = false` under `[http]`?
> * How are you trying to download `spinning v0.1.0` manually - what command do you use and what error do you get?
> 
> Edit:
> For example, does something like `curl https://static.crates.io/crates/spinning/spinning-0.1.0.crate --output spinning-0.1.0.crate` work?

@lkatalin 
Really appraciate your help! It works now! :)
