### ISSUE TITLE
cargo test failed for some basic functions test cases

### ISSUE THREAD

**Issue by xiaonan-INTC** [enarx/enarx#952]
environment: Fedora 32 + NUC7JY
branch: 230b5c2a31cd0c6ca4a8bf37f09732f6bd022912

$cargo build -- PASS
$cargo test   -- FAIL, error message is as below:

running 22 tests
test bind ... FAILED
test clock_gettime ... FAILED
test close ... FAILED
test echo ... FAILED
test exit_one ... ok
test exit_zero ... FAILED
test get_att ... FAILED
test getegid ... FAILED
test geteuid ... FAILED
test getgid ... FAILED
test getuid ... FAILED
test listen ... FAILED
test memory_stress_test ... FAILED
test memspike ... FAILED
test read ... FAILED
test read_udp ... FAILED
test readv ... FAILED
test socket ... FAILED
test write_emsgsize ... ignored
test unix_echo ... FAILED
test write_stderr ... FAILED
test write_stdout ... FAILED

failures:

---- bind stdout ----
thread 'bind' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- clock_gettime stdout ----
thread 'clock_gettime' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- close stdout ----
thread 'close' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- echo stdout ----
thread 'echo' panicked at 'failed to write stdin to child: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', tests/integration_tests.rs:78:14

---- exit_zero stdout ----
thread 'exit_zero' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- get_att stdout ----
thread 'get_att' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- getegid stdout ----
thread 'getegid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- geteuid stdout ----
thread 'geteuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- getgid stdout ----
thread 'getgid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- getuid stdout ----
thread 'getuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- listen stdout ----
thread 'listen' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- memory_stress_test stdout ----
thread 'memory_stress_test' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- memspike stdout ----
thread 'memspike' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- read stdout ----
thread 'read' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 10]`: Expected contents of stdout output differs', tests/integration_tests.rs:106:13

---- read_udp stdout ----
thread 'read_udp' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `65507`: Expected length of stdout output differs', tests/integration_tests.rs:36:5

---- readv stdout ----
thread 'readv' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100]`: Expected contents of stdout output differs', tests/integration_tests.rs:106:13

---- socket stdout ----
thread 'socket' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- unix_echo stdout ----
thread 'unix_echo' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- write_stderr stdout ----
thread 'write_stderr' panicked at 'assertion failed: `(left == right)`
  left: `[69, 114, 114]`,
 right: `[104, 105, 10]`: Expected contents of stderr output differs', tests/integration_tests.rs:30:5

---- write_stdout stdout ----
thread 'write_stdout' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 105, 10]`: Expected contents of stdout output differs', tests/integration_tests.rs:106:13

failures:
    bind
    clock_gettime
    close
    echo
    exit_zero
    get_att
    getegid
    geteuid
    getgid
    getuid
    listen
    memory_stress_test
    memspike
    read
    read_udp
    readv
    socket
    unix_echo
    write_stderr
    write_stdout

test result: FAILED. 1 passed; 20 failed; 1 ignored; 0 measured; 0 filtered out; finished in 2.26s

**Comment by lkatalin** [comment]
Hi @xiaonan-INTC - I suspect your problem may be that you are not using the custom Fedora kernel for Enarx, which is required currently to run the SGX Keep. What is the output of `uname -r`? What is the output of `ls -la /dev/sgx`?

If you are okay updating your kernel to be the custom kernel, you can take these steps to install it from our [COPR repo](https://copr.fedorainfracloud.org/coprs/npmccallum/enarx/) (disclaimer: these are sometimes under active development):

First, make sure secure boot is disabled in the BIOS. Then run:
```
dnf copr enable npmccallum/enarx && dnf update
```

Then reboot. Your output from `uname -r` should now be something like:
`5.10.8-200.1.enarx.sgx.41.fc33.x86_64`

In case you do not want to update your kernel to this custom kernel, you also have the option of becoming a contributor and using our development environment detailed [here](https://github.com/enarx/enarx/wiki/How-to-use-the-lab-machines).

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC - I suspect your problem may be that you are not using the custom Fedora kernel for Enarx, which is required currently to run the SGX Keep. What is the output of `uname -r`? What is the output of `ls -la /dev/sgx`?
> 
> If you are okay updating your kernel to be the custom kernel, you can take these steps to install it from our [COPR repo](https://copr.fedorainfracloud.org/coprs/npmccallum/enarx/) (disclaimer: these are sometimes under active development):
> 
> First, make sure secure boot is disabled in the BIOS. Then run:
> 
> ```
> dnf copr enable npmccallum/enarx && dnf update
> ```
> 
> Then reboot. Your output from `uname -r` should now be something like:
> `5.10.8-200.1.enarx.sgx.41.fc33.x86_64`
> 
> In case you do not want to update your kernel to this custom kernel, you also have the option of becoming a contributor and using our development environment detailed [here](https://github.com/enarx/enarx/wiki/How-to-use-the-lab-machines).

Thanks for the patient reply, @lkatalin 

I upgrade my Fedora 32 according to your link: https://copr.fedorainfracloud.org/coprs/npmccallum/enarx/ - Fedora 32 repo download, is that right?

$uname -r
>>5.10.8-100.1.enarx.sgx.41.fc32.x86_64
$ls -la /dev/sgx
>>ls: cannot access '/dev/sgx_': No such file or directory
$ls -la /dev/sgx_
>>sgx_enclave    sgx_provision
And I chmod those 2 sgx_* files to crwxrwxrwx.

But those failures still occurred, I will try the option of becoming a contributor and using your development environment.

**Comment by lkatalin** [comment]
@xiaonan-INTC Yes, the kernel looks right. We are currently working on smoothing out some breaking changes made to how SGX interacts with the new kernel - if you don't mind giving us a few days, I can notify you when this should all be working and that may resolve your problem.

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Yes, the kernel looks right. We are currently working on smoothing out some breaking changes made to how SGX interacts with the new kernel - if you don't mind giving us a few days, I can notify you when this should all be working and that may resolve your problem.

OK, I keep waiting and really appreciate you, @lkatalin :)

**Comment by lkatalin** [comment]
@xiaonan-INTC Thanks for your patience. We've updated our SGX code and it should now work with the custom kernel version that you have (which should also be the final version of that kernel to match finalized upstream patches). Do you mind pulling the new version from our master branch (commit 64f21b6b707898006557cd99b86fb05b7e9755c6 and later) to see if the tests will pass? If not, please let us know.

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Thanks for your patience. We've updated our SGX code and it should now work with the custom kernel version that you have (which should also be the final version of that kernel to match finalized upstream patches). Do you mind pulling the new version from our master branch (commit [enarx/enarx-keepldr@64f21b6](https://github.com/enarx/enarx-keepldr/commit/64f21b6b707898006557cd99b86fb05b7e9755c6) and later) to see if the tests will pass? If not, please let us know.

hi, @lkatalin 
I switch enarx-keepldr to 64f21b6b707898006557cd99b86fb05b7e9755c6 but still got same failures:

[sgx@localhost enarx-keepldr]$ cargo test
   Compiling enarx-keepldr v0.1.0 (/home/sgx/enarx-keepldr)
warning: missing documentation for an associated functioneepldr(build)
   --> /home/sgx/enarx-keepldr/internal/x86_64/src/structures/paging/page_table.rs:199:5
    |
199 |     pub fn new() -> Self {
    |     ^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> /home/sgx/enarx-keepldr/internal/x86_64/src/lib.rs:12:9
    |
12  | #![warn(missing_docs)]
    |         ^^^^^^^^^^^^

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
    Finished test [unoptimized + debuginfo] target(s) in 33.01s
     Running target/debug/deps/enarx_keepldr-8d4d4d7122ebbe60

running 12 tests
test sallyport::tests::buf_capacity ... ok
test sallyport::tests::block_size ... ok
test sallyport::tests::copy_into_slice ... ok
test sallyport::tests::cursor ... ok
test sallyport::tests::cursor_multiple_allocs ... ok
test sallyport::tests::msg_size ... ok
test sallyport::tests::rep_size ... ok
test sallyport::tests::req_size ... ok
test sallyport::tests::request ... ok
test sallyport::tests::syscall ... ok
test sallyport::tests::copy_into_raw_parts ... ok
test sallyport::tests::test_read_write ... ok

test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/integration_tests-9932cf5e5cef98e3

running 22 tests
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test clock_gettime ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test bind ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test close ... FAILED
test echo ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test exit_one ... ok
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test exit_zero ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test get_att ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test getegid ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test geteuid ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test getgid ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test getuid ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test listen ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test memory_stress_test ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test memspike ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test read ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test read_udp ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test readv ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test socket ... FAILED
test write_emsgsize ... ignored
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test unix_echo ... FAILED
test write_stderr ... FAILED
Error: Shutdown Ok(
    kvm_regs {
        rax: 0x2170ed,
        rbx: 0xffffff8000000000,
        rcx: 0x29d003,
        rdx: 0x0,
        rsi: 0x200000,
        rdi: 0x3000,
        rsp: 0x0,
        rbp: 0x0,
        r8: 0x0,
        r9: 0x0,
        r10: 0x0,
        r11: 0x0,
        r12: 0x0,
        r13: 0x0,
        r14: 0x0,
        r15: 0x0,
        rip: 0x2170e5,
        rflags: 0x10006,
    },
)
test write_stdout ... FAILED

failures:

---- clock_gettime stdout ----
thread 'clock_gettime' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bind stdout ----
thread 'bind' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- close stdout ----
thread 'close' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- echo stdout ----
thread 'echo' panicked at 'failed to write stdin to child: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', tests/integration_tests.rs:78:14

---- exit_zero stdout ----
thread 'exit_zero' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- get_att stdout ----
thread 'get_att' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- getegid stdout ----
thread 'getegid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- geteuid stdout ----
thread 'geteuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- getgid stdout ----
thread 'getgid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- getuid stdout ----
thread 'getuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- listen stdout ----
thread 'listen' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- memory_stress_test stdout ----
thread 'memory_stress_test' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- memspike stdout ----
thread 'memspike' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- read stdout ----
thread 'read' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 10]`: Expected contents of stdout output differs', tests/integration_tests.rs:106:13

---- read_udp stdout ----
thread 'read_udp' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `65507`: Expected length of stdout output differs', tests/integration_tests.rs:36:5

---- readv stdout ----
thread 'readv' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100]`: Expected contents of stdout output differs', tests/integration_tests.rs:106:13

---- socket stdout ----
thread 'socket' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- unix_echo stdout ----
thread 'unix_echo' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/integration_tests.rs:128:9

---- write_stderr stdout ----
thread 'write_stderr' panicked at 'assertion failed: `(left == right)`
  left: `[69, 114, 114]`,
 right: `[104, 105, 10]`: Expected contents of stderr output differs', tests/integration_tests.rs:30:5

---- write_stdout stdout ----
thread 'write_stdout' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 105, 10]`: Expected contents of stdout output differs', tests/integration_tests.rs:106:13


failures:
    bind
    clock_gettime
    close
    echo
    exit_zero
    get_att
    getegid
    geteuid
    getgid
    getuid
    listen
    memory_stress_test
    memspike
    read
    read_udp
    readv
    socket
    unix_echo
    write_stderr
    write_stdout

test result: FAILED. 1 passed; 20 failed; 1 ignored; 0 measured; 0 filtered out; finished in 2.21s

error: test failed, to rerun pass '--test integration_tests'

**Comment by lkatalin** [comment]
@xiaonan-INTC Have you tried with `cargo test --no-default-features --features=backend-sgx`? It looks like there is some kvm-related output, which is one of the other backends.

**Comment by xiaonan-INTC** [comment]
> @xiaonan-INTC Have you tried with `cargo test --no-default-features --features=backend-sgx`? It looks like there is some kvm-related output, which is one of the other backends.

@lkatalin thanks a lot, it all got PASS!

running 14 tests
test backend::sgx::attestation::tests::req_ti ... ok
test backend::sgx::attestation::tests::req_quote ... ok
test sallyport::tests::buf_capacity ... ok
test sallyport::tests::copy_into_raw_parts ... ok
test sallyport::tests::copy_into_slice ... ok
test sallyport::tests::cursor ... ok
test sallyport::tests::cursor_multiple_allocs ... ok
test sallyport::tests::msg_size ... ok
test sallyport::tests::rep_size ... ok
test sallyport::tests::req_size ... ok
test sallyport::tests::request ... ok
test sallyport::tests::syscall ... ok
test sallyport::tests::test_read_write ... ok
test sallyport::tests::block_size ... ok

test result: ok. 14 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/integration_tests-67fc5f2254b4175e

running 23 tests
test clock_gettime ... ok
test bind ... ok
test close ... ok
test echo ... ok
test exit_one ... ok
test exit_zero ... ok
test get_att ... ok
test getegid ... ok
test geteuid ... ok
test getgid ... ok
test getuid ... ok
test listen ... ok
test memory_stress_test ... ok
test memspike ... ok
test read ... ok
test read_udp ... ok
test readv ... ok
test sgx_get_att_quote ... ok
test socket ... ok
test write_emsgsize ... ignored
test unix_echo ... ok
test write_stderr ... ok
test write_stdout ... ok

test result: ok. 22 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 2.61s
