### ISSUE TITLE
Enarx DnD Party

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#953]
The Enarx team is finalizing some significant breakthroughs around demoing Enarx's end-to-end functionality. To celebrate, we'd like to host a DnD party for the team.

This issue should be considered _extremely_ high priority.

**Comment by mbestavros** [comment]
Tagging @npmccallum @MikeCamel @connorkuehl @lkatalin @ueno @ambaxter @mbestavros -- let's get this done.

**Comment by connorkuehl** [comment]
We partied.
