### ISSUE TITLE
Tests fail for enarx-keepldr

### ISSUE THREAD

**Issue by agal19** [enarx/enarx#954]
Hello I tried to run the tests on enarx-keepldr but most of them fail.
environment: Operating System: "openSUSE Tumbleweed"
                      Kernel Version: 5.11.3-1-default
                      Firmware Version: Platform Family 17, Model 31

paltform: Backend: sev
 ✔ CPU Manufacturer: AuthenticAMD
 ✔  Microcode support: AMD EPYC 7262 8-Core Processor                 
 ✔  Secure Memory Encryption (SME)
 ✔   Physical address bit reduction: 47
 ✔   C-bit location in page table entry: 15
 ✔  Secure Encrypted Virtualization (SEV)
 ✔   Number of encrypted guests supported simultaneously: 509
 ✔   Minimum ASID value for SEV-enabled, SEV-ES disabled guest: 5
 ✔  Secure Encrypted Virtualization Encrypted State (SEV-ES)
 ✔  Page Flush MSR available
 ✔ Driver: /dev/sev
 ✔  SEV is enabled in host kernel
 ✔  /dev/sev is readable by user
 ✔  /dev/sev is writable by user
 ✔ KVM support
 ✔ MEMLOCK rlimit allows for: ~3518437208883 keeps (soft limit = 18446744073709551615 bytes, hard limit = 18446744073709551615 bytes)
Backend: kvm
 ✔ Driver: /dev/kvm
 ✔  API Version: 12

Do you know what could be the problem?

running 12 tests
test sallyport::tests::block_size ... ok
test sallyport::tests::cursor ... ok
test sallyport::tests::buf_capacity ... ok
test sallyport::tests::copy_into_slice ... ok
test sallyport::tests::cursor_multiple_allocs ... ok
test sallyport::tests::copy_into_raw_parts ... ok
test sallyport::tests::rep_size ... ok
test sallyport::tests::req_size ... ok
test sallyport::tests::msg_size ... ok
test sallyport::tests::request ... ok
test sallyport::tests::syscall ... ok
test sallyport::tests::test_read_write ... ok

test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration_tests.rs (target/debug/deps/integration_tests-b265800b4d4e31b5)

running 24 tests
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test clock_gettime ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test close ... FAILED
test echo ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test exit_one ... ok
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test exit_zero ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test get_att ... FAILED
test write_emsgsize ... ignored
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test getegid ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test geteuid ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test getuid ... FAILED

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer
test getgid ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test listen ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test memory_stress_test ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test read ... FAILED

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer
test memspike ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test read_udp ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test readv ... FAILED
test sev_get_att_quote ... ok
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test socket ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test uname ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test unix_echo ... FAILED
test write_stderr ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test write_stdout ... FAILED
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    failed to fill whole buffer

attestation_bridge Error: failed to deserialize expected certificate chain

Caused by:
    Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })
test bind ... FAILED

failures:

---- clock_gettime stdout ----
thread 'clock_gettime' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- close stdout ----
thread 'close' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- echo stdout ----
thread 'echo' panicked at 'failed to write stdin to child: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', tests/integration_tests.rs:78:14

---- exit_zero stdout ----
thread 'exit_zero' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- get_att stdout ----
thread 'get_att' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- getegid stdout ----
thread 'getegid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- geteuid stdout ----
thread 'geteuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- getuid stdout ----
thread 'getuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- getgid stdout ----
thread 'getgid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- listen stdout ----
thread 'listen' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- memory_stress_test stdout ----
thread 'memory_stress_test' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- read stdout ----
thread 'read' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 10]: Expected contents of stdout output differs`', tests/integration_tests.rs:106:13

---- memspike stdout ----
thread 'memspike' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- read_udp stdout ----
thread 'read_udp' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `65507: Expected length of stdout output differs`', tests/integration_tests.rs:36:5

---- readv stdout ----
thread 'readv' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100]: Expected contents of stdout output differs`', tests/integration_tests.rs:106:13

---- socket stdout ----
thread 'socket' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- uname stdout ----
thread 'uname' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- unix_echo stdout ----
thread 'unix_echo' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

---- write_stderr stdout ----
thread 'write_stderr' panicked at 'assertion failed: `(left == right)`
  left: `[69, 114, 114]`,
 right: `[104, 105, 10]: Expected contents of stderr output differs`', tests/integration_tests.rs:30:5

---- write_stdout stdout ----
thread 'write_stdout' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 105, 10]: Expected contents of stdout output differs`', tests/integration_tests.rs:106:13

---- bind stdout ----
thread 'bind' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0: Expected exit status differs.`', tests/integration_tests.rs:128:9

failures:
    bind
    clock_gettime
    close
    echo
    exit_zero
    get_att
    getegid
    geteuid
    getgid
    getuid
    listen
    memory_stress_test
    memspike
    read
    read_udp
    readv
    socket
    uname
    unix_echo
    write_stderr
    write_stdout

test result: FAILED. 2 passed; 21 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.36s

error: test failed, to rerun pass '--test integration_tests'

**Comment by connorkuehl** [comment]
@agal19 enarx-keepldr is looking for an SEV certificate chain to use for part of the launch process.

If you clone and build [sevctl](https://github.com/enarx/sevctl), you can use it to export the certificate chain like this:

```console
$ mkdir -p /var/cache/amd-sev
$ sevctl export --full /var/run/cache/amd-sev/chain
```

Then enarx-keepldr will be able to use it to launch.

**Comment by agal19** [comment]
Thank you, exporting the environment variable helped.
