### ISSUE TITLE
Modularize AESM daemon for ease of use

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#968]
This is probably a longer-term goal with a lot of fiddly pieces. Goals may include:
- Dropping the use of protobuf
- Removing the dependencies on the whole of the Intel SDK, etc.
- Having something that is easy to install / deploy on a machine, rather than multiple moving pieces that all must be installed to work together

Possible alternatives: relying on [aesm-client](https://crates.io/crates/aesm-client) (but this also has some dependency issues, to be investigated)

**Comment by platten** [comment]
No longer applicable.
