### ISSUE TITLE
Add TPM information on wiki

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#98]
Made changes to the FAQ here:

https://github.com/enarx/enarx/wiki/Enarx-FAQ#is-enarx-a-host-attestation-project
https://github.com/enarx/enarx/wiki/Enarx-FAQ#does-enarx-useneed-a-tpm

Please review.

**Comment by axelsimon** [comment]
Changes look good to me. A welcome addition.

I think we should also add something about WASM in the FAQ.

**Comment by MikeCamel** [comment]
Agreed - please open a new issue for WASM.

**Comment by MikeCamel** [comment]
Thanks.

Please create an issue for WASM in the FAQ.
