### ISSUE TITLE
Extend/standardize backend::Datum to give client-relevant data

### ISSUE THREAD

**Issue by wgwoods** [enarx/enarx#984]
Right now `Backend.data()` returns a `Vec<Datum>` giving some information about the host's support for that backend:
```rust
pub struct Datum {
    /// The name of this datum.
    pub name: String,

    /// Whether the datum indicates support for the platform or not.
    pub pass: bool,

    /// Short additional information to display to the user.
    pub info: Option<String>,

    /// Longer explanatory message on how to resolve problems.
    pub mesg: Option<String>,
}
```

This is all human-readable information explaining the boolean pass/fail, and it's really only helpful for doing local debugging.

For a client-server case, there's other data we will want to expose - one possible example is the maximum supported enclave size. Some of these Data may be backend-specific (e.g. the maximum enclave size supported by this backend technology) but there may also be host-specific Data as well (e.g. maximum enclave size allowed/supported by this host system). We will need to present these in a machine-readable form so the client can use them to make decisions about its behavior.

This means we'd probably need something like:

- [ ] Well-defined names or numeric IDs for each Datum
- [ ] Data containing values other than `pass`/`fail`
- [ ] Per-datum info about whether this Datum is..
   - [ ] backend-specific or host-specific?
   - [ ] only useful for local debugging?
   - [ ] relevant to a client/tenant?
   - [ ] security sensitive (e.g. exposes information about the host system)?

**Comment by platten** [comment]
No longer applicable with current design.
